sites/docs/docs/troubleshooting.md

"offset is longer than source length" can also occur if the query identifier in the markdown block starts with a number.

Added another root cause to common error

---

.github/ISSUE_TEMPLATE/bug_report.md
packages/db-orchestrator/package.json
packages/mysql/.gitignore
packages/mysql/index.cjs
packages/mysql/package.json
pnpm-lock.yaml
sites/docs/docs/getting-started/connect-data-warehouse.md
sites/docs/docs/queries/sql-queries.md

add mysql support

---

sites/example-project/src/components/ui/ChevronToggle.svelte
sites/example-project/src/components/ui/QueryViewer.svelte
sites/example-project/src/components/ui/QueryViewerSupport/Prismjs.svelte
sites/example-project/src/components/ui/QueryViewerSupport/QueryDataTable.svelte

- Remove whitespace in transition of query viewer closing
- Add transition for query viewer chevron when opening and closing
- Make transition smooth for pagination portion of query data table - previously was snapping shut later than the rest of the table
- Add blur transition to SQL code to cover flash of unstyled code when opening the code pane of the query viewer
- Add blur transition to table when opening the data table pane
- Add a link to the settings page when user receives `Missing database credentials` error

Misc UI fixes

---

.changeset/grumpy-cats-accept.md
packages/evidence/package.json
sites/docs/docs/components/charts/bubble-chart.md
sites/example-project/src/components/viz/Bubble.svelte
sites/example-project/src/components/viz/BubbleChart.svelte

BubbleChart's scaling function contained a bug that was making the bubble areas not proportional to one another. This PR makes each bubble the correct area relative to other points in the dataset. This also includes a `scaleTo` prop, which allows you to increase or decrease the size of the largest bubble (similar to Excel's functionality for bubble charts).

Bubble chart fixes

---

sites/example-project/src/components/ui/BreadCrumbs.svelte
sites/example-project/src/components/ui/Sidebar.svelte

- replaceAll function isn't available on node versions <= 14. Replaced those references with global regex
- Fixed edge cases on sidebar nav menu where user has folders and files with the word "index" in them

remove replaceAll function and fix sidebar path parse logic

---

sites/example-project/src/components/ui/Databases/SqliteForm.svelte
sites/example-project/src/pages/api/settings.json.js

- Change gitignore filepath to reference two directories above the current directory (to reference the root directory of the proejct)
- This references the root gitignore for the example-project, which is not the correct one for running that project, but does allow us to test that the functionality of editing the gitignore file in a user's project root will work.
- Change check of sqlite extensions in gitignore to use regex (account for "sqlite" being contained in "sqlite3")

fix gitignore filepath and gitignore check for sqlite extensions

---

packages/preprocess/index.cjs
sites/example-project/src/components/ui/BreadCrumbs.svelte
sites/example-project/src/components/ui/Header.svelte
sites/example-project/src/components/ui/stores.js
sites/example-project/src/components/viz/BarChart.svelte
sites/example-project/src/pages/__layout.svelte

At the moment, all pages display the show/hide queries button. This change removes the button if there are no queries on the page.
The way this works is:
- New variable `pageHasQueries` is added to the same store used by `showQueries`
- In the `preprocess` package, the `hasQueries()` function is used to determine if a page has queries or not
- Based on the result of that function, `pageHasQueries` store value is updated
- In `Breadcrumbs.svelte`, the button is not shown if `pageHasQueries` is `false`
This also fixes an issue where the show/hide query button was not working in `example-project`

Hide the show/hide queries button if no queries on page

---

sites/example-project/src/components/viz/ErrorChart.svelte

Including a scrollable area in the chart error component causes an error in Windows - it makes all chart errors appear with both horizontal and vertical scrollbars, even if there isn't scrollable content. 
Fixing this requires setting up custom scrollbars to work across OS/browsers (which we have in our QueryViewer component).
Easier fix for now is to extend the height of the chart error until the full error message is visible. Otherwise, the min height will be 150px (same as height of a typical working chart).

Chart error scroll fix for Windows

---

sites/docs/docs/vscode-extension.md

The VS Code extension blocks the shortcut for accessing markdown preview. This PR adds a workaround to the docs to access markdown preview when the Evidence extension is enabled in VS Code.
We'll attempt to support the default markdown preview (perhaps with enhancements specific to Evidence) in a future version.

add note about markdown preview for vs code extension

---

sites/example-project/src/components/ui/QueryViewer.svelte
sites/example-project/src/components/ui/stores.js

As a user in dev mode, it's frustrating that query results collapse every time the page reloads.
Desired behaviour: 
- The query results are kept as shown / hidden based on what the state was before reload
Rough approach
- Store the state of each query in local storage, and read from there on reload
Questions
- This seems like a weird implementation of storage - I feel like you typically put svelte store variables in store.js?
- But since (I think) you want to control each query independently, you'd perhaps need to independently make variables for each query - and you don't know how many there are before the queries are compiled. So I put them in the component instead.
Next
- It would seem logical to also include the show/hide state of the query text itself, once we've worked out the best …

Persistent query show/hide states

---

.changeset/cuddly-news-film.md
sites/example-project/src/components/ui/stores.js

Discussed in #260
- Fixing the behaviour so that in dev mode queries are shown by default.

Devmode showhide fix

---

.changeset/big-pears-laugh.md
packages/evidence/cli.js
packages/telemetry/index.cjs
pnpm-lock.yaml
sites/example-project/src/components/ui/TelemetryOptOut/TelemetrySettingsPanel.svelte
sites/example-project/src/pages/settings/index.svelte

Closes #255, adds a panel to the development settings page with information on what data we're collecting, and the option to toggle off telemetry.

255 settings telemetry opt out

---

.github/workflows/tests.yml

Reduce noise in our telemetry by opting CI/CD jobs out.

Excludes CI/CD from telemetry

---

.changeset/shiny-walls-shout.md
package.json
pnpm-lock.yaml
sites/example-project/package-lock.json
sites/example-project/package.json
sites/example-project/src/components/modules/echarts-canvas.js
sites/example-project/src/components/modules/echartsCanvasDownload.js
sites/example-project/src/components/viz/Chart.svelte
sites/example-project/src/components/viz/ECharts.svelte

This PR adds a feature to download a chart to a PNG file with one click. The download button appears at the bottom right of the chart on hover.
- File name of exported file is `evidence-chart.png`
- Background of the image is white
- Pixel ratio is 3x, which seems to generate crisp images across devices
- Background colour to be changed to transparent in future iterations (pending fix of y-axis title background issue)
- This does not handle situations where the legend is paginated
- It would be preferable for the file name to contain some more descriptive info (query name, chart type, etc.)

Download chart to PNG

---

.changeset/mean-squids-film.md
sites/example-project/src/components/modules/getSortedData.js
sites/example-project/src/components/viz/Bar.svelte
sites/example-project/src/components/viz/BarChart.svelte

Currently, the `getSortedData()` function sorts a dataset without making a copy of it, meaning the original dataset shown in the query viewer is altered.
This PR changes the sort behaviour so that sort is only applied to a copy of the dataset within the component sorting it. This will make the query viewer table respect the `order by` statement in SQL rather than reflecting however a component was sorting the data.

Fix sorting side-effects issue

---

.changeset/curvy-frogs-check.md
packages/snowflake/index.cjs
sites/example-project/src/components/ui/Databases/SnowflakeForm.svelte

- The snowflake connector does not have fields for warehouse and database name. 
- This means `select 10 as num` works - it does not need to find a database. This is what we use to test the connection.
- However if you `select * from database_name` you get the error:
- Add (mandatory) warehouse and database name fields to the snowflake connector form.
- Are there any other files we need to update? (I think no, but can't tell)
- Is there any reason we would not want these fields to be mandatory?
- Where in the css can you change the grey colour of the placeholder text, I think users are finding it a bit dark and assuming it's filled in.

Snowflake connector update

---

packages/evidence-vscode/snippets/emd.code-snippets
sites/docs/docs/features/advanced/parameterized-pages.md
sites/docs/docs/features/advanced/templating.md
sites/docs/docs/features/charts/area-chart.md
sites/docs/docs/features/charts/bar-chart.md
sites/docs/docs/features/charts/bubble-chart.md
sites/docs/docs/features/charts/histogram.md
sites/docs/docs/features/charts/line-chart.md
sites/docs/docs/features/charts/mixed-type-charts.md
sites/docs/docs/features/charts/scatter-plot.md
sites/docs/docs/features/data-table.md
sites/docs/docs/features/markdown/value.md
sites/docs/docs/features/queries/sql-queries.md
sites/docs/docs/getting-started/edit-your-project.md
sites/docs/docs/tutorial/add-a-chart.md
sites/docs/docs/tutorial/advanced-loops.md
sites/docs/docs/tutorial/advanced-parameterized-pages.md
sites/docs/docs/tutorial/use-query-results-in-text.md
sites/docs/docs/walkthroughs/evidence-chart-library.md
sites/docs/package-lock.json
sites/example-project/package-lock.json

Took a quick look at how the docs would need to change to reflect that queries can be referenced directly.  It was mostly a search and replace so I just opened a PR (with the exception of sql-queries.md).  Opening this for feedback.

Extension + Doc changes for referencing queries without having to reference the `data` object

---

.changeset/lovely-items-kneel.md
sites/example-project/src/components/modules/formatValue.js
sites/example-project/src/components/viz/Bubble.svelte
sites/example-project/src/components/viz/BubbleChart.svelte
sites/example-project/src/components/viz/Chart.svelte
sites/example-project/src/components/viz/Hist.svelte
sites/example-project/src/components/viz/Scatter.svelte
sites/example-project/src/components/viz/ScatterPlot.svelte
sites/example-project/src/pages/newpage.md

This PR adds value and column title formatting to chart tooltips.
It includes:
- ECharts custom `formatter` function to pull in value and title formats as specified through column format tags
- Specific tooltip formats for `<ScatterPlot/>`, `<BubbleChart/>`, and `<Histogram/>` which override the default chart tooltip
- Add more columns to the tooltips for `<ScatterPlot/>` and `<BubbleChart/>`
- These should include at least one identifier column (e.g., Product Name)
- The right behaviour might be to include all columns from the query result in the tooltip to start, then provide an option to exclude specific columns
- If we add these options, we should probably also include a prop where you can specify exactly which column(s) you would like to appear in the tooltip
- Add back the feature …

Extend formatting system to chart tooltips

---

.changeset/kind-steaks-laugh.md
sites/example-project/src/components/ui/QueryViewerSupport/QueryDataTable.svelte

Happy to look at an icon in the future, but I think this is probably the most straightforward for now, and doesn't require a tooltip. I also think we can add a few additional "sub-header" rows like these to display a couple other things in the future: extents, distributions, central tendency, that type of thing. 
- also cleans up formatting of boolean (and treatment of "false") 
- ~~we should switch to a tabular font in here (compare the widths of the two gdp figures). I'll open an issue for this.~~ [edit: done]

indicate types, fix boolean styling

---

.changeset/lucky-tigers-swim.md
.changeset/tiny-maps-cheer.md
sites/example-project/src/components/ui/Databases/SqliteForm.svelte
sites/example-project/src/pages/api/settings.json.js

If your project doesn't have a `.gitignore` file:
- Selecting SQLite as your database on the Settings page throws an error.
If your project doesn't have a `.gitignore` file:
- Selecting SQLite as your database does not throw an error.
- If you save a SQLite database on your Settings page and set "Gitignore All SQLite Files" to `true`, Evidence will create a new `.gitignore` file in the root of your project and add SQLite extensions to it.
- If you set "Gitignore All SQLite Files" to false, Evidence will save the database, but will not create a `.gitignore` file

Fix missing gitignore error in settings

---

.changeset/serious-bottles-study.md
packages/evidence/scripts/build-template.js
pnpm-lock.yaml
sites/example-project/package.json

The ssf library was needed from code in the components.
It seems to that it is the `package.json` in the example project that gets copied as the package.json in the components package, so I added the dependency there.  However, I still noticed that the dependency has to be listed on the top level package.json file for the example project to work.

Added ssf dependency to the component project

---

.changeset/lovely-maps-love.md
packages/preprocess/index.cjs

Turns on styling for quotes, so when you save a quote in your `.md` file, it includes curly quotes on your webpage.
Quotes included in SQL queries appear the same way (as straight quotes rather than curly).

Turn on quote formatting in mdsvex

---

.changeset/sharp-mails-train.md
sites/example-project/src/components/modules/autoFormatting.js
sites/example-project/src/components/modules/builtInFormats.js
sites/example-project/src/pages/newpage.md

Makes two changes:
1. Changes thresholds for applying units to numbers. 
- Eg for applying "k": Median value boundary moved from 1,000 -> 5,000
2. Adds a 0 currency suffix format. eg `usd0`. This was missing.

Editing format tags

---

.changeset/rich-cows-rescue.md
sites/example-project/src/app.css
sites/example-project/src/components/ui/Hamburger.svelte
sites/example-project/src/components/ui/Sidebar.svelte

**Why**
The mobile hamburger is currently in an unexpected location (bottom-left)
This makes it hard to find, and can also mean it is not clear when evidence is in "mobile" mode.
**What is best practice?**
When you look at most modern websites and apps, the mobile hamburger menu is either in the top left (eg Github - this page, https://www.adidas.ca/), or top right (eg https://getbootstrap.com/, https://www.nike.com).
**Potential solution**
- This PR includes a top right positioning.
- This is a pretty easy implementation as it doesn't block the current nav items.
- This can be done with the slide-in as is, from the left, or altering the slide-in to be from the right. See gifs below. 
- Personally prefer the slide from the left as before, but keen to hear other views
**From Left** …

Mobile Hamburger configuration

---

.changeset/clean-seals-dance.md
packages/preprocess/index.cjs

reverts the change in #346, to prevent MDSVEX from introducing errors when users include a string in svelte template syntax. e.g. `{"this should render"}`

revert smart quotes

---

sites/example-project/src/components/modules/echarts.js
sites/example-project/src/components/viz/Area.svelte
sites/example-project/src/components/viz/AreaChart.svelte
sites/example-project/src/components/viz/Bar.svelte
sites/example-project/src/components/viz/BarChart.svelte
sites/example-project/src/components/viz/Bubble.svelte
sites/example-project/src/components/viz/BubbleChart.svelte
sites/example-project/src/components/viz/Chart.svelte
sites/example-project/src/components/viz/DataTable.svelte
sites/example-project/src/components/viz/Hist.svelte
sites/example-project/src/components/viz/Histogram.svelte
sites/example-project/src/components/viz/Line.svelte
sites/example-project/src/components/viz/LineChart.svelte
sites/example-project/src/components/viz/Scatter.svelte
sites/example-project/src/components/viz/ScatterPlot.svelte
sites/example-project/src/components/viz/Value.svelte
sites/example-project/src/pages/test-analysis.md

Adds reactivity to charts using `$`:
https://svelte.dev/tutorial/reactive-declarations
https://svelte.dev/tutorial/reactive-statements
https://svelte.dev/tutorial/reactive-assignments
Tested manually by going through example project pages and changing queries.

Add reactivity to charts

---

.changeset/cold-timers-swim.md
sites/example-project/src/components/ui/Formatting/BuiltInFormatGrid.svelte
sites/example-project/src/components/ui/Formatting/CollapsibleTableSection.svelte
sites/example-project/src/components/ui/Formatting/CurrencyFormatGrid.svelte
sites/example-project/src/components/ui/Formatting/CustomFormatGrid.svelte
sites/example-project/src/components/ui/Formatting/CustomFormatsSection.svelte
sites/example-project/src/components/ui/Formatting/FormattingSettingsPanel.svelte
sites/example-project/src/components/ui/Formatting/format-grid.css
sites/example-project/src/components/ui/QueryViewerSupport/prismtheme.css
sites/example-project/src/pages/settings/index.svelte

Some further refinements on the styling and copy in the formats section of the settings. 
- Data tables aligned to header, increased size, removed border box 
- More obvious interaction and working transitions in the currencies section 
- Cleaned up description + example 
- Remove layers on the custom formats section. Form is visible from the beginning, only one action. 
- Collapsible section in the custom formats area serves the same purpose as collapsible sections above it. 
- Collapse all sections to ensure that the custom formats input is visible from the docs section at the top.
**After**

Settings formatting nits

---

.changeset/popular-bats-tell.md
packages/postgres/index.cjs
sites/example-project/src/components/modules/getColumnEvidenceType.js

- User reported difficult connecting to Cube.js via their [Postgres SQL API](https://cube.dev/docs/backend/sql)
- Cube.js compiles queries, and then passes the results back to the query engine.
- Cube.js by default uses camel case for the names of the fields that are passed back
- The postgres connector lowercases all of the field names: `myColumn` -> `mycolumn`
- But the `evidenceType` column name is not lowercased
- This means that if when Evidence looks for the type of `mycolumn` it cannot find it.
Result:
- Lowercase the field name for the column types object also

Postgres Connector Case Normalization Fix

---

.changeset/purple-cougars-sip.md
sites/example-project/src/components/modules/getSeriesConfig.js

In `getSeriesConfig`, there was a scenario where we were passing echarts an unformatted column title - it only showed up in single series charts. This PR passes a formatted title instead, solving the tooltip formatting issue.
Closes #385

Fix tooltip column title formatting issue

---

.changeset/thick-items-turn.md
sites/docs/docs/features/charts/bubble-chart.md
sites/docs/docs/features/charts/scatter-plot.md
sites/example-project/src/components/modules/getSeriesConfig.js
sites/example-project/src/components/viz/Bubble.svelte
sites/example-project/src/components/viz/BubbleChart.svelte
sites/example-project/src/components/viz/Chart.svelte
sites/example-project/src/components/viz/Scatter.svelte
sites/example-project/src/components/viz/ScatterPlot.svelte
sites/example-project/src/pages/charts/bubble-chart.md
sites/example-project/src/pages/charts/scatter-plot.md

This PR improves tooltips in scatter and bubble charts by letting you pass in a column to use as the title for the tooltip.
For example, if you are charting a list of products and their characteristics, you may want to show the product name as the title of the tooltip, rather than only showing the metrics associated with that product.
- `tooltipTitle` prop - pass in a column which will be used as the title for the tooltip (best for identifying individual items in your data - e.g., products, countries)
- Axis titles are now turned on by default for scatter and bubble charts
- The `size` column used in a bubble chart is now appended with a `(size)` indicator so you know which column is driving size differences across points

Scatter and bubble chart tooltip enhancement

---

.changeset/cuddly-carrots-type.md
sites/example-project/src/app.css
sites/example-project/src/components/modules/echartsCopy.js
sites/example-project/src/pages/__layout.svelte

Resolves: 
- Axis only copying (caused by leaving animation on in the copy target) 
- Separate issue with inconsistent treatment of PNGs landing in MS word (switched to jpeg) 
Adds `⌘A` keyboard shortcut support 
- Styling to restrict text selection to the main article section of the page
- Addition of a non breaking space at the end of each article to ensure text selection reaches the end of all content 
Demo

359 charts not copying properly

---

.changeset/cold-ears-fetch.md
sites/example-project/src/components/modules/formatting.js

This PR turns off format tag usage for columns where type is `string`.
Currently, if you apply a format tag to a string, it will work with whatever information is contained in the column. This is normally fine, but occasionally it can mask an underlying type issue. For example, if you have dates stored as strings, applying a date format tag may work in 90% of cases, but the remainder of the cases will give the wrong date (due to timezone conversions) and it will be difficult to debug.
Turning off format tags for strings is an effort to bring type issues to light earlier through this workflow:
- Run query as normal
- Check that data is formatted correctly in query viewer
- If something looks off or unformatted, check the data type in the query viewer for that column
- Edit SQL query as …

Turn off format tags for string columns

---

.changeset/tame-pens-beam.md
sites/example-project/src/components/modules/formatting.js
sites/example-project/src/components/ui/QueryViewerSupport/QueryDataTable.svelte
sites/example-project/src/pages/dates-and-times/index.md

This PR applies consistent date and time treatment across components.
Prior to these changes, the following components used the `getParsedDate` function logic to handle dates:
- `Value`
- `DataTable`
- `Chart` (axes)
The following components and functions were using default javascript logic, which in some cases led to different date results:
- `QueryDataTable`
- `formatValue`
These changes update `QueryDataTable` and `formatValue` to treat dates consistently to the other components mentioned above.
- QueryDataTable showing dates inconsistent with query input
- Chart tooltips not matching axis label values
Consistency is the first issue to solve for date handling in Evidence, but there are still two remaining issues related to dates:
1. Fix `getParsedDate` logic to be applicable across all …

Apply consistent date handling across components

---

.changeset/popular-maps-give.md
sites/example-project/src/components/modules/dateParsing.js
sites/example-project/src/components/modules/formatting.js
sites/example-project/src/components/modules/getParsedDate.js
sites/example-project/src/components/ui/QueryViewerSupport/QueryDataTable.svelte
sites/example-project/src/components/viz/Chart.svelte
sites/example-project/src/components/viz/DataTable.svelte
sites/example-project/src/components/viz/Value.svelte
sites/example-project/src/pages/database-specific/bigquery-dates.md
sites/example-project/src/pages/database-specific/postgres-dates.md
sites/example-project/src/pages/database-specific/snowflake-dates.md
sites/example-project/src/pages/database-specific/sqlite-dates.md

This PR implements improved date parsing.
- Each database returns slightly different date strings
- Each browser interprets and parses dates differently depending on the format of the string
- Safari and Firefox return `Invalid Date` in several scenarios
- Chart not able to use dates from Snowflake if they include a timestamp
- Splits `getParsedDate` into a few functions and saves them in a module called `dateParsing`
- **`standardizeDateString`** - Parses any date string and attempts to get it into a standard format `YYYY-MM-DDTHH:MM:SS`
- **`standardizeDateColumn`** - Applies `standardizeDateString` to a full column in a data object
- **`convertColumnToDate`** - Applies `standardizeDateString` to a full column plus `new Date()`
- Adds date string standardization to `Chart.svelte`
- …

Date parsing improvements

---

.changeset/angry-bats-live.md
.changeset/gorgeous-cars-doubt.md
packages/evidence/cli.js
packages/evidence/scripts/build-template.js
sites/docs/docs/features/advanced/custom-components.md
sites/test-env/components/Hello.svelte
sites/test-env/pages/firstquery.md

This adds the the first part of this [feature](https://github.com/evidence-dev/evidence/issues/430).
It allows users to build their own components, stored in `./components/` to use in markdown files in their Evidence project.
- Should these components automatically be added to the imports?
- so that users don't have to import their custom components at the top of markdown files
- Should all custom components also import all the Evidence components?
- so using Evidence components inside custom components is easy
I think these may both come with trade-offs

Support Custom Components Library

---

.changeset/red-rocks-love.md
sites/example-project/src/components/modules/dateParsing.js

Allows for null values in date columns, which were previously throwing errors.
There were two issues happening here:
1. `standardizeDateString` function was not able to handle nulls at all. Added a quick check so if a null is encountered, the function leaves it as is
2. `convertColumnToDate` function was running `new Date` on all values, including nulls. This was causing it to return Jan 1, 1970 when it encountered nulls. Added a check so it leaves nulls as is.

Fix null date bug

---

.changeset/fluffy-plants-shake.md
sites/example-project/src/pages/__layout.svelte

@mcrascal this is the thing I was mentioning yesterday
- Weird "getting larger as you make width smaller" effect. Toggles between 70ch and 80ch width
- Especially odd when there is no Table of Contents
- Always 70ch width
Thoughts?

Consistent article width across breakpoint

---

.github/workflows/tests.yml
sites/docs/docs/features/advanced/parameterized-pages.md

- Tests fail from PRs from non maintainers. 
- This is because forks by default do not have access to the secrets that are needed for the tests to run.
- Set up `pull_request_target` to trigger the action. This can access secrets.
- However, this requires an authentication workflow to ensure there are not malicious attempts to use said secrets.
- This is set up, such that maintainers will have to "approve" PRs, allowing the tests to run
- For existing maintainers / contributors, approval is automatic
This is well explained (and mainly copied from) [here](https://dev.to/petrsvihlik/using-environment-protection-rules-to-secure-secrets-when-building-external-forks-with-pullrequesttarget-hci)

Add pull_request_target and approval workflow

---

sites/docs/docs/features/advanced/templating.md
sites/docs/docs/features/queries/query-chaining.md
sites/docs/docs/features/queries/sql-queries.md

While reading through docs, I noticed some minor problems with SQL queries and a typo, this PR fixes them.
- [Missing groupby](https://docs.evidence.dev/features/queries/sql-queries#query-blocks)
- [The last query is not valid for most DB engines, you need an alias for the subquery](https://docs.evidence.dev/features/queries/query-chaining#example)
- typo [componet](https://docs.evidence.dev/features/advanced/templating#text-expressions)

Some minor fixes for docs

---

.changeset/pink-panthers-tell.md
sites/example-project/src/components/ui/BreadCrumbs.svelte
sites/example-project/src/components/ui/Header.svelte
sites/example-project/src/components/ui/Sidebar.svelte
sites/example-project/src/pages/__layout.svelte

Fixes a few issues with breadcrumbs:
1. Removes slashes from the click target for breadcrumb links
2. Allows breadcrumb links to be created for nested parameterized pages (was blocked by a previous fix #417)
3. Disables breadcrumb link if a folder does not contain an index file (rather than previous version which checked if the specific path existed in the menu)

Breadcrumb fix

---

.changeset/strong-mugs-prove.md
sites/example-project/src/components/modules/echarts.js

I was playing around and found an issue related to chart layout when performing client side navigation
https://user-images.githubusercontent.com/14029371/199779439-3b1c19a1-0d19-408e-980d-275415adebd1.mov
I'm new using echarts so not sure if this would be the most idiomatic solution to this problem. Happy to hear your thoughts

Update chart size on render finished

---

.changeset/long-geese-destroy.md
packages/sqlite/package.json
pnpm-lock.yaml

sqlite3 has just started releasing pre-built binaries for `arm64`. 
This should significantly speed up the install for machines running `arm64` (ie Mac Silicon)

bump sqlite3

---

.changeset/wild-rings-unite.md
sites/example-project/src/pages/__layout.svelte

This addresses the bug described in #410. 
It specifically addresses:
> **Expected Behaviour**
> - Not show is sidebar
For manual testing I added `[something].md` at root, along with `anotherthing.md` and verified that `[something]` does *not* show in the sidebar, but `anotherthing.md` does.
This does **not** address:
> - possibly crawl links in pages to determine which parameterized pages should be show in sidebar.
If anyone could elaborate on what the "crawl" functionality looks like maybe the PR can be expanded.

fix: hide root level parameterized pages in sidebar

---

package.json
pnpm-lock.yaml

This adds a postinstall script to the monorepo
This means when you run `pnpm install` on a clean install of the monorepo, all required scripts should be run.
This also means when working in `test-env`, you should be able to `pnpm install` to update any changes to components needed.

pnpm postinstall script 

---

.changeset/weak-geckos-wait.md
packages/db-commons/index.cjs
sites/example-project/src/pages/database-specific/sqlite-dates.md

Currently, our date type inference logic determines dates as follows:
1. For any string columns, check if the data contains one `-`. If so, assume it is a date
2. If the value does not contain a timestamp, append a timestamp of `T00:00`
3. Run the new value through a check to see if it should be considered a date (attempt to run `new Date` then parse the result)
This works in most cases because databases have consistent formatting of date and datetime types. The only database that can cause issues here is SQLite, since there is no date type.
We found an example that causes this logic to break down:
- Column containing months in the format `YYYY-MM` is included in a query
- It passes the first check based on having one `-`
- It passes through the date check and is returned as `type=date` …

Change date type inference check to ignore dates in formats other than YYYY-MM-DD

---

.changeset/purple-cherries-begin.md
sites/docs/docs/features/charts/big-value.md
sites/example-project/src/components/viz/BigValue.svelte

Resolves #494 
- Add a max-width to BigValue comparison titles
- Left align title to end of Value rather than start
Before:
After:

add max-width to BigValue titles

---

.changeset/stupid-guests-juggle.md
sites/example-project/src/components/ui/Databases/MysqlForm.svelte

This PR adds options for `port` and `ssl` to the MySQL database connector form on the Settings page. These options are a part of our MySQL connector, but I missed them when I added options to the settings form the first time. Thanks @hooopo for pointing this out.

Add port and ssl options to mysql form

---

.changeset/famous-bats-change.md
sites/example-project/src/components/modules/formatTitle.js

The `formatTitle` function currently only looks for A-Z characters when capitalizing column title names. This PR fixes the regex to allow for any characters in the column name to be recognized by the function.

Fix `formatTitle` function regex

---

.changeset/nice-ghosts-stare.md
sites/example-project/src/components/ui/BreadCrumbs.svelte
sites/example-project/src/components/ui/DownloadData.svelte
sites/example-project/src/components/ui/QueryViewer.svelte
sites/example-project/src/components/ui/QueryViewerSupport/QueryDataTable.svelte
sites/example-project/src/components/viz/DataTable.svelte
sites/example-project/src/components/viz/ECharts.svelte

Part of #489 
Most of these changes involved replacing `spans` with `button` tags and then styling them to match as they were before.
Turned into a button for a11y.
Made `downloadData` function a prop w/ default.
Hover effect for DownloadData now through CSS in the parent component.
Updated ECharts and DataTable to both use DownloadData, both should still download the appropriate files for the user.
Before (ECharts):
https://user-images.githubusercontent.com/14843458/207218051-c8f5def8-5b56-44fd-a167-e1cb6bbc8f24.mov
After (ECharts):
https://user-images.githubusercontent.com/14843458/207218250-41123c2e-6bbf-42d7-8788-9ec207235f69.mov
Before (DataTable):
https://user-images.githubusercontent.com/14843458/207218701-9dc4aa0c-457f-4cff-b783-793ea3556103.mov
After (DataTable): …

Add a11y to QueryViewer, DownloadData, BreadCrumbs, ECharts, DataTable Components

---

.changeset/fifty-mangos-sneeze.md
sites/example-project/src/components/ui/Deployment/VercelDeploy.svelte

Fix install command which previously said "build/"
After:

fix: corrected install command

---

.changeset/pretty-knives-attend.md
packages/postgres/index.cjs
sites/example-project/src/components/ui/Databases/PostgresForm.svelte

- Some users separate production and development data environments using different schemas.
- Currently, you have to specify the schema you are referencing per query. 
- This means there is no easy way to have the change the schema, would resort to a find-replace or similar
Add a config option that lets a user specify a default schema either with:
- The settings UI (suitable for dev environments)
- An env variable (suitable for production environments)
- Should add schema support for other databases in the future

Optional schema field for postgres connector

---

.changeset/famous-coins-invent.md
sites/example-project/src/components/ui/DownloadData.svelte
sites/example-project/src/components/viz/Chart.svelte
sites/example-project/src/components/viz/ECharts.svelte

Resolves #528 
Hopefully, this is what was requested.
- DownloadData now has text as prop ("Download Data", "Save Image", etc). Might be good to rename (DownloadButton)
- Data added as prop to ECharts component
- Echarts now has download option for Chart PNG and CSV data
Before:
After:
https://user-images.githubusercontent.com/14843458/207746387-3914617d-e623-474d-91bd-a65443d3fd4f.mp4

add separate download data option to charts

---

.changeset/tiny-grapes-appear.md
sites/docs/docs/features/charts/area-chart.md
sites/docs/docs/features/charts/bar-chart.md
sites/docs/docs/features/charts/line-chart.md
sites/example-project/src/components/viz/Chart.svelte

Mutiple users found the automatic sorting behaviour confusing.
This removes sort by default behaviour for Chart components (AreaChart, BarChart, LineChart)
Sort will now be determined by the data order in the query.
(This does not affect date / time based axes, which will still be sorted chronologically)

Turn off chart sort by default

---

.changeset/thin-files-add.md
pnpm-lock.yaml
sites/example-project/src/app.css
sites/example-project/src/components/ui/Databases/DatabaseSettingsPanel.svelte
sites/example-project/src/components/ui/Deployment/DeploySettingsPanel.svelte
sites/example-project/src/components/ui/Deployment/NetlifyDeploy.svelte
sites/example-project/src/components/ui/Deployment/OtherDeploy.svelte
sites/example-project/src/components/ui/Deployment/VercelDeploy.svelte
sites/example-project/src/components/ui/Formatting/CollapsibleTableSection.svelte
sites/example-project/src/components/ui/Formatting/CustomFormatsSection.svelte
sites/example-project/src/components/ui/Formatting/FormattingSettingsPanel.svelte
sites/example-project/src/components/ui/Sidebar.svelte
sites/example-project/src/components/ui/TelemetryOptOut/TelemetrySettingsPanel.svelte
sites/example-project/src/components/ui/VersionControl/VersionControlPanel.svelte
sites/example-project/src/components/viz/BigValue.svelte
sites/example-project/src/pages/text-and-metrics/markdown.md
sites/example-project/src/pages/text-and-metrics/text.md
sites/example-project/src/pages/text-and-metrics/value-component.md

- We've had feedback that there isn't enough distinction between some of our H1 - H6 styles. 
- H3 and below are not very useful as they are not very visualy distinct from `<p>` text size wise.
- Sub-lists contain gaps after final bullet that breaks list flow
This contains some **reasonably major stylistic updates** to the default styling of Evidence projects:
- **More visual contrast between H1 - H6 using sizes**: This brings Evidence in line with [more typical web standards](https://html.spec.whatwg.org/multipage/rendering.html#sections-and-headings) for reading
- Removing margin after sub-lists
- Adding slight margin separating list items
- This will change how H1 tags should be used. It will now probably not be suitable to use aside from the top of a page. (and instead use H2s) Does …

Improving Visual Hierarchy

---

.changeset/orange-cameras-smile.md
sites/example-project/src/components/viz/Chart.svelte

This PR adds a patch fix to 100% stacked charts to avoid them erroring out on changes to the data object or page.
Here is the rough approach to building 100% stacked charts:
- In Chart.svelte, we receive the y column(s) as inputted by the user (e.g., `sales`)
- The total of the y column is calculated
- Each y column value is divided by the y column total to get the percentage for use in the stack
- Once the stacked percentages are calculated, the y variable name is overwritten as `y + "_pct"` (e.g., `sales_pct`)
The problem appears when the chart re-runs reactively (either from a change to the `data` object or to the page):
- Chart.svelte's script tag re-runs, but the `y` variable has not been reset to the original name supplied by the user (e.g., it still shows up as `sales_pct`)
- …

Patch fix for 100% stacked charts

---

.changeset/gorgeous-geese-stare.md
sites/example-project/src/components/viz/DataTable.svelte

DataTable had a reactivity issue where the error state would persist even after the data object changed. This PR adds a fix so when the data is updated, the error state is reset to undefined.

Fix datatable error reactivity

---

.changeset/odd-snails-deliver.md
sites/example-project/src/components/modules/getCompletedData.js
sites/example-project/src/components/modules/getSeriesConfig.js

This PR fixes 2 issues regarding nulls in charts:
1. Fixes #541 - null series previously did not appear in the chart legend
2. Null values shifting across the x axis in some scenarios - this only happened when a series entry was missing in the dataset
The second issue was caused by our series completion function - the function was completing the dataset with undefined values rather than nulls, which led the chart to ignore those rows in the dataset when calculating the position of rectangles in the chart area.
Below is a before and after on that issue:

Fix treatment of nulls in charts

---

.changeset/tricky-goats-suffer.md
sites/example-project/src/pages/__layout.svelte

Shading / blurring at top of page in export

fix: remove header bar from printed content

---

.changeset/heavy-pillows-know.md
sites/example-project/src/components/ui/Databases/DatabaseSettingsPanel.svelte
sites/example-project/src/components/ui/Formatting/FormattingSettingsPanel.svelte

Fix minor spacing in settings

---

.changeset/sharp-melons-love.md
sites/example-project/src/app.css

When the new DataTable was released last week, it turned off the default styling for images inside of tables. It also inadvertently turned off default image styling across the project. This PR returns the default image styling to the project and removes it only for images within a table cell.
Fixes #578

Fix scoping of img styling in tables

---

.changeset/popular-cameras-carry.md
sites/example-project/src/components/ui/Hamburger.svelte
sites/example-project/src/pages/__layout.svelte

The sidebar was overflowing over the hamburger menu button. I was able to fix it by dividing the `header-bar` into two entities.
**Note:** I didn't want to change the structure of the `menu/nav` as I am new to the project. I went for mainly `css` change.

Fix the menu button disappearing in the sidebar

---

.changeset/many-cobras-warn.md
sites/example-project/src/components/modules/echarts.js
sites/example-project/src/components/modules/echartsCanvasDownload.js
sites/example-project/src/components/modules/echartsCopy.js

Previously, we were importing the full echarts library wherever it was used in the project, even though we only use 2 functions each time we import it. This PR reduces the imports to only the required functions. Thanks @Winterhart for the suggestion!

Reduce imports from echarts library

---

.changeset/stupid-papayas-jam.md
sites/example-project/src/components/viz/DataTable.svelte

Adding error if `<Column />` `id` is not found in the table or if it doesn't contain any `id`. 
- The `error` is also sent to the `console` in `dev` mode 
- The `error` will fail the build in `strict` mode.

Add more error handling in DataTable

---

.changeset/smart-adults-think.md
packages/preprocess/index.cjs
sites/example-project/src/components/diagrams/VennDiagram.svelte
sites/example-project/src/pages/text-and-metrics/diagrams.md

This implements a simple Venn Diagram per a customer request. 
This is sufficient for their use case, but it is not ready for prime-time. Propose we leave this undocumented, and open an issue for a broader diagrams suite in the future. 
* Does not offer robust data handling. Overlap percentages, labels, and amounts are supplied directly through props which accept arrays. Live data would be supplied using `query[row].column` syntax. 
* No automatic calculation of overlap percentages. There are a variety of approaches to calculating these, and we're not enforcing any one. For example, sets expressed as a percentage of a total records, sets expressed as a percentage of a single category of records etc.  
* No format handling -- default percentages for overlaps, en-gb for record counts. 
``` …
```

minimal venn diagram implementation

---

.changeset/wise-hounds-watch.md
packages/mysql/index.cjs

The current mysql connection for evidence is not working, even if the ssl option is not set. This is because 'true' is not a valid option for mysql2, as seen in this example: https://github.com/sidorares/node-mysql2/tree/07a429d9765dcbb24af4264654e973847236e0de/examples/ssl
This PR addresses the following issues:
* Users can set ssl to `true`
* Users can set ssl to `Amazon RDS`
* Users can set ssl to `JSON` string in order to handle more complex situations, such as https://mariadb.com/kb/en/nodejs-connection-options/#two-way-ssl-authentication
More information can be found here: https://github.com/evidence-dev/evidence/pull/518#issuecomment-1399571132

Fix mysql ssl option

---

.changeset/blue-tables-prove.md
sites/example-project/src/components/modules/echartsMap.js
sites/example-project/src/components/viz/EChartsMap.svelte
sites/example-project/src/components/viz/USMap.svelte
sites/example-project/src/pages/states/[state].md
sites/example-project/src/pages/states/index.md

Adds a `link` property to the USMap component, which lets you pass a column of links to the map. When you click on each state, it takes you to the link provided:

Add map links

---

.changeset/long-rocks-care.md
sites/example-project/src/components/ui/QueryViewerSupport/QueryDataTable.svelte
sites/example-project/src/components/viz/DataTable.svelte

Value formatting in DataTable was missing the "units" portion of our formatting system (e.g., summarizing numbers to "k", "M", etc.). This PR adds that feature back in.

Fix value formatting in datatable

---

.changeset/rotten-frogs-knock.md
sites/docs/docs/features/data-table.md
sites/example-project/src/components/viz/DataTable.svelte
sites/example-project/src/components/viz/SearchBar.svelte

Fixes the following in DataTable:
- Enables `downloadable` option to turn on/off download button
- Fixes download button not appearing on non-paginated tables
- Cleans up spacing below the table
- Documents the `rows=all` feature

fix datatable download button and spacing

---

.changeset/violet-squids-protect.md
.github/workflows/prerelease.yml
package.json

We will `pre-release` on merge with `main` allowing to test, before major release. On `npm` registry the tag `next` will be `sync` with the latest changes on `main`

Add Prerelease Github Action

---

.changeset/hip-deers-look.md
packages/csv/.gitignore
packages/csv/index.cjs
packages/csv/package.json
packages/csv/test/test.js
packages/db-orchestrator/package.json
packages/evidence/cli.js
pnpm-lock.yaml
sites/example-project/src/components/ui/Databases/CSVForm.svelte
sites/example-project/src/components/ui/Databases/DatabaseSettingsPanel.svelte
sites/example-project/src/pages/api/settings.json.js
sites/example-project/src/pages/test.md
sources/csv_test.csv

- We already support CSV file querying through our DuckDB connector, but there are a few drawbacks for someone who wants to use only CSVs:
- They need to include an empty DuckDB file along with their CSVs
- The path to the file is not intuitive + it's not clear where to store the CSV files 
- This PR adds a new connector for CSVs, which uses DuckDB under the hood
- When the CSV connector is selected, it spins up an in-memory DuckDB instance and uses that to query the CSV files in the project
- This PR also includes a new `sources` directory, which will be the recommended place to store CSV files. E.g., 
```sql
select * from 'sources/myfile.csv'
```

CSV Support

---

.changeset/eighty-buckets-jam.md
sites/example-project/src/components/ui/BreadCrumbs.svelte

Fix breadcrumb capitalization

---

.changeset/early-cooks-greet.md
.changeset/six-steaks-attack.md
sites/example-project/src/components/ui/Databases/GenericForm.svelte
sites/example-project/src/components/ui/Databases/InfoIcon.svelte
sites/example-project/src/components/ui/Databases/SnowflakeForm.svelte

Resolves #655 
Gives users clear understanding of the format of snowflake account number to be entered.

Clarify Snowflake account number formats

---

.github/workflows/tests.yml

@ItsMeBrianD this will mean your tests run without approval

Add Brian to test auto-run list

---

.changeset/lazy-bulldogs-dream.md
packages/preprocess/index.cjs
sites/example-project/src/components/ui/Tabs/Tab.svelte
sites/example-project/src/components/ui/Tabs/Tabs.svelte
sites/example-project/src/pages/ui-components/tabs/+page.md

This adds a tabs component; with an interface that looks like this:
```html
<Tabs id="my-tabs">
<Tab label="Tab 1">
This is the content of Tab 1
</Tab>
<Tab label="Tab 2">
This is the content of Tab 2
</Tab>
</Tabs>
```
This is the result of that example:
https://user-images.githubusercontent.com/10779616/226673033-25137495-8fa3-4c22-92bc-1c3a8d2780c3.mp4
The `id` prop on the `Tabs` component is optional; but when provided, the tab state is persisted in the URL via Query Parameters, which means links can be sent that indicate which tab should be upon load.
This probably needs a design pass; I loosely based this off the tabs shown [in the documentation](https://docs.evidence.dev/getting-started/install-evidence)
**This is not yet ready for merge**; just posting to get design feedback and …

Add Tabs Component

---

.changeset/tasty-dodos-speak.md
sites/example-project/src/components/ui/QueryViewer.svelte

- Remove `QueryViewer` UI regression on windows machine

Fix query viewer still visible on windows (OS)

---

.changeset/pink-stingrays-behave.md
sites/example-project/src/components/ui/QueryViewerSupport/QueryDataTable.svelte

Fix horizontal table scroll bug

---

.changeset/flat-impalas-rule.md
sites/example-project/src/components/viz/FunnelChart.svelte
sites/example-project/src/pages/charts/funnel-chart/+page.md

Fixes #786 
Funnel chart spacing was working for charts with titles and subtitles, but didn't account for charts without those. This PR adds logic to handle the various combinations of title, subtitle, and legend to include appropriate spacing at the top of the chart.

Fix funnel chart spacing

---

.changeset/dull-lemons-notice.md
packages/bigquery/index.cjs
packages/bigquery/test/test.js

It seems that the BigQuery driver is returning special objects when the values corresponding to it's type is *potentially* too wide to fit in a JS number. 
This is a more general issue on Evidence and we should find a generalized approach for all DB drivers (e.g BIGINT types in Postgres)  More details here:  https://github.com/evidence-dev/evidence/issues/792
The fix here is a work around for how it specifically fails in BigQuery.  I suspect this was a regression introduced by the BigQuery driver updated from a month ago 1124bb52c8879bfcf8a052f02002ea190db5c35b
In BigQueries case, this blew up when we were standardizing row results
```
{
"rows":[
{
"numeric_number":"1.23456789",
"float64_number":1.23456789,
"decimal_number":"1.23456789",
"string_number":"1.23456789"
},
{ …
```

issue-700 Workaround for handing values from numeric columns that are not returned as JS 64 bit number

---

sites/docs/docs/core-concepts/data-sources/index.md

This PR is to add some details to the data source documentation with regards to SSL and PostgreSQL.
It should partially help with #796, although additional UI fields to allow declaring a certificate file without needing to use a connection string will be even better.

Add documentation details for Postgres SSL connections

---

sites/docs/docs/components/custom-components.md

This PR extends the custom components documentation by adding a simple example for how to "override" an existing component to better suit ones needs. It wasn't immediately clear to me how I might adapt the sidebar to use a different project title, since the documentation seems focussed on adding new components and it wasn't obvious to me that adapting existing components is functionally identical.
A big thank you to the Evidence team for getting me pointed in the right direction on doing what I wanted, and I hope that this addition to the docs will help others as well.
(I don't believe these checklist items apply since I am updating documentation only - I'll be happy to adapt if needed).

Add instructions for adapting UI components

---

.changeset/mean-baboons-punch.md
sites/example-project/src/components/ui/DownloadData.svelte

Make download buttons non-copyable

---

.changeset/fresh-coats-lick.md
packages/preprocess/src/process-queries.cjs
sites/docs/docs/core-concepts/formatting/index.md
sites/example-project/src/components/modules/formatting.js
sites/example-project/src/pages/expressions/+page.md

- Sometimes it’s not possible to use our components
- For example, if you want to do a subtraction in js, it will display raw js floating point
- `Sales are up {orders[0].sales_usd - orders[1].sales_usd} from last month.`
- It stops you doing difficult stuff in SQL just to get the format right
- Common occurrence is lag functions and annoying division
```orders_by_month
select
date,
count(*) as num_orders,
lag(count(*),1) as num_orders_last_month,
count(*) / lag(count(*),1) -1 as num_orders_change_pct
from orders
```
- It means making a custom component is much easier
- You call the format function
- Allows users to call the function like this`{fmt(value, excelFormatCode)}`, eg `{fmt(orders[0].sales, '$##0')}`
- It works for numbers, percentages, currencies
- It _does not_ work for dates …

Expose format function

---

.github/pull_request_template.md
.github/workflows/tests.yml
.github/workflows/ui-tests.yml

This reverts commit facd101a919317daf88792ac83a7b9f97fd21253.
This doesn't work: branch protection rules prevent the ignore syntax working
See #860 for detail.
Additionally, pull_request_target is needed for access to secrets

Revert "tests: only run on code changes"

---

.changeset/afraid-planets-sip.md
sites/example-project/src/components/icons/HelpCircleIcon.svelte
sites/example-project/src/components/viz/Value.svelte

Addressing #788
Value component error icon is white and positioned in the center.
Before: 
After:

Value component error icon

---

sites/docs/docs/core-concepts/data-sources/index.md

Change anchor reference from #local-data-files to #csv-and-parquet-files as needed to make the link work on the published website.
i.e. https://docs.evidence.dev/core-concepts/data-sources/#csv-and-parquet-files
- [ X ] For UI or styling changes, I have added a screenshot or gif showing before & after
- [  ] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

docs/data-sources: fix link to local-data-files

---

.changeset/moody-toys-sit.md
.github/ISSUE_TEMPLATE/bug_report.md
packages/evidence/cli.js

See #898 
Add the `env` setup in the new `sade` CLI setup.

Make build:strict windows compatible

---

.changeset/fresh-news-refuse.md
packages/duckdb/package.json
pnpm-lock.yaml

Fixes #885 
Adds support for the latest version of DuckDB. Also removes support for older versions. The error message for older database versions is fairly descriptive on how to upgrade (and users of pre-1.0 libraries should be aware of upgrading anyways), so I don't think anything else should be necessary.

version bump duckdb to 0.8.0

---

sites/example-project/tailwind.config.cjs

Instead of looking in `<project>/node_modules/@evidence-dev/...`, example-project was looking in `<project>/.evidence/template/node_modules/@evidence-dev/...` for components

fixed tailwind exploration path

---

.changeset/eleven-drinks-share.md
.npmrc
package.json
packages/evidence/package.json
pnpm-lock.yaml
sites/test-env/package.json

Removes accidental `.npmrc` commit, adds `@evidence-dev/plugin-connector` in with `@evidence-dev/preprocess`

moved plugin-connector dependency, deleted .npmrc

---

.changeset/mean-swans-impress.md
packages/core-components/src/lib/unsorted/viz/Area.svelte
packages/core-components/src/lib/unsorted/viz/AreaChart.svelte
sites/docs/docs/components/area-chart.md
sites/example-project/src/pages/charts/area-chart/+page.md

Added `lineColor` prop to `AreaChart.svelte` file. Also doc for AreaChart has been updated

Line colour for area chart. Addresses issue #923

---

.changeset/ten-melons-complain.md
packages/core-components/src/lib/unsorted/QueryStatus.svelte

Fixes #905 
Switches to async while loop to prevent requests building up and dumping when dev server is turned off/on

switch to async while loop vs. setInterval

---

.changeset/silly-waves-own.md
packages/plugin-connector/src/build-plugins/preprocess.js
packages/plugin-connector/src/component-resolution/get-plugin-components.js
packages/plugin-connector/types/sveltekit-autoimport/index.d.ts

Fixes #829
Enables components in the components folder to be automatically imported
Message when conflict is detected:
> [!] The components folder and {package} both provide {component}. The component from the components folder will be used. To use the component from {package}, specify an alias (https://docs.evidence.dev/plugins/using-plugins/#component-aliases) or explicitly import the component.

integrate components folder as a plugin

---

.changeset/old-shoes-marry.md
sites/example-project/tailwind.config.cjs

Fixes #944 
Tailwind was breaking HMR because it was looking outside of vite's project directory(?), so removing these two lines makes it stay in it's place. The lines are redundant because all the contents of `/pages` and `/components` are copied to `.evidence/template/src` anyways, so Tailwind can parse them regardless.

removed redundant tailwind config lines that broke HMR

---

.changeset/seven-paws-switch.md
packages/evidence/scripts/build-template.js

Removes the contents of `sources` during template build

Empty sources folder after copying to template

---

.changeset/chatty-tomatoes-laugh.md
packages/core-components/src/lib/unsorted/ui/DownloadData.svelte

Converts date values to ISO strings before exporting to CSV
Does it by running it through `JSON.parse(JSON.stringify(data))` (which calls `.toISOString()` on the dates) to avoid modifying the original data

Standardize dates to ISO string during CSV export

---

.changeset/smooth-dolls-smile.md
packages/core-components/src/lib/unsorted/viz/Bar.svelte
packages/core-components/src/lib/unsorted/viz/ReferenceArea.svelte

Due to a change introduced with ReferenceArea, grouped bar charts were being overridden and changed to stacked bar charts. This PR fixes that issue.

Fix for grouped bar charts

---

.changeset/warm-crews-sparkle.md
packages/preprocess/index.cjs
packages/preprocess/package.json
packages/preprocess/src/add-classes.cjs
pnpm-lock.yaml

Allows for styling targeting markdown generated tags. `rehype-add-classes` was misconfigured(?) so the functionality was just put in `src/add-classes.cjs`
*edit* resolves #919

Enable classes to be added to markdown-generated tags

---

packages/evidence/package.json
packages/universal-sql/package.json
packages/universal-sql/src/client-duckdb/browser.d.ts
packages/universal-sql/src/client-duckdb/browser.js
packages/universal-sql/src/client-duckdb/node.d.ts
packages/universal-sql/src/client-duckdb/node.js
pnpm-lock.yaml
sites/example-project/package.json
sites/example-project/src/pages/+layout.js

Stops linting test from failing because it can't find `apache-arrow`

shove all `duckdb-wasm` deps into `universal-sql`

---

packages/evidence/package.json
pnpm-lock.yaml

@ItsMeBrianD 
I think this was missing from #984, and is causing the [prerelease to fail](https://github.com/evidence-dev/evidence/actions/runs/5405240311) when attempting to build the template in packages/evidence.

include tailwind config in cli dev deps

---

.changeset/little-baboons-hear.md
packages/preprocess/src/frontmatter/process-frontmatter.cjs

Fixes #963 
remove export from mdsvex-generated `export const metadata` because it makes tailwind break HMR

Fix frontmatter HMR

---

.changeset/heavy-tables-call.md
packages/core-components/src/lib/unsorted/ui/Details.svelte
sites/docs/docs/components/details.md

- Moves from semantic HTML to div which addresses issues with any content which is `onMount`-ed / rendered in the browser
- Adds slide transition on expand
- Adds `open` prop that allows you to have it expanded (off by default)

Update Details component styling and props

---

.changeset/tasty-suns-sleep.md
packages/core-components/src/lib/unsorted/viz/SankeyChart.svelte

Sets animation duration for sankey chart to 500ms to match other charts for #1090 
|      Before      |      After      |
| :---------------------: | :---------------------: |
| ![before-sankey](https://github.com/evidence-dev/evidence/assets/129554482/1ac31b2e-c6ea-470c-bd8d-5103bd6e9e38) |![after-sankey](https://github.com/evidence-dev/evidence/assets/129554482/c3bc505d-48d5-4420-a497-9d75f4eb7134) |

sets animation duration to 500ms for sankey chart - #1090

---

.changeset/kind-glasses-exist.md
packages/component-utilities/src/dateParsing.js
sites/example-project/src/pages/+layout.js

Slices the time zone off `Date` ISO string representations to let browser adapt to local timezone

Normalize dates from ddb

---

.changeset/large-zoos-hug.md
packages/plugin-connector/src/data-sources/exec-source.js
packages/plugin-connector/src/data-sources/get-sources.js

Prior to this change; all queries for a source were executed, then they were all flushed to files.
This meant that all the results for a single source needed to fit into memory at once.
This change runs a single query at a time, and then saves it to a file before moving on - meaning it can be garbage collected.

[next] Execute query and save to file in one step

---

.changeset/friendly-news-dress.md
sites/example-project/src/pages/api/status/[...route]/extractQueries.server.js

previously, a conditional in `extractQueries.server.js` would do two things when a `+page.md` is empty:
- return `[{}]`, causing `QueryToast.svelte` to try to read properties off the `{}`, causing a broken toast notification
- skip `updateDirectoriesandStatus`, which would normally update `.evidence-dev/queries/extracted/<hash>/queries.json` to have the proper extracted queries, which ends up making old queries stay on the page in evidence's eyes

remove broken conditional in `extractQueries.server.js`

---

.changeset/popular-geese-leave.md
packages/component-utilities/src/dateParsing.js
packages/component-utilities/src/formatting.js
packages/universal-sql/src/client-duckdb/browser.js
sites/test-env/pages/date-formatting-and-performance.md

Moves `Date` object standardization to `formatValue` instead of `standardizeDateString`.
Worth considering removing `convertColumnToDate` in favour of doing all standardization on-demand in `formatValue` to speed up component initialization and improving perf for large datasets

Speed up date handling

---

.changeset/chatty-jobs-kneel.md
packages/core-components/src/lib/unsorted/ui/Databases/DatabaseSettingsPanel.svelte

Adds a note to the db connection panel for users who are starting with the demo database. 
In most scenarios, new projects get db credentials auto-added, but there are 2 situations where this doesn't happen:
1. "Use This Template" button in the template repo on Github
2. Creating a new template project from Evidence Cloud
The best way to start editing these projects locally is to clone the repos, but that means the db connection won't automatically be set up.
A few alternatives I considered:
- Add a command to our VS Code extension to "Add demo database credentials", which would create an `evidence.settings.json` file
- Add a button to the db connection settings panel to "Use demo database", which would fill out the form with the information
- Add an entry to our db dropdown for "demo …

Add note to db connection panel

---

.changeset/pink-masks-type.md
packages/core-components/src/lib/unsorted/viz/ReferenceArea.svelte
packages/core-components/src/lib/unsorted/viz/ReferenceLine.svelte
sites/example-project/src/pages/charts/annotations/+page.md

Adds identifier to `ReferenceLine` and `ReferenceArea` series to prevent them from breaking with reactive values

Prevent duplicate reference lines

---

.changeset/breezy-hounds-crash.md
.changeset/real-moose-happen.md
packages/evidence/cli.js
packages/plugin-connector/src/data-sources/get-sources.js
packages/plugin-connector/src/data-sources/index.js
packages/plugin-connector/src/data-sources/schemas/datasource-spec.schema.js

Also removes references to sources/queries that no longer exist
- Should we be attempting to remove parquet as well if sources or queries are found to be removed?
- Should we be attempting to remove queries who's parquet is found to be removed (basically just `queries.filter(x => fs.exists(x))`)?

Don't fully overwrite manifest.json on filtered builds

---

.changeset/hot-ravens-roll.md
packages/core-components/src/lib/unsorted/viz/BarChart.svelte
sites/test-env/pages/test-charts.md

Prevents the `BarChart` from locking the entire page

chore: fix bar chart

---

.changeset/slow-actors-march.md
.eslintignore
packages/evidence/scripts/build-template.js
packages/evidence/scripts/svelte.config.js
sites/test-env/svelte.config.js

An evidence project can now have a `svelte.config.js` file at the root of the project that will be merged _over_ Evidence's own configuration. Certain fields that are required for Evidence and it's components to function properly are ignored.
- Preprocessors form the basis of Evidence, users should not mess with them (yet)
- File locations are hard-coded into the CLI; changing them will completely break the app
- Extensions are also hard-coded in many places, and changing them will likely break everything.
Resolves #1182

feat: enable custom sveltekit configs

---

packages/postgres/index.cjs
sites/docs/docs/cli/index.md

fixes #1199
I feel like there is probably a more elegant way where we could put the env maps into the redshift connector directly, but I dont really understand cjs and therefore how to achieve this

Add redshift env vars to PG connector

---

.changeset/lovely-dolls-shop.md
packages/core-components/src/lib/unsorted/ui/Databases/DatabaseSettingsPanel.svelte
packages/core-components/src/lib/unsorted/ui/Databases/TrinoForm.svelte
packages/core-components/src/lib/unsorted/ui/Databases/index.js
packages/db-orchestrator/package.json
packages/trino/.gitignore
packages/trino/index.cjs
packages/trino/package.json
packages/trino/test/test.js
pnpm-lock.yaml
sites/docs/docs/cli/index.md
sites/docs/docs/core-concepts/data-sources/index.md

This PR adds a data source for [Trino](https://trino.io/)/[Presto](https://prestodb.io/).
Resolves #1095.
Adding Trino/Presto significantly increases the number of data sources supported by Evidence, as they function as data source aggregators.

Add a data source for Trino/Presto

---

.changeset/poor-carpets-sneeze.md
packages/component-utilities/src/inferColumnTypes.js
packages/core-components/src/lib/unsorted/viz/Chart.svelte
packages/core-components/src/lib/unsorted/viz/DataTable.svelte
packages/query-store/src/QueryStore.ts
packages/query-store/src/types.ts
packages/query-store/src/utils/handleMaybePromise.ts
pnpm-lock.yaml

When QueryStores encounter an error running (any) query they enter an error state; because the queries are immutable, the query store basically locks up and does nothing, when a new query string is provided, a new query store is created, which causes the page to start executing again.
This can most easily be tested using the Query console in the `test-env` project

Universal SQL: QueryStores keep error state

---

.changeset/mighty-tomatoes-promise.md
packages/plugin-connector/src/data-sources/get-sources.js
packages/plugin-connector/src/data-sources/get-sources.spec.js
pnpm-lock.yaml

Previously source option environment variables were structured as `EVIDENCE_SOURCE_[source name]_[option]` and for nested options, `EVIDENCE_SOURCE_[source name]_[object]_[option]`. This caused issues when an option included an `_` (a common case for multi-word variable names.
This PR changes these variables to be delimited with `__`,  a much less common appearance:
`EVIDENCE_SOURCE__[source name]__[object]__[option]`;
Resolves #1174

Universal SQL: Change Environment variable delimiter `_` to `__`

---

.changeset/thin-pens-care.md
packages/core-components/src/lib/unsorted/viz/DataTable.svelte
sites/test-env/pages/null-datatable.md

Use `-` instead of `{column.linkLabel}` for nullish linkLabel values

---

.changeset/good-papayas-relate.md
packages/core-components/src/lib/unsorted/ui/Deployment/DeploySettingsPanel.svelte
packages/core-components/src/lib/unsorted/ui/Deployment/EnvironmentVarListing.svelte
packages/core-components/src/lib/unsorted/ui/Deployment/NetlifyDeploy.svelte
packages/core-components/src/lib/unsorted/ui/Deployment/OtherDeploy.svelte
packages/core-components/src/lib/unsorted/ui/Deployment/VercelDeploy.svelte
packages/plugin-connector/src/data-sources/build-connector.js
packages/plugin-connector/src/data-sources/index.js
pnpm-lock.yaml
sites/example-project/src/pages/settings/+page.js
sites/example-project/src/pages/settings/+page.server.js
sites/example-project/src/pages/settings/+page.svelte

This converts the deployment panel to use the environment variable structure of usql, rather than the predefined variables that were there previously.
This is dynamic, based on what is provided to the datasource, (e.g. in the user's own environment, `connection.options.yaml`, and `connections.yaml`), so while it may not be 100% correct _all the time_, it will exactly match the user's local environment.
Once we complete #1186 this will not be as much of an issue; as the UI for configuration _will_ use options defined by the sources themselves.
As a potential addition to this PR, we may want to consider a "copy all" button, or file an issue for having on in the future; as copy-pasting for more than one or two connectors would probably be long and tedious.

Universal SQL: Deployment menu uses new environment variables

---

.changeset/nervous-keys-yell.md
packages/core-components/src/lib/unsorted/ui/QueryToast.svelte
packages/core-components/src/lib/unsorted/viz/EchartsCopyTarget.svelte

Noticed that charts in Chrome are getting cut off when I try to export to PDF.
@mcrascal you might already know what's going on here - let me know what you think
But the same issue doesn't happen in Safari:
I think there are 2 options here, but I don't totally understand why some things are working and others aren't, so maybe there are better ways:
I took a look at the print width which was set to `645px` and adjusted it until it would fit on my page in Chrome. `606px` was the max I could do without it overflowing the margins of the page.
This works for bringing the charts onto the page fully, but it causes the spacing above/below the charts to be bigger than it appears on the webpage, which isn't great.

Adjust chart print width to fix Chrome print issue

---

.changeset/clean-dancers-love.md
packages/core-components/src/lib/unsorted/ui/Deployment/EvidenceDeploy.svelte
packages/core-components/src/lib/unsorted/ui/Formatting/FormattingSettingsPanel.svelte
packages/core-components/src/lib/unsorted/ui/Header.svelte

Opens settings links in same browser so they work in VS Code's simple browser.

Fix links for vscode browser

---

.changeset/cuddly-dancers-collect.md
packages/core-components/src/lib/unsorted/viz/Area.svelte
packages/core-components/src/lib/unsorted/viz/Bar.svelte
packages/core-components/src/lib/unsorted/viz/Bubble.svelte
packages/core-components/src/lib/unsorted/viz/Line.svelte
packages/core-components/src/lib/unsorted/viz/ReferenceArea.svelte
packages/core-components/src/lib/unsorted/viz/Scatter.svelte

Secondary y-axis PR introduced a secondary axis that is included in all XY charts and hidden by default. Any axis overrides were updated to reference the correct axis (`[0]` for the primary axis and `[1]` for secondary). I had forgotten that the hidden secondary axis is only included in charts where `swapXY=false`, so anything that was referencing `yAxis[0]` in a `swapXY=true` chart was causing issues. This PR fixes the referencing of the yAxis from swapXY charts.

Fix axis overrides for multiple y axes

---

sites/docs/docs/core-concepts/data-sources/index.md

Documentation update: in the Snowflake section of Data Sources, add a note that all column names will be converted to lowercase in Evidence.  This is significant because Snowflake has the (weird) convention of all table and column names being being uppercase.
It looks like this was design choice made when the Snowflake connector was written, with a comment saying that an issue should be opened to consider this further:
https://github.com/evidence-dev/evidence/blob/cafd4b1f6002a25873949c6c1b62cb72cc4eacd7/packages/snowflake/index.cjs#L158C5-L158C5

Docs: note that Snowflake columns will be lowercase

---

.changeset/curly-foxes-battle.md
sites/example-project/src/pages/+layout.js
sites/example-project/src/pages/templated-pages/[category]/[item]/+page.md

This prevents queries from executing twice when pages load in development.

Fix multiple queries running on server start

---

.changeset/yellow-cows-perform.md
packages/evidence/scripts/build-template.js

Adds dependencies that vite can't find (plugin-connector inserted `@evidence-dev/core-components` imports, imports added in preprocess)

Fix hard refresh on initial project boot

---

.changeset/chatty-pugs-sleep.md
packages/component-utilities/src/echartsThemes.js

On some operating systems, the font shown in charts is inconsistent with the UI font. This PR explicitly sets the font family within the echarts theme so the font is more consistent across operating systems.
In the future, we should consider changing the font family from `sans-serif` to `inter`, but on trying it here I noticed spacing issues that would need to be worked out.
This also slightly darkens the default chart title and subtitle colour to fit better with the new project styling:
Still might be a touch too light, but we can start here

Explicitly set font family for chart theme

---

.changeset/giant-lizards-help.md
packages/core-components/src/lib/unsorted/ui/LastRefreshed.svelte
packages/core-components/src/lib/unsorted/ui/index.js
sites/example-project/src/pages/ui-components/last-refreshed/+page.md

Adds `LastRefreshed` component, which shows the time since the last build took place.
Can see the full date/time by hovering over the text.
```html
<LastRefreshed/>
```
- `prefix`: allows you to set a custom prefix (e.g., "Updated" instead of the default "Last Refreshed")
```html
<LastRefreshed prefix="Updated"/>
```

Add LastRefreshed component

---

sites/docs/docs/core-concepts/data-sources/index.md

Adds docs for Cube: https://cube.dev/ which can be connected using Cube's postgres compatible SQL API

add docs for Cube

---

.changeset/dull-pandas-join.md
packages/preprocess/src/process-queries.cjs
packages/universal-sql/src/index.d.ts
pnpm-lock.yaml

Wraps the debounced update function to assure svelte knows it is dependent on query text being defined

Fix regression in next

---

.changeset/happy-games-wink.md
packages/postgres/index.cjs

Hi, this PR if merged would close #1358 by adding `options` to the postgres settings options.
I did a bit of manual testing, and could see the option pass though certainly happy to update to make things robust.
This is what the UI looks like with the new field.
Thanks!

feat: add option param for postgres pool

---

.changeset/fast-cars-end.md
packages/plugin-connector/src/data-sources/get-sources.js
packages/plugin-connector/src/data-sources/update-datasource-options.js
packages/plugin-connector/src/lib/b64-deep.js

- `connection.options.yaml` now has values b64 encoded
- Options where `children` is not exhaustive no longer break

Universal SQL: Fixes to options handling

---

.changeset/smooth-hairs-explode.md
packages/core-components/src/lib/unsorted/viz/DataTable.svelte
packages/universal-sql/src/client-duckdb/node.js
sites/example-project/src/pages/types/+page.md

DuckDB often returns HUGEINT types, for example as the result of summing BIGINTS. 
These were breaking when passed into charts.
This also contains an unrelated fix where fuse.io would break when encountering an invalid JS date

Hugeint fix for duckdb, Invalid dates don't break DataTables

---

.changeset/green-suns-dress.md
packages/core-components/src/lib/unsorted/ui/QueryViewer.svelte

Query viewer SQL should not be visible by default

fix QueryViewer open state

---

.changeset/fluffy-avocados-impress.md
pnpm-lock.yaml
sites/example-project/src/pages/+layout.js

Removes the sql string collecting part of the dummy page request, which wasn't really used yet, but would've been helpful for async SSR'd queries (i.e. motherduck integration, native duckdb). Worth looking at again in the future

remove dummy page sql string collection

---

.changeset/breezy-tomatoes-pretend.md
packages/bigquery/index.cjs
pnpm-lock.yaml

big bigquery queries were timing out before types were sent back

add hour long timeout to bigquery type fetching

---

.changeset/few-forks-begin.md
packages/telemetry/index.cjs

If the evidence.settings.json file is not available (which happens to be the case with out of box USQL projects), this ugly error message can show up during `npm run sources`
The file not existing has no impact on the project - so this is just noise from a user point of view

Remove redundant log message that pollutes build sources (via telemetry)

---

.changeset/good-goats-crash.md
sites/docs/docs/components/data-table.md

Updated the docs on incorporating static images in the Data Table component. 
Added a link to the section explaining how to store static images in the `static` folder.

Update docs: Explain how to add static images to the Data Table component.

---

.changeset/olive-frogs-rescue.md
packages/mssql/index.cjs
packages/trino/index.cjs

Boolean config options were returning booleans but we were comparing them to strings during parsing

fix boolean config option parsing

---

.changeset/yellow-frogs-speak.md
packages/universal-sql/src/build-parquet.js
sites/test-env/pages/nullish-bools.md
sites/test-env/sources/needful_things/nullish_bool.sql

Converts `Bool` columns to `Float64` columns if they're entirely null to bypass `apache-arrow` serialization bug

Bypass fully null bool column

---

sites/docs/docs/components/area-chart.md
sites/docs/docs/components/bar-chart.md
sites/docs/docs/components/line-chart.md

Bar, line, and area charts use `sort=true` as the default. Updating docs to reflect.

Update docs for chart sort

---

.changeset/proud-drinks-remember.md
packages/component-utilities/src/buildQuery.js

fix: buildReactiveInputQuery

---

.changeset/shaggy-ducks-unite.md
packages/core-components/src/lib/unsorted/viz/table/_DataTable.svelte

Fixes a bug in DataTable when a custom color scale is used with `colorMin` or `colorMax`.
When dividing a cell against the range of values in a column, the percentage can become higher than 100% or lower than 0% depending on how `colorMin` and `colorMax` are set. These values weren't a problem with the built-in conditional formatting colors, but the color setting used for custom color scales can't handle them.
This PR adjusts the logic so the calculations must return a number between 0 and 1.

Fix custom conditional formatting bug

---

sites/docs/docs/components/dimension-grid.md

set name to not required in docs for dimension grid

---

sites/docs/docs/core-concepts/data-sources/index.md

Fixes the location of local file databases in the docs SQLite and DuckDB

File location docs

---

.changeset/strong-eggs-pull.md
packages/plugin-connector/src/data-sources/build-sources.js
packages/plugin-connector/src/data-sources/get-sources.js

Switches to `Date.now()` in an attempt to fix #1437, as leading theory for cause is faulty caching. Post-change, parquet file paths are now immutable, so caching shouldn't be an issue.

use `Date.now()` instead of `query.hash` for file path

---

.changeset/light-poets-return.md
packages/component-utilities/src/formatting.js

If you are building a custom component in an Evidence project and you use a formatting function from `component-utilities`, there can be problems when these functions try to retrieve custom formats from the project settings.
This happened most recently to me when my custom component was loaded in an `onMount()` call and the error I received was `Function called outside component initialization`
I traced this through to the `getCustomFormats` function, which was throwing an error. Adding a try-catch solves the problem.

Add error handling to custom format retrieval

---

.changeset/gentle-berries-teach.md
packages/core-components/src/lib/molecules/sql-console/SqlConsole.svelte

Fixes `SQLConsole` crashing page on navigation, but only fixes the symptom of some greater bug that has something to do with on-page queries + transitions?
To reproduce the bigger bug:
1. Clone & run https://github.com/csjh/sqlconsole-transition-repro
2. Click on link to test
3. Click on link back to home
4. Witness error in dev console
Suspect it might be a Svelte bug, since I can't figure out anything we would be doing that would make Svelte complain

Semi-fix SQLConsole bug

---

.changeset/quick-parrots-hear.md
packages/core-components/src/lib/unsorted/viz/heatmap/_Heatmap.svelte
sites/docs/docs/components/heatmap.md

Passing a date column into Heatmap causes the chart to display blank cells. This PR adds error handling to alert the user that they should cast their dates to strings before using Heatmap

Add error handling for dates in heatmap

---

packages/core-components/package.json
packages/core-components/src/lib/organisms/layout/EvidenceDefaultLayout.svelte
packages/core-components/src/lib/organisms/layout/header/AlgoliaDocSearch.svelte
packages/core-components/src/lib/organisms/layout/header/Header.svelte
packages/core-components/src/lib/organisms/layout/header/SearchButton.css
pnpm-lock.yaml

adds an algolia option to evidence default layout, which accepts the public info for the algolia docs search bar. Adds some custom styles on the actual search button. 
+layout.svelte 
```
<script>
import '@evidence-dev/tailwind/fonts.css';
import '../app.css';
import { EvidenceDefaultLayout } from '@evidence-dev/core-components';
export let data;
</script>
<EvidenceDefaultLayout
{data}
githubRepo="/"
slackCommunity="/"
xProfile="/"
algolia={{
appId: 'KHH9ANIISC',
apiKey: 'd2bd44615d8d5f5464e54f06e82edd19',
indexName: 'docs-evidence'
}}
>
<slot slot="content" />
</EvidenceDefaultLayout>
```
yields

support for algolia docsearch

---

.changeset/lazy-boxes-brake.md
packages/component-utilities/src/getDistinctValues.js
packages/component-utilities/src/getSortedDistinctValues.js
packages/core-components/src/lib/unsorted/viz/heatmap/_Heatmap.svelte
sites/docs/docs/components/heatmap.md
sites/example-project/src/pages/charts/heatmap/+page.md

Adds x and y axis sorting ability to Heatmap.
`xSort` and `ySort`: column to sort the axis by - can be the same column or another column
`xSortOrder` and `ySortOrder`: 'asc' (default) or 'desc'
`nullsZero`: whether to treat missing/null data as zeros or not (true - default | false)
`zeroDisplay`: string to display in place of zeros ('-' is default)

Add x and y sort to heatmap

---

.changeset/calm-impalas-rescue.md
packages/core-components/src/lib/unsorted/viz/table/_DataTable.svelte

Fix table search when sorting

---

.changeset/four-olives-cheat.md
packages/evidence/scripts/svelte.config.js

Only covers the errors we want to catch and handle from the svelte vite plugin - undefined variables and empty blocks. There may be more which we can add over time. Goal of this function is to eliminate broken pages in Evidence apps during development mode.

Fix error handling in svelte.config.js

---

.changeset/fast-hornets-mate.md
packages/core-components/src/lib/atoms/inputs/dropdown/Dropdown.svelte
sites/docs/docs/components/dropdown.md
sites/example-project/src/pages/input-components/dropdown/+page.md
sites/test-env/pages/dropdown.md

This allows you to use outputs from mutli-dropdowns as DuckDB arrays.
In the case where nothing is selected, it will return an empty array
causes multiple values to be returned as a LIST type
`${inputs.category.value} → ['Cursed Sporting Goods', 'Sinister Toys']`
which means to filter a query, you need to use
`where list_contains(${inputs.category.value}, category)`
use an ARRAY type
`${inputs.category.value} → ('Cursed Sporting Goods', 'Sinister Toys')`
which means you could filter with
`where category IN ${inputs.category.value}`
which I believe is the intended behaviour

Fix: Arrays for Multiselect Dropdowns

---

.changeset/late-mails-grin.md
sites/example-project/src/pages/api/pagesManifest.json/+server.js

Stops the pages manifest from returning source code for each page, which is currently unused.

Exclude page source code from pagesManifest

---

.changeset/soft-candles-trade.md
packages/core-components/src/lib/atoms/query-load/QueryLoad.svelte
packages/core-components/src/lib/unsorted/viz/core/_BigValue.svelte
sites/test-env/pages/single-value.md

Closes #1745 
Re-enables `Value` and `BigValue`'s ability to render a single row

Fix single row `Value` and `BigValue` regressions

---

.changeset/cold-bats-smash.md
packages/ui/core-components/src/lib/atoms/inputs/button-group/ButtonGroup.svelte
packages/ui/core-components/src/lib/atoms/inputs/date-range/DateRange.svelte
packages/ui/core-components/src/lib/atoms/inputs/dropdown/Dropdown.svelte
packages/ui/core-components/src/lib/atoms/inputs/text/TextInput.svelte

Shift the margin on input components from `mx-1` to `ml-0 mr-2` so they align with the left edge of the page

Align inputs to left side of page

---

.changeset/twelve-kings-admire.md
packages/lib/query-store/src/QueryStore.ts

Fixes `initialData` being overwritten if used with interpolated query that is unresolved

No resolve unresolvable promise

---

.changeset/red-beans-cheat.md
packages/ui/core-components/src/lib/atoms/inputs/button-group/ButtonGroup.svelte
packages/ui/core-components/src/lib/atoms/inputs/button-group/ButtonGroupItem.svelte
sites/docs/docs/components/button-group.md
sites/example-project/src/pages/input-components/button-group/+page.md
sites/test-env/pages/button-range.md

Adds a `default` prop to `ButtonGroupItem` for adding a default selected button

Add default `ButtonGroup` selected item

---

.changeset/cyan-suits-fry.md
packages/ui/core-components/src/lib/unsorted/viz/core/_Chart.svelte
packages/ui/core-components/src/lib/unsorted/viz/core/_Value.svelte
packages/ui/core-components/src/lib/unsorted/viz/funnel/_FunnelChart.svelte

In Value and BigValue, when `fmt` was applied to nulls, it threw an error. This PR removes the error and passes the value through as "-"
I think we can simplify the flow for value formatting. When we set it up, the only way to format values was with format tags in column names, but now the primary method of formatting is using `fmt` props. Creating a format object gets a bit confusing when `fmt` is the method, as we need the value type for the column, which comes from `columnSummary`.
Once we fix the date/timezone issue and rip out the date parsing logic (which also requires `columnSummary`, it would be a good time to reconsider the default formatting approach inside components.

Fix format object retrieval in Chart and Value components

---

.changeset/friendly-windows-beg.md
.prettierrc
package.json
packages/lib/sdk/.prettierrc
packages/ui/core-components/package.json
packages/ui/core-components/src/lib/atoms/inputs/dropdown/Dropdown.svelte
packages/ui/core-components/src/lib/atoms/shadcn/range-calendar/range-calendar-next-button.svelte
packages/ui/core-components/src/lib/atoms/shadcn/range-calendar/range-calendar-prev-button.svelte
packages/ui/core-components/src/lib/atoms/shadcn/range-calendar/range-calendar.svelte
packages/ui/core-components/src/lib/unsorted/viz/table/_DataTable.svelte
pnpm-lock.yaml

Fixes #1776, #1777
`Select all` option:
Old `DateRange`:
New `DateRange`:

`Dropdown` multiselect `Select all` option and `DateRange` month/year selectors

---

.changeset/violet-scissors-walk.md
packages/ui/core-components/src/lib/organisms/layout/BreadCrumbs.svelte
packages/ui/core-components/src/lib/organisms/layout/EvidenceDefaultLayout.svelte
packages/ui/core-components/src/lib/organisms/layout/header/Header.svelte
packages/ui/core-components/src/lib/organisms/layout/sidebar/Sidebar.svelte
packages/ui/core-components/src/lib/organisms/layout/tableofcontents/TableOfContents.svelte

Adds options to layout:
- `hideHeader`
- `hideBreadcrumbs`
- `hideTOC`
Also modifies some margin/padding to make this possible, but likely needs a good look to make sure the changes are not brittle.

Add options to layout

---

.changeset/twelve-bottles-wink.md
packages/lib/component-utilities/src/echartsCanvasDownload.js
packages/ui/core-components/src/lib/unsorted/viz/map/_EChartsMap.svelte

Fixes map image download button, which was broken after a recent change to the underlying functions use for chart downloads.

Fix map image download

---

.changeset/new-cows-speak.md
packages/ui/core-components/src/lib/unsorted/viz/core/_Delta.svelte
sites/example-project/src/pages/text-and-metrics/big-value/+page.md
sites/example-project/src/pages/text-and-metrics/delta/+page.md

Changes delta neutral symbol from en dash to em dash when `symbolPosition=left`
This helps with BigValue values where positive values could be confused for negative values.
A better long-term solution is needed for this, but putting this in as a short term fix.

Adjust delta neutral symbol

---

.changeset/tough-camels-brush.md
packages/ui/core-components/src/lib/unsorted/viz/core/Delta.svelte
packages/ui/core-components/src/lib/unsorted/viz/table/GroupRow.svelte
packages/ui/core-components/src/lib/unsorted/viz/table/SubtotalRow.svelte
packages/ui/core-components/src/lib/unsorted/viz/table/TableCell.svelte
packages/ui/core-components/src/lib/unsorted/viz/table/TableHeader.svelte
packages/ui/core-components/src/lib/unsorted/viz/table/TableRow.svelte
packages/ui/core-components/src/lib/unsorted/viz/table/TotalRow.svelte
packages/ui/core-components/src/lib/unsorted/viz/table/_DataTable.svelte
packages/ui/core-components/src/lib/unsorted/viz/table/datatable.js
sites/example-project/src/pages/charts/area-chart/+page.md

Fixes issue with manually-specified column order in DataTable
Adjusts spacing for table groups
Removes unnecessary warnings in browser console

DataTable fixes for column order and spacing

---

.changeset/thirty-seals-worry.md
packages/lib/preprocess/src/process-queries.cjs
packages/lib/query-store/src/QueryStore.ts
packages/lib/query-store/tsconfig.json

Lowers memory consumption during builds, especially ones with parameterized pages

Lower memory consumption during builds

---

.changeset/chilled-students-deliver.md
packages/lib/component-utilities/src/echartsCopy.js
packages/ui/core-components/src/lib/atoms/grid/Grid.svelte
packages/ui/core-components/src/lib/organisms/layout/EvidenceDefaultLayout.svelte
packages/ui/core-components/src/lib/unsorted/viz/core/EChartsCopyTarget.svelte
packages/ui/core-components/src/lib/unsorted/viz/map/_EChartsMap.svelte
sites/example-project/src/pages/grid/+page.md

(Updated)
- Adds support for landscape printing
- Fixes printing for Grid components, which were previously incorrectly sized and overlapped each other
Same page shown printed in portrait and landscape
- Sets a fixed print width for portrait pages at 650px and landscape pages at 841px (assumes 8.5x11 page).
- Sets maximum grid columns at 2 for portrait and 3 for landscape
- Adds context to the Grid component to share with child components - charts are now aware they are inside a Grid, the number of columns in the grid, and the gap width
- Safari printing is affected by the width of the browser window when print is selected. This does not happen in other browsers
- Recommendation is to print using another major browser, or adjust your browser window width until the print output meets your …

Fix grid printing & add landscape print support

---

.changeset/quick-ducks-drive.md
sites/example-project/src/app.css

Scrollbar was appearing in print/PDF for some users on Windows. This changes a CSS setting for headers, which was causing unnecessary whitespace, leading to the scrollbar.

Fix windows print scrollbar

---

.github/workflows/tests.yml

- Contributor tests are failing as they do not have access to secrets in their forks. 
- `pull_request_target` allows tests to run in the context of the main repo, and has access to secrets, after approval by a maintainer for tests to run.

Use pull_request_target for tests

---

sites/docs/docs/markdown/index.md

https://docs.evidence.dev/markdown/#frontmatter
suggests `side_bar_position` is the way to change the sidebar ordering. This does not work, the correct key is `sidebar_position`.

fix typo in docu

---

.changeset/lazy-hornets-call.md
packages/ui/core-components/src/lib/atoms/inputs/dropdown/Dropdown.svelte
sites/docs/docs/components/dropdown.md
sites/test-env/pages/dropdown.md

Adds `noDefault` option to `Dropdown` component to allow for no default option to be selected
Adds support for multiple `defaultValue`s via an array being passed

Add `noDefault` option, allow `defaultValue`s to be array in `Dropdown`

---

.changeset/pretty-jobs-wait.md
packages/datasources/postgres/index.cjs
packages/lib/universal-sql/src/calculateScore.js

Closes https://github.com/evidence-dev/evidence/issues/1751 by advising node-pg to extract json/jsonb as string. Also removes universal-sql "warning" when obtaining `::json` results from duckdb (just treat as string in evidence, for now).

Allow json columns in postgres and duckdb

---

.changeset/hungry-chefs-wave.md
packages/datasources/postgres/index.cjs

Closes https://github.com/evidence-dev/evidence/issues/1750.  
This PR just re-adds `standardizeResult` to the first batch. I have not extensively tested this in all combinations; AFAIU from the commits mentioned in #1750 this seems to be the right thing to do, though...

standardizeResult should also be applied to first batch(?)

---

.changeset/sharp-years-film.md
packages/lib/preprocess/index.cjs
packages/lib/preprocess/package.json
packages/ui/core-components/src/lib/organisms/layout/tableofcontents/ContentsList.svelte
pnpm-lock.yaml
sites/example-project/src/pages/links-to-page-headers/+page.md

Addresses #1352
- Adds automatic anchor links to headings (H1-H6) in the preprocess stage.
- Puts H1-H3 in the TOC (rather than H1-H2)
- Links are based on slugified forms of the headers, but are made unique in the case of duplication by appending numbers
- Allows external links to navigate to the correct section of the page eg: `my-project.evidence.app/page-1/#heading-on-the-page`
- Appears to be client side nav only issue
- This is not a regression as this did not work before.
- This uses outdated versions of rehype packages that still support CJS. I suspect the long term solution here is to convert this whole module to ESM, but then we need to rip out Prism (code highlighting) which is CJS only.

Slugified Anchor Links

---

.changeset/smooth-boats-tell.md
sites/example-project/src/app.css
sites/example-project/src/pages/text-and-metrics/markdown/+page.md

maintain correct sizing for bold, italic, strikethrough, code spans

---

.changeset/smart-dryers-hunt.md
packages/ui/core-components/src/lib/unsorted/viz/table/TableRow.svelte

Adds support for HTML in table rows, so you can return HTML from queries and render it in your tables
````
```sql html_in_table
select '<b>Bold</b> text' as "HTML in Table" union all
select '<i>Italic</i> text' as "HTML in Table" union all
select '<a href="https://evidence.dev">Link</a>' as "HTML in Table" union all
select '<img src="/img/how-it-works.png" width="200px"/>' as "HTML in Table"
```
````

HTML in DataTable

---

.changeset/forty-doors-leave.md
packages/datasources/databricks/package.json
pnpm-lock.yaml

Fixes: https://github.com/evidence-dev/evidence/issues/1885 by temporarily downgrading
Maintainer suggested they may be able to release a version with the lz4 dep as optional in the future, which would allow us to get back to latest

downgrade databricks dep to 1.7.1 to remove lz4 dep

---

.changeset/beige-bobcats-applaud.md
packages/ui/core-components/src/lib/organisms/layout/sidebar/Sidebar.svelte
sites/docs/pages/components/all-components.md

closes #1797 
Changes:
- In the `if` check - `if (a.frontMatter?.sidebar_position && b.frontMatter?.sidebar_position)`, we need to check whether the `sidebar_position` value exists. However 0 being a falsy value, if `sidebar_position` is 0 then also the check evaluates to false. This is fixed by using `isNaN` function.
- Updated `sidebar_position` for `All Components` in docs from -1 to 0, where -1 was used as a workaround.

 fix: support 0 as a `sidebar_position`

---

.changeset/sour-papayas-act.md
packages/ui/core-components/src/lib/organisms/layout/EvidenceDefaultLayout.svelte

When hovering the last chart on a page, occasionally a scroll would appear on the page.
This adds padding to the article to eliminate the scrollbar.

Fix scrollbar appearing when hovering last chart on page

---

.changeset/odd-readers-compete.md
packages/ui/core-components/src/lib/unsorted/viz/table/DataTable.svelte
packages/ui/core-components/src/lib/unsorted/viz/table/TableRow.svelte
packages/ui/core-components/src/lib/unsorted/viz/table/_DataTable.svelte
sites/example-project/src/pages/charts/line-chart/+page.md

Errors in DataTable were breaking the page. This patches over a couple of common errors: 
- `data` prop passed as a string instead of using `{ }`
- Incorrect column name passed to `Column`
Incorrect column name error is not handling well here, but better than breaking the page - it currently inserts an empty column with title "undefined"

Reintroduce error handling to DataTable

---

.changeset/red-boxes-impress.md
packages/ui/core-components/src/lib/unsorted/viz/heatmap/_CalendarHeatmap.svelte

fix: calendar heatmap off by 1 error

---

.changeset/big-hornets-hunt.md
sites/example-project/src/pages/charts/stacked-charts/+page.md

Changes:
- In example-poject, /charts/stacked-charts/ , sql queries were not working due to deprecated data={date.query} syntax. Updated to data={query}
closes #1394 
unable to reproduce issue#1394, truncated date string are working when used as x-axis in stacked bar chart
query used:
````
```sql needful_things
select
substr(order_datetime,1,7) as date,
category as category,
sum(sales) as sales_usd0
from needful_things.orders
group by 1, 2
```
<BarChart data={needful_things} x=date y=sales_usd0 series=category type=stacked100/>
````

fix: update deprecated data.query syntax used for stacked charts in example project

---

.changeset/spotty-lions-sleep.md
packages/ui/core-components/src/lib/unsorted/ui/LinkButton.svelte

fix: adds bottom margin on LinkButton

---

.changeset/lucky-carrots-end.md
packages/ui/core-components/src/lib/unsorted/viz/table/_DataTable.svelte

closes #1204 
Changes:
- Added reactive `inputPageElWidth` variable to dynamically update input box width based on input.
query used:
````
```sql needful_things
select * from needful_things.orders
```
<DataTable data={needful_things}/>
````

fix: DataTable pagination input box width overflow

---

.changeset/afraid-countries-sort.md
packages/ui/core-components/src/lib/unsorted/ui/DownloadData.svelte
packages/ui/core-components/src/lib/unsorted/viz/references/ReferenceArea.svelte
packages/ui/core-components/src/lib/unsorted/viz/references/ReferenceLine.svelte
packages/ui/core-components/src/lib/unsorted/viz/references/_ReferenceArea.svelte
packages/ui/core-components/src/lib/unsorted/viz/references/_ReferenceLine.svelte
sites/example-project/src/pages/charts/annotations/+page.md

Fixes #1928 
Adds component wrapper to ReferenceLine and ReferenceArea to allow passing of query stores.

Fix annotation reactivity

---

.changeset/fuzzy-weeks-watch.md
packages/lib/component-utilities/src/getCompletedData.js
sites/example-project/src/pages/charts/line-chart/+page.md

When passing multiple columns to `y`, using `handleMissing` did not take effect. This PR iterates through the y columns to set nulls to the appropriate values.

Handle missing values for multiple y columns

---

.changeset/cyan-carrots-worry.md
packages/lib/preprocess/src/utils/highlighter.cjs
packages/ui/core-components/src/lib/unsorted/ui/CodeBlock.svelte
packages/ui/core-components/src/lib/unsorted/ui/prism-svelte.js
sites/docs/pages/components/data-table.md
sites/example-project/src/app.css
sites/example-project/src/pages/text-and-metrics/code-blocks/+page.md

- Styling issues - `@apply` wasn't working, so for now I've had to override styles in the html tag
- Uses a slightly modified definition of Svelte syntax from `svelte-prism` rather than importing from that library
- Prism themes not working, stuck on default styling
- Import method for languages may not be ideal

Add syntax highlighting to code blocks

---

.changeset/short-grapes-unite.md
packages/ui/core-components/src/lib/unsorted/ui/Details.svelte

`open=false` was not working in the Details component. This fixes that behaviour

Fix Details component open option

---

.changeset/sweet-ducks-peel.md
.changeset/wise-rats-leave.md
packages/lib/sdk/src/usql/setTrackProxy/setTrackProxy.js
packages/lib/sdk/src/usql/setTrackProxy/setTrackProxy.spec.js
packages/ui/core-components/src/lib/atoms/inputs/text/TextInput.svelte
sites/test-env/pages/text-input.md

- text input respects unset now
- setTrackProxy is now callable (returns undefined when unset, but doesn't break b/c not a function)

fix:  text inputs

---

sites/docs/pages/core-concepts/data-sources/index.md

Tells users how to increase the amount of memory allocated to the `npm run sources` command

Add docs on increasing process memory

---

.changeset/big-walls-rule.md
packages/ui/core-components/src/lib/atoms/inputs/dropdown/Dropdown.svelte
packages/ui/core-components/src/lib/atoms/inputs/dropdown/stories/Dropdown.stories.svelte
sites/docs/pages/components/dropdown.md

This PR adds the ability to select all available options in a dropdown by default. I'm just reusing the same action as the `Select all` button.
resolve #1997 #1991 
https://github.com/evidence-dev/evidence/assets/16650656/885fa96a-2908-428f-8503-ccae802ab265
Documentation updates:

feat(UI): Ability to select all dropdown options by default

---

sites/docs/pages/core-concepts/syntax/index.md
sites/docs/pages/reference/markdown.md

This is a small PR. The #710 and #1716 PRs moved the location of `supportedLanguages.cjs` between different places. This PR adjusts sources to changes.

docs: update location of `supportedLanguages.cjs`

---

.changeset/rude-ravens-run.md
packages/lib/sdk/src/usql/query/Query.js
packages/lib/sdk/src/usql/query/Query.spec.js

fix: QueryBuilder fn now inherit opts from parent

---

.changeset/sweet-seas-reflect.md
packages/ui/core-components/src/lib/atoms/inputs/dropdown/dropdownOptionStore.js
packages/ui/core-components/src/lib/atoms/inputs/dropdown/stories/Dropdown.stories.svelte

Before
After
@hughess  - Considering adding a custom sorting option for unique string + number scenarios 
- [ x ] For UI or styling changes, I have added a screenshot or gif showing before & after

Added numerical sorting and Story testing scenarios

---

.changeset/shaggy-sloths-fail.md
packages/ui/core-components/src/lib/unsorted/viz/map/EvidenceMap.js
packages/ui/core-components/src/lib/unsorted/viz/map/Map.stories.svelte

When `title` is supplied in a custom map tooltip, auto-casing should not apply.

Fix tooltip title autocasing in maps

---

sites/docs/pages/index.md
sites/docs/pages/install-evidence.md
sites/docs/pages/motivation.md

- Remove Docker
- Add VSCode marketplace deeplink
- Motivation section to own page

Remove Docker, Break out Motivation as own page

---

.changeset/three-pumpkins-watch.md
packages/ui/core-components/src/lib/unsorted/ui/CodeBlock.svelte
packages/ui/core-components/src/lib/unsorted/ui/prismLoader.js
sites/docs/pages/components/area-map.md

Aims to fix #2041 
Some Prism-related files were causing errors in the browser. These seemed to be triggered by a vite dependency optimization (which is triggered by pages in the `explore/` directory), but I believe the root cause is that `Prism` is not available at the time the other dependencies are imported.
There is some overlap and duplication of Prism usage in various places in the product - ideally we should create a consolidated component for these all to use:
- CodeBlock
- QueryViewer
- Settings > Value Formatting
- Possibly SQL console
- ~~[ ] I have added to the docs where applicable~~ 
- ~~[ ] I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) …

Fix Prism imports in CodeBlock

---

.changeset/fresh-starfishes-sin.md
packages/ui/core-components/src/lib/unsorted/viz/table/_DataTable.svelte

- [x ] For UI or styling changes, I have added a screenshot or gif showing before & after
no big change before if your table columns had spaces i nthe name generateMarkdown wouldnt add ' behind it
now it does
yay

Fix/DataTable Ensure generateMarkdown adds ""  to code when column contains spaces

---

.changeset/tall-hornets-remain.md
packages/ui/core-components/src/lib/unsorted/viz/table/datatable.js
packages/ui/core-components/src/lib/unsorted/viz/table/datatable.spec.js

This makes a very small change to how weightedMeans are calculated, and adds some unit tests to validate the behavior. If @hughess or @archiewood can validate that the unit tests are correct, we should be good to go here

Weighted Mean behavior improvements

---

packages/extension/language-configuration.json
packages/extension/package-lock.json
packages/extension/package.json
packages/extension/snippets/emd.code-snippets
packages/extension/src/commands/cache.ts
packages/extension/src/commands/documents.ts
packages/extension/src/commands/project.ts
packages/extension/src/commands/settings.ts
packages/extension/src/extension.ts
packages/extension/src/providers/markdownSymbolProvider.ts
packages/extension/src/providers/schemaViewProvider.ts
packages/extension/syntaxes/emd.tmLanguage.json

Several new features for writing queries and managing large markdown files.
- Better handling of nested components and indenting
- Headers stay highlighted when indented
When you add any of the below elements to your markdown page, the extension will shade the background to make it clear where that element starts and stops:
- Frontmatter
- SQL queries
- Each blocks
- If blocks
This behaviour can be turned off in the Evidence extension settings in the VS Code settings menu.
You should now see an arrow at the top of large blocks of code on your page - you can click this to collapse that section, making your page easier to read and navigate.  
This also works well for nested elements:
The built-in schema viewer now lets you copy the column names from your schema and paste them into your …

Upgrades and fixes for vscode extension

---

packages/lib/sdk/src/build-dev/vite/datasource-plugins/source-query-hmr.js
packages/lib/sdk/src/plugins/datasources/evalSources.js
packages/lib/sdk/src/plugins/datasources/wrapSimpleConnector.js

This addresses issues noted in #2065 
- The eager loading notification for large files (mostly CSV and DuckDB files) is behind the debug flag, and will not show the warning
- To manage the `no results returned` for some `needful_things` table, we need to modify the duckdb connector to an advanced connector and skip duckdb files, or find some way for simple connectors to indicate that a file is not a query. Either solution (or both) would be okay
- Verbiage has changed for skipped queries / sources
- `[Filtered] source name` has been hidden behind the debug flag, the filtered sources are now only presented as a count at the end by default to reduce noise
- `Skipping: Filtered` for queries has been changed to `This query was not run due to filters`
- `Skipping: Cached` for queries has been …

Datasource CLI Tweaks

---

packages/ui/core-components/src/lib/unsorted/viz/map/Map.stories.svelte

Excludes the base map story from chromatic snapshots. 
The base map story alternates between plotting the orange la locations at the top of the layers and at the bottom, which generate spurious diffs.

Exclude base map story from chromatic snapshots

---

.changeset/ten-ears-build.md
packages/lib/component-utilities/src/formatting.js
sites/test-env/pages/tz.md
sites/test-env/sources/needful_things/random_metrics.sql
sites/test-env/sources/needful_things/tz.sql

This change resolves https://github.com/evidence-dev/evidence/issues/1652
This shouldn't be released on its own, but instead it is a step in the right direction to making timezones less of a pain. Next steps explained below.
Using this query (`tz.sql`)
```sql
WITH inserted as (
SELECT
'2024-06-01 17:00:00+00'::timestamptz as "timestamptz_utc_offset",
'2024-06-01 12:00:00-05'::timestamptz as "timestamptz_local_offset",
'2024-06-01 17:00:00'::timestamp as "timestamp"
)
SELECT * FROM inserted
```
And a datatable with date formatting (`tz.md`)
```svelte
<DataTable data={tz}>
{#each tz.columns as col}
<Column id={col.column_name} fmt="dddd mmmm d, yyyy H:MM:SS AM/PM" />
{/each}
</DataTable>
```
The dates appear in the table in UTC (5pm), not my local time (12pm)
After removing the incorrect …

Fix incorrect date processing related to timezones in `formatting.js`

---

.changeset/big-cougars-retire.md
packages/ui/core-components/src/lib/unsorted/ui/Tabs/Tab.svelte
packages/ui/core-components/src/lib/unsorted/ui/Tabs/Tabs.stories.svelte

Fixes a bug added by https://github.com/evidence-dev/evidence/pull/2158

fix: only use label as id if id not specified

---

.changeset/tough-windows-shout.md
packages/ui/core-components/src/lib/unsorted/viz/references/ReferencePoint/Callout.svelte
packages/ui/core-components/src/lib/unsorted/viz/references/ReferencePoint/ReferencePoint.stories.svelte
packages/ui/core-components/src/lib/unsorted/viz/references/ReferencePoint/ReferencePoint.svelte
packages/ui/core-components/src/lib/unsorted/viz/references/ReferencePoint/reference-point.d.ts
packages/ui/core-components/src/lib/unsorted/viz/references/ReferencePoint/reference-point.store.js
sites/docs/pages/components/annotations.md

The `labelVisible` prop was supposed to control whether the `ReferencePoint`/`Callout` label was visible always or only on hover of the point. However, emphasis was disabled on `ReferencePoint`/`Callout` to fix flickering issues and match the behavior of ReferenceLine and ReferenceArea, so `labelVisible` is no longer functional.
Perhaps we can add it back when we revisit interactions on charts and references.

Remove non-functional labelVisible prop from ReferencePoint and Callout

---

.github/workflows/chromatic.yml
.github/workflows/lint-format.yml
.github/workflows/playwright-tests.yml
.github/workflows/release.yml
.github/workflows/tests.yml

pnpm action-setup is failing, solution is to upgrade to v4.0.0
https://github.com/pnpm/action-setup/issues/135

bump pnpm action-setup

---

.github/workflows/chromatic.yml
.github/workflows/lint-format.yml
.github/workflows/playwright-tests.yml
.github/workflows/release.yml
.github/workflows/tests.yml

See https://github.com/evidence-dev/evidence/pull/2186 for details on why this needs to be merged without tests passing

Upgrade gh action

---

.changeset/red-readers-tan.md
packages/ui/core-components/src/lib/unsorted/viz/core/Value.stories.svelte
packages/ui/core-components/src/lib/unsorted/viz/core/_Value.svelte
sites/docs/pages/components/value.md

Added Link Prop to Value with Blue hover state
Copied the structure of the Link Prop Description from the Link Button
If this styling is ideal, we can normalize the blue hover state, and "link" (e.g Big Link uses "href") to the other components I've come across using links; Big Link, Button Link, Big Value
NOTE:
I think as the linking in charts/graphs becomes more specific (i.e x-axis title link, line chart link), we define those prop descriptions accordingly.

Added link prop to Value Component

---

.changeset/sixty-keys-beam.md
packages/ui/core-components/src/lib/atoms/inputs/dropdown/stories/Dropdown.stories.svelte

https://github.com/evidence-dev/evidence/assets/31896377/ab7a15d8-9623-4cbe-a4a8-28a0b275db2e
Using `select 1 as value` is essentially the same as the complicated date query, all we want to test is that the dropdown can use a default value from a query.

Don't use date in Dropdown story

---

.changeset/bright-toes-march.md
.changeset/clean-frogs-flash.md
packages/lib/sdk/src/lib/sharedPromise.js
packages/lib/sdk/src/utils/index.d.ts
packages/ui/core-components/package.json
packages/ui/core-components/src/lib/atoms/inputs/dropdown/Dropdown.svelte
packages/ui/core-components/src/lib/atoms/inputs/dropdown/dropdownOptionStore.js
packages/ui/core-components/src/lib/atoms/inputs/dropdown/stories/Dropdown.stories.svelte
pnpm-lock.yaml

Fixes #2179 
The root cause was this error:
I fixed that specific error by adding handling for `null`/`undefined` `value`/`label`.
I also enabled `ts-check` for `dropdownOptionStore.js` to catch any other related issues. Tweaked some types to make everything happy.
~~- [ ] For UI or styling changes, I have added a screenshot or gif showing before & after~~
~~- [ ] I have added to the docs where applicable~~
~~- [ ] I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable~~

Dropdown can have option with null `value`/`label`

---

.changeset/spotty-dots-double.md
packages/ui/core-components/src/lib/unsorted/viz/references/ReferenceArea/ReferenceArea.stories.svelte
packages/ui/core-components/src/lib/unsorted/viz/references/ReferenceArea/reference-area.store.js
packages/ui/core-components/src/lib/unsorted/viz/references/ReferenceLine/ReferenceLine.stories.svelte
packages/ui/core-components/src/lib/unsorted/viz/references/ReferenceLine/ReferenceLine.svelte
packages/ui/core-components/src/lib/unsorted/viz/references/ReferenceLine/reference-line.store.js
packages/ui/core-components/src/lib/unsorted/viz/references/ReferencePoint/ReferencePoint.stories.svelte

In the haste of refactoring, new props were added but weren't being properly utilized. Now they are, and we have stories to catch any bugs in the future with these props.
~~- [ ] I have added to the docs where applicable~~
~~- [ ] I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable~~

Fix label and font styling props for ReferenceLine and ReferenceArea

---

.changeset/shaggy-cups-jam.md
packages/lib/sdk/src/build-dev/vite/datasource-plugins/source-query-hmr.js

On a Windows system, the path given to the `watchChange` callback was a unix-style path `/path/to/file.ext`, but the `sourcesDirectory` was a windows style path `C:\\path\to\file.ext` causing us to ignore the watch change.
The fix is simply to use `path.resolve` to convert the `watchChange` `id` to the proper path for the operating system, and using `path.sep` when we split the path into `parts`

Properly handle Windows paths in source query HMR

---

.changeset/healthy-spoons-mix.md
packages/lib/telemetry/index.cjs

Fixes: https://github.com/evidence-dev/evidence/issues/1690
As per the [Segment Docs](https://segment.com/docs/connections/sources/catalog/libraries/server/node/#batching), Segment batches events to send them:
> By default, Segment’s library will flush:
>  - Every 15 messages (controlled by settings.flushAt).
>  - If 10 seconds has passed since the last flush
This causes segment to wait for a long time before flushing, and causes `npm run sources` to hang before the flush completes. The solution is to flush after every event, as recommended by the Segment docs.
(An alternative if we were sending lots more events, would be to decrease the flushInterval)

Fix: Flush telemetry events immediately to prevent sources command hanging

---

.changeset/neat-olives-retire.md
packages/evidence/scripts/build-template.js
packages/ui/core-components/src/lib/organisms/layout/EvidenceDefaultLayout.svelte
sites/example-project/src/service-worker.js

Resolves https://github.com/evidence-dev/evidence/issues/1693
Demo video:
https://github.com/user-attachments/assets/f6ecf747-3c6b-41f4-a942-d3be8de25181

Fix TProtocolException when loading Parquet files on Windows

---

e2e/playwright-config.js

Windows checks were failing here because the preview web server wasn't ready within 1 minute.
This PR increases the timeout to 2 minutes.

Increase playwright preview timeout

---

.changeset/cold-beds-drop.md
packages/ui/core-components/src/lib/unsorted/viz/funnel/_FunnelChart.svelte

- `params.percent` in the formatter function by default is calculated based upon the total, not the initial value (which is most often desired when using funnel charts) docs are not very clear on this https://echarts.apache.org/en/option.html#series-funnel.label.formatter
- fixes https://github.com/evidence-dev/evidence/issues/2469
Before
After

Change `showPercent` param in Funnel Chart to calculate % based upon initial value instead of total

---

.changeset/fast-otters-perform.md
packages/lib/universal-sql/src/build-parquet.js

Resolves https://github.com/evidence-dev/evidence/issues/2463
Running the following commands:
`rm -rf .evidence build && pnpm sources && pnpm build && ls -al build/dat
a/needful_things/orders/`
Before this fix:
```
drwxr-xr-x 2 zach zach   4096 Sep  3 13:09 ./
drwxr-xr-x 3 zach zach   4096 Sep  3 13:09 ../
-rw------- 1 zach zach 450914 Sep  3 13:09 orders.parquet
-rw-r--r-- 1 zach zach   1032 Sep  3 13:09 orders.schema.json
```
After this fix:
```
drwxr-xr-x 2 zach zach   4096 Sep  3 13:04 ./
drwxr-xr-x 3 zach zach   4096 Sep  3 13:04 ../
-rw-r--r-- 1 zach zach 450914 Sep  3 13:04 orders.parquet
-rw-r--r-- 1 zach zach   1032 Sep  3 13:04 orders.schema.json
```

fix: set 644 permissions on output parquet files

---

.changeset/few-beds-appear.md
packages/ui/core-components/src/lib/unsorted/viz/box/Box.svelte
packages/ui/core-components/src/lib/unsorted/viz/box/BoxPlot.stories.svelte
packages/ui/core-components/src/lib/unsorted/viz/box/BoxPlot.svelte

- ~~I have added to the docs where applicable~~
- ~~I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable~~
https://github.com/user-attachments/assets/76df5439-e852-4e37-a335-2a06371c28f9

Fixed duplicate boxplots

---

.changeset/olive-oranges-learn.md
packages/lib/sdk/src/plugins/datasources/evalSources.js
packages/lib/sdk/src/plugins/datasources/loadSources.js

Resolves https://github.com/evidence-dev/evidence/issues/2496

Better error message when running sources without a sources directory

---

.changeset/silent-sloths-begin.md
packages/ui/core-components/src/lib/devtools/_DevTools.svelte

On windows the key comes through as `E`, not `e` when `Shift` is held

fix: dev tools keybind

---

.changeset/tidy-timers-smell.md
e2e/basic/pages/index.md
e2e/basic/tests/tests.spec.js
sites/example-project/src/pages/api/pagesManifest.json/+server.js

Fixes #2326
`src/pages/+page.md` was (accidentally?) being skipped in the `import.meta.glob` that generates the page manifest which was causing the home page to not get any of those options

Fix frontmatter on home page

---

.changeset/wild-dingos-hug.md
packages/evidence/cli.js

Allows environment variables to be used in custom components in development mode, loads .env file in cli and keeps VITE_ prefixed variables.  Fixes #2550

Environment variable fixes

---

.changeset/happy-carrots-invite.md
packages/extension/package.json
packages/extension/snippets/emd.code-snippets
packages/ui/core-components/src/lib/unsorted/ui/Group.svelte
packages/ui/core-components/src/lib/unsorted/ui/index.js
sites/docs/pages/components/grid.md

Adds a Group component for stacking items inside a Grid. If you want multiple items inside the same Group cell, you can now wrap them in a Group component like so:
```html
<Grid cols=2>
<LineChart/>
<Group>
Some text
<BarChart/>
</Group>
</Grid>
```

Group component

---

.changeset/sour-badgers-invent.md
packages/datasources/snowflake/index.cjs

Issue here: https://github.com/snowflakedb/snowflake-connector-nodejs/issues/932 which I believe is a bug with the Snowflake NodeJS lib given my minimal repro
Fixes: https://github.com/evidence-dev/evidence/issues/2527

Suppress OCSP warnings in Snowflake Connector

---

packages/ui/core-components/src/lib/atoms/shadcn/accordion/accordion-trigger.svelte

Prevents the accordion focus ring from displaying in Chrome when you click an accordion.

Prevent accordion focus ring from displaying on click in chrome

---

.changeset/rare-singers-tease.md
.changeset/soft-plums-repeat.md
packages/ui/core-components/src/lib/unsorted/viz/map/BaseMap.stories.svelte
packages/ui/core-components/src/lib/unsorted/viz/map/BaseMap.svelte
packages/ui/core-components/src/lib/unsorted/viz/map/EvidenceMap.js
packages/ui/core-components/src/lib/unsorted/viz/map/components/Bubbles.svelte
packages/ui/core-components/src/lib/unsorted/viz/map/components/Points.svelte
sites/docs/pages/components/base-map.md

Points + Bubbles Layering inconsistency affecting chromatic checks.
This PR seperates Points and Bubbles into separate layers, ensuring Points layers on top of bubbles 
Video:
1. Multiple storybook refreshes showing points layered above bubbles
2. 2 browser refreshes showing points layered above bubbles
https://github.com/user-attachments/assets/39435e78-941e-408c-b064-09f38553e45a
--------------------------------------------------------------------------------------------------------------------------------------------
_**UPDATE**_
**-Example**
The order of layering from bottom - top = [bubbles (yellow), points (green), points(red)]
`<BaseMap title="My Map" height="300">
<Bubbles {...$$restProps} color="yellow"/>
<Points {...$$restProps} color="green" />
<Points {...$$restProps} …

fixed rendering layers Bubbles + Points

---

.changeset/mean-crabs-rescue.md
packages/lib/sdk/src/cli.root.js
packages/lib/sdk/src/logger/EvidenceLogger.js
packages/lib/universal-sql/package.json
packages/lib/universal-sql/src/build-parquet.js
pnpm-lock.yaml

Adds logging to `build-parquet.js` (mainly to diagnose slow builds), also generically adds a `--profile` flag to all `evidence *` commands which profiles the duration of the command's execution

Add parquet building logs + profiling to `evidence *` commands

---

.changeset/wild-cats-teach.md
sites/example-project/src/pages/+layout.js

hide manifest warning toast in prod

---

.changeset/wet-rats-flash.md
packages/datasources/mssql/index.cjs
sites/docs/pages/core-concepts/data-sources/index.md

This pull request adds the connectionTimeout option to the MSSQL connector.
[connectionTimeout](https://tediousjs.github.io/node-mssql/#general-same-for-all-drivers) allows for the extension of the time that a query can run. The current value is left undefined, which leads to the connector defaulting to 15000 ms. This could cause some connections to be terminated if they take longer than 15 seconds to run.

Add connectionTimeout option to MSSQL connector

---

.changeset/old-carpets-poke.md
packages/ui/core-components/src/lib/atoms/inputs/date-range/_DateRange.svelte

This reduces the start date calculation for the 'Last 7 Days', 'Last 30 Days', and 'Last 90 Days' DateRange presets by 1 (for example, 'Last 7 Days' now subtracts 6 days to get the end date instead of 7 days). Previously, selecting one of these presets would select 8 days, 31 days, and 91 days. For example, this is 'Last 7 Days':
Before:
After:

Reduce last x days selectors by 1 in DateRange component

---

sites/docs/components/PropListing.svelte

* Fixes ~50 cases where bare html is being printed when using the props listing `description` prop instead of a slot. 
* Adjusts the breakpoints on prop listing to get into the stacked mode a little earlier 
* Drops the left margin on the stacked prop listing 
Before 
After

support html in prop listing descriptions, adjust breakpoints

---

.changeset/six-waves-drop.md
e2e/prerender/tests/tests.spec.js
packages/ui/core-components/src/lib/unsorted/viz/core/_Chart.svelte

Broken:
Fixed:
Note: removes safeguard Brian put for [showing the empty chart error state when all rows in a series are null](https://github.com/evidence-dev/evidence/pull/2026) - I would think this PR takes higher priority, but would be nice to recover that error indication

Fix transitions between chart states w/ updated data

---

.changeset/young-maps-change.md
packages/ui/core-components/src/lib/unsorted/ui/CodeBlock.svelte
packages/ui/core-components/src/lib/unsorted/ui/QueryViewerSupport/prismtheme.css

Fix Codeblock CLS

---

.changeset/chilled-kiwis-chew.md
packages/datasources/mssql/index.cjs
sites/docs/pages/core-concepts/data-sources/index.md

This PR adds the `requestTimeout` option to the MSSQL connector.
This request is the same as #2699, which I accidentally closed with a force push.

Add requestTimeout to mssql connector

---

.changeset/dirty-taxis-warn.md
packages/lib/sdk/src/plugins/datasources/loadSourceConfig.js

The regex that loads the environment variables for the production environment only includes digits 0 and 1. 
This pull request updates the regex to include digits up to 9.

Support digits 2-9 in env var names names

---

.changeset/chilled-lobsters-sing.md
packages/ui/core-components/src/lib/atoms/inputs/date-range/DateRange.svelte
packages/ui/core-components/src/lib/atoms/inputs/slider/Slider.svelte

`DateRange` wasn't properly receiving its prerendered columns, so it threw away its SSR'd data
`Slider` was flickering from 0 to its true minimum when there's no specified default value, now goes straight to min

Fix `DateRange` flicker, `Slider` default value

---

.changeset/rude-ducks-type.md
packages/ui/core-components/src/lib/organisms/layout/EvidenceDefaultLayout.svelte
packages/ui/core-components/src/lib/organisms/layout/sidebar/Sidebar.svelte
sites/docs/pages/reference/themes-and-layouts/index.md

See https://evidencedev.slack.com/archives/C0239KTKHH7/p1730837677172329

Allow changing the name of the homepage in the sidebar

---

.changeset/cyan-sloths-train.md
packages/ui/core-components/src/lib/unsorted/viz/map/AreaMap.svelte
packages/ui/core-components/src/lib/unsorted/viz/map/BaseMap.stories.svelte
packages/ui/core-components/src/lib/unsorted/viz/map/BaseMap.svelte
packages/ui/core-components/src/lib/unsorted/viz/map/BubbleMap.svelte
packages/ui/core-components/src/lib/unsorted/viz/map/PointMap.svelte
packages/ui/core-components/src/lib/unsorted/viz/map/_BaseMap.svelte

Fix map loading screen layout shift

---

.changeset/few-spoons-move.md
packages/ui/core-components/src/lib/atoms/inputs/slider/Slider.stories.svelte
packages/ui/core-components/src/lib/atoms/inputs/slider/Slider.svelte
sites/docs/pages/components/slider.md

fix #2668 
1. Fixed: ToNumber String Values to avoid errors
2. Improved: console.error for NaN values
`<Story
name="handle string values"
args={{
defaultValue: '18',
fmt: 'usd0',
steps: '2',
max: '20',
min: '0'
}}
/>`
https://github.com/user-attachments/assets/7c02e1f7-cc94-4ff3-85a3-30facc1860ed

fixed string handling for prop values

---

sites/example-project/src/pages/api/pagesManifest.json/+server.js

Fixes tests on < node 20.something

don't rely on `Dirent.parentPath`

---

.changeset/lemon-pugs-divide.md
packages/evidence/scripts/build-template.js

This was causing the input store to not update on the page when running the dev server, resulting in queries that used those inputs to never finish. `@evidence-dev/sdk/utils/svelte` provides `ensureInputContext` which is probably the root cause, though not sure why.

fix: add sdk/utils/evelte to Vite optimizeDeps.include

---

.changeset/config.json

Now the changesets CLI will add the right packages by default, as next is our development branch

make next the base branch for changesets

---

.changeset/twelve-melons-dream.md
packages/lib/component-utilities/src/echarts.js
sites/test-env/pages/echarts-blink.md

Removes resize observation of container element in `echarts.js`. Still works with `Fullscreen`-wrapped charts. I think `Fullscreen` was the only other thing that depended on the resize behaviour, but would be nice if there's a way to test resize animations w/ playwright/storybook.

Fix double loading in accordion-wrapped charts

---

.changeset/happy-toes-change.md
.changeset/wet-tips-worry.md
packages/datasources/duckdb/package.json
packages/evidence/index.js
packages/evidence/scripts/build-template.js
pnpm-lock.yaml

Instead, just put the packages in as strings when building the template
Should fix build failure here: https://github.com/evidence-dev/template/pull/184

fix: dont import injectedEvidenceImports in template vite config

---

.changeset/pretty-worms-worry.md
packages/evidence/scripts/build-template.js

Disables all non-error Vite logging, except in debug mode

Silence all non-error Vite logging

---

.changeset/unlucky-books-compete.md
packages/ui/core-components/src/lib/unsorted/viz/table/DataTable.stories.svelte
packages/ui/core-components/src/lib/unsorted/viz/table/_DataTable.svelte

Originally Data Table was only sorted based on aggregated group values, but the data within each group was unsorted
_Group name not sorting, GDP Growth Russia negative value always first in group_
https://github.com/user-attachments/assets/b859d0df-f2d4-4a77-8c42-1bee29100746
After investigation, the issue was identified: the sorted data was overwritten because the displayed data was repopulated from the original data set. This PR resolves the problem by ensuring the displayed data is only populated during the initial render or when the data changes. This allows the sorted data to render correctly on the page.
https://github.com/user-attachments/assets/b46bd387-da79-4c78-84fb-9ed0ac191cbb

fixed datatable not displaying sorted group data

---

.changeset/heavy-dodos-happen.md
sites/example-project/src/pages/api/pagesManifest.json/+server.js

Fixes regression in last release's `pagesManifest.json` change that didn't properly support v18.17
Was discussing w/ Archie, might be good to add another set of tests that test the minimum version we want to officially support (atm that appears to be 18.13?)

Fix pagesManifest generation for pre-v18.17 node

---

sites/docs/components/DocTab.svelte

https://github.com/user-attachments/assets/eb5c10c6-1440-497f-b8a7-7ab7e23c4296
https://github.com/user-attachments/assets/52f4781a-709c-4179-a4b5-174f2d881a4d
https://github.com/user-attachments/assets/d7069b04-f026-4a8e-b7e8-7a3996a98a24
- ~~[ ] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)~~

[Theming] `DocTab` uses theme

---

sites/docs/pages/components/bar-chart/index.md

Change "duel" to "dual" for bar chart docs.
Simple spelling fix.

Fix spelling mistake

---

.changeset/cuddly-peas-do.md
packages/lib/component-utilities/src/getSeriesConfig.js
packages/ui/core-components/src/lib/unsorted/viz/area/Area.svelte
packages/ui/core-components/src/lib/unsorted/viz/area/AreaChart.stories.svelte
packages/ui/core-components/src/lib/unsorted/viz/area/AreaChart.svelte
packages/ui/core-components/src/lib/unsorted/viz/bar/Bar.svelte
packages/ui/core-components/src/lib/unsorted/viz/bar/BarChart.stories.svelte
packages/ui/core-components/src/lib/unsorted/viz/bar/BarChart.svelte
packages/ui/core-components/src/lib/unsorted/viz/bubble/Bubble.svelte
packages/ui/core-components/src/lib/unsorted/viz/bubble/BubbleChart.stories.svelte
packages/ui/core-components/src/lib/unsorted/viz/bubble/BubbleChart.svelte
packages/ui/core-components/src/lib/unsorted/viz/core/Chart.stories.svelte
packages/ui/core-components/src/lib/unsorted/viz/core/_Chart.svelte
packages/ui/core-components/src/lib/unsorted/viz/line/Line.svelte
packages/ui/core-components/src/lib/unsorted/viz/line/LineChart.svelte
packages/ui/core-components/src/lib/unsorted/viz/scatter/Scatter.svelte
packages/ui/core-components/src/lib/unsorted/viz/scatter/ScatterPlot.stories.svelte
packages/ui/core-components/src/lib/unsorted/viz/scatter/ScatterPlot.svelte
sites/docs/pages/components/area-chart/index.md
sites/docs/pages/components/bar-chart/index.md
sites/docs/pages/components/bubble-chart/index.md
sites/docs/pages/components/line-chart/index.md
sites/docs/pages/components/scatter-plot/index.md

Adding existing evidence/excel formatting properties to series name displayed in chart legends
- ~~[ ] Funnel Chart~~ _does not use charts_
- ~~[ ] Histogram~~ _does not accept multiseries_
_Before:_
`<BarChart {data} />`
_After:_
`<BarChart {data} seriesFmt="pct"/>`

seriesFmt for series labels in charts

---

.changeset/unlucky-ants-enjoy.md
packages/evidence/cli.js
packages/evidence/scripts/build-template.js

Re-enable vite logging in dev

---

.changeset/large-tips-end.md
packages/evidence/cli.js

Hashes parquet files when projects are built via the evidence cli
The logic here is a bit weird to try to align w/ the `process.env.EVIDENCE_DATA_DIR` and `process.env.EVIDENCE_DATA_URL_PREFIX` env vars
The main sketchy part is the `static` directory "disappearing" when static is copied into the build directory, and since we want to(?) allow custom `static` directory naming (via `svelte.config.js`), it's hard to determine the location of `manifest.json` (though its location is hardcoded as `./static/data/manifest.json` in some places which is a whole other problem)
I think if we officially decide you can't have a custom static directory location it can be simplified more (but then I have more complaints about `process.env.EVIDENCE_DATA_DIR` and `process.env.EVIDENCE_DATA_URL_PREFIX`

Hash built parquet files

---

.changeset/fuzzy-zebras-give.md
packages/ui/core-components/src/lib/unsorted/viz/map/_USMap.svelte
packages/ui/core-components/src/lib/unsorted/viz/table/Column.svelte
pnpm-lock.yaml
sites/docs/pages/components/data-table/index.md

Fixes https://github.com/evidence-dev/evidence/issues/2908
**Note: This is a change in behaviour and should be included in the release notes for upgrading users.**

fix: USMap and Column default colorScale is `default`

---

.changeset/lazy-days-cheer.md
packages/ui/core-components/src/lib/atoms/inputs/date-range/DateRange.stories.svelte
packages/ui/core-components/src/lib/atoms/inputs/date-range/_DateRange.svelte
sites/docs/pages/components/date-range/index.md

Adds a **Last 365 days** option to the preset ranges in DateRange
| Before | After |
|--|--|
| ![CleanShot 2024-12-16 at 13 59 38@2x](https://github.com/user-attachments/assets/caeca0e2-0f6c-439d-944b-4951f7e557f7) | ![CleanShot 2024-12-16 at 13 57 13@2x](https://github.com/user-attachments/assets/7882b5be-485e-42e5-b7f9-dc9f4afd1310) |

Last 365 days preset in DateRange

---

sites/docs/pages/components/custom-components/index.md
sites/docs/pages/guides/usql-migration-guide/index.md
sites/docs/pages/plugins/create-component-plugin/index.md

Evidence labs is deprecated and so should be removed from the docs

Docs: Remove Evidence Labs

---

sites/docs/pages/core-concepts/themes/index.md

Feedback from user that this was unclear:
> "The documentation page says that I should add the rule for appearance to the evidence.config.yaml file, however I don't have such a file. 
Adding it to the evidence.plugins.yaml file doesn't seem to have any effect. "

Docs: Clearer themes migration instructions

---

.changeset/five-bottles-worry.md
packages/lib/universal-sql/src/build-parquet.js
sites/test-env/pages/nullish-dates.md
sites/test-env/sources/needful_things/nullish_dates.sql

Fixes #2897
Originates from https://github.com/duckdb/duckdb/pull/14268, so we can remove this workaround when a new stable version of duckdb-wasm is released (it's fixed in [1.29.1-dev17.0](https://www.npmjs.com/package/@duckdb/duckdb-wasm/v/1.29.1-dev17.0))

Fix full null date column source gen

---

.changeset/blue-sloths-sort.md
e2e/hmr/tests/tests.spec.js
packages/lib/preprocess/src/process-queries.cjs

Fixes #2926 
Deletes prerendered queries on HMR so nothing leaks through from edited queries
We could implement some level of caching so non-edited queries aren't deleted, not sure if it's worth the added complexity or not

Fix page query HMR

---

.changeset/clever-avocados-punch.md
packages/lib/sdk/src/plugins/datasources/cli/edit/Options.js
packages/lib/sdk/src/plugins/datasources/cli/edit/Options.spec.js
sites/example-project/src/pages/settings/+page.server.js

fixes datasources that use virtual/references, adds tests, logs info when source updating errors in debug mode
not totally sure this is the proper fix, still not 100% sure of what `Options.ownKeys` semantically represents (I'm understanding it as the keys of the given options that have materialized values in the schema? Or something like that)

Fix virtual source configs

---

.github/workflows/e2e.yml
.github/workflows/tests.yml

Re-adds the windows/mac tests on e2e, mac on non-e2e tests
also removes node-version 18 exclusions because they aren't used anymore (and we also want them to run for the same reason we're re-adding the windows/mac tests)
could also remove node 20 from the next branch exclusion at this point

run mac and windows tests on non-main PRs

---

.changeset/cool-weeks-hang.md
packages/ui/core-components/src/lib/atoms/inputs/date-input/_DateInput.svelte

Regression in border styling for `dateRange` and `dateInput` `range={true}`. Simple fix, `border-r` --> `border-r-0` 
Before:
After:

fixed border regression in dateinput

---

.changeset/wise-papayas-clap.md
packages/ui/core-components/src/lib/atoms/inputs/button-group/ButtonGroup.svelte
packages/ui/core-components/src/lib/atoms/inputs/checkbox/Checkbox.svelte
packages/ui/core-components/src/lib/atoms/inputs/date-range/DateRange.svelte
packages/ui/core-components/src/lib/atoms/inputs/dropdown/Dropdown.svelte
packages/ui/core-components/src/lib/atoms/inputs/slider/_Slider.svelte
packages/ui/core-components/src/lib/atoms/inputs/text/TextInput.svelte
packages/ui/core-components/src/lib/molecules/dimension-grid/DimensionCut.svelte
packages/ui/core-components/src/lib/molecules/dimension-grid/DimensionRow.svelte
packages/ui/core-components/src/lib/unsorted/ui/BigLink.stories.svelte
packages/ui/core-components/src/lib/unsorted/ui/BigLink.svelte
packages/ui/core-components/src/lib/unsorted/ui/LinkButton.stories.svelte
packages/ui/core-components/src/lib/unsorted/ui/LinkButton.svelte
packages/ui/core-components/src/lib/unsorted/ui/Modal.stories.svelte
packages/ui/core-components/src/lib/unsorted/ui/Modal.svelte
packages/ui/core-components/src/lib/unsorted/viz/core/SearchBar.svelte

Styling changes to make components more consistent-looking.
Standardized to the following:
- Margin top: none
- Margin bottom: `mb-4`
- Margin right: `mr-2`
Before and afters below
- DataTable search bar I don't think is 100% right
- Spacing between input components is tricky with titles involved and when only using bottom margin
- One approach we could try is using some top margin and removing it when a title is used (letting the title occupy the margin space)
- When on multiple lines, once a title is included it makes the components look too far apart
- A way to handle groups of inputs (will address in a separate PR with an InputGroup component)
- Tabs styling looks out of place with the rest of components
ButtonGroup is now `inline-block` rather than `inline-flex` to align well with …

Component styling changes for consistency

---

.changeset/green-jeans-hide.md
sites/example-project/src/pages/+page.md

If you delete the index.md page, then you you puzzlingly get the +page.md from the example-project
This adds a warning to help users rectify this case

Warning default index page

---

sites/docs/pages/plugins/create-source-plugin/index.md

Link was outdated since postgres plugin moved into `datasources` subdirectory.
Note: the GH web editor seems to have also changed the newline at the end of the file so lmk if that's an issue and I'll clone/fix locally.

Docs: fix broken link to postgres datasource

---

.changeset/twelve-toes-serve.md
packages/ui/core-components/src/lib/unsorted/viz/table/DataTable.stories.svelte
packages/ui/core-components/src/lib/unsorted/viz/table/_DataTable.svelte

This PR removes the `groupDataPopulated` flag from `_DataTable`. This flag wasn't updated when the `data` object was modified, leading to the DataTable being frozen after the first execution, making grouped DataTables non-interactive.
Closes #2850

Fix table grouping

---

.changeset/olive-walls-clean.md
packages/ui/core-components/src/lib/organisms/layout/sidebar/Sidebar.svelte

Make level three links in the sidebar click-able for the full width of the sidebar, rather than just the width of the text. Aligns the behaviour to level two links.

Expand clickable area of level three sidebar links

---

.changeset/friendly-avocados-shake.md
packages/ui/core-components/src/lib/organisms/layout/EvidenceDefaultLayout.svelte
packages/ui/core-components/src/lib/organisms/layout/header/Header.svelte
sites/docs/pages/reference/layouts/index.md
sites/docs/pages/reference/markdown/index.md

- Adjusts alignment of mobile hamburger menu to get as close to edge of content as possible
- Fixes spacing of page contents when using `sidebar` option in frontmatter
- Adds new options to page frontmatter to better align with layout options and give you control of page-specific layout:
- `hide_header` 
- `hide_toc`
- `hide_breadcrumbs`
- `full_width`
- `max_width`
- Fixes frontmatter in templated pages - closes #2859

Layout and frontmatter adjustments

---

.changeset/ten-humans-fetch.md
packages/ui/core-components/src/lib/unsorted/ui/Details.svelte
packages/ui/core-components/src/lib/unsorted/viz/core/sparkline.js
packages/ui/core-components/src/lib/unsorted/viz/map/components/Areas.svelte
packages/ui/core-components/src/lib/unsorted/viz/map/components/Points.svelte
packages/ui/core-components/src/lib/unsorted/viz/table/TableHeader.svelte
packages/ui/core-components/src/lib/unsorted/viz/table/TableRow.svelte

- Sparkline tooltip background color to `base-100`
- DataTable row lines and header lines slightly lighter
- Details component text lighter
- Maps legends default to `num0` formatting

Minor component styling updates

---

.changeset/odd-cups-attend.md
packages/ui/core-components/src/lib/unsorted/viz/table/_DataTable.svelte

Fixes issue in DataTable where uppercase strings and lowercase strings were sorted separately, which resulted in situations like:
```
Apple
Banana
apple
banana
```
Post fix, this returns:
```
Apple
apple
Banana
banana
```

Fix case sensitivity of sort in DataTable

---

.changeset/lemon-singers-pretend.md
packages/ui/core-components/src/lib/atoms/shadcn/badge/index.js

Noticed when reviewing #2940 brings the badge styling in multi-selects back to pre-themes. 
Before: 
After:

mute multi-select badges

---

.changeset/selfish-coins-wash.md
packages/ui/core-components/src/lib/organisms/layout/EvidenceDefaultLayout.svelte

Ensures when in `Dark mode` or `System: Dark Mode` that print preview will have `light mode` styling
https://github.com/user-attachments/assets/fb54c5d8-ee44-4293-9eca-f134263a11c1
Something I noticed that `system: dark mode` takes care of print preview in `light mode`, whilst keeping the page with `dark mode` styling. It would be ideal if `dark mode` did the same, but couldn't find a way to make that happen.

fix print preview in dark mode

---

.github/workflows/e2e.yml
sites/test-env/evidence.config.yaml

I renamed @evidence-dev/javascript to @evidence-dev/source-javascript but missed this, which is causing CI to fail

Fix datasource ref

---

.changeset/itchy-carrots-chew.md
packages/ui/core-components/src/lib/unsorted/viz/references/ReferenceLine/ReferenceLine.svelte
packages/ui/core-components/src/lib/unsorted/viz/references/ReferencePoint/ReferencePoint.svelte
packages/ui/core-components/src/lib/unsorted/viz/sankey/_SankeyDiagram.svelte
sites/docs/pages/components/charts/annotations/index.md
sites/docs/pages/components/charts/sankey-diagram/index.md

A few explicit color names hanging around, now removed.

Update default color values from 'grey' to 'base-content-muted' in Annotations, and SankeyDiagram

---

.changeset/dull-carrots-invent.md
packages/ui/core-components/src/lib/unsorted/viz/heatmap/Heatmap.stories.svelte
packages/ui/core-components/src/lib/unsorted/viz/heatmap/_Heatmap.svelte

Added toBoolean for `downloadableData` & `downloadableImage` props for Heatmap chart
- [] For UI or styling changes, I have added a screenshot or gif showing before & after

fix download props to handle strings

---

.changeset/shiny-rocks-chew.md
package.json
packages/lib/component-utilities/package.json
packages/lib/component-utilities/src/echarts.js
packages/lib/component-utilities/src/echartsThemes.js
packages/ui/core-components/package.json
packages/ui/core-components/src/lib/unsorted/viz/area/AreaChart.svelte
packages/ui/core-components/src/lib/unsorted/viz/bar/BarChart.svelte
packages/ui/core-components/src/lib/unsorted/viz/box/BoxPlot.svelte
packages/ui/core-components/src/lib/unsorted/viz/bubble/BubbleChart.svelte
packages/ui/core-components/src/lib/unsorted/viz/core/ECharts.svelte
packages/ui/core-components/src/lib/unsorted/viz/core/_Chart.svelte
packages/ui/core-components/src/lib/unsorted/viz/histogram/Histogram.svelte
packages/ui/core-components/src/lib/unsorted/viz/line/LineChart.svelte
packages/ui/core-components/src/lib/unsorted/viz/map/_EChartsMap.svelte
packages/ui/core-components/src/lib/unsorted/viz/scatter/ScatterPlot.svelte
pnpm-lock.yaml
sites/docs/pages/components/charts/area-chart/index.md
sites/docs/pages/components/charts/bar-chart/index.md
sites/docs/pages/components/charts/box-plot/index.md
sites/docs/pages/components/charts/bubble-chart/index.md
sites/docs/pages/components/charts/histogram/index.md
sites/docs/pages/components/charts/line-chart/index.md
sites/docs/pages/components/charts/scatter-plot/index.md

- Echarts upgrade to 5.6.0
- Axis label tooltip for truncated labels
- Datazoom echarts theme adjustments to include handles
- Echarts grid adjustments
- Move padding and margin settings to parent chart container
- Add `leftPadding` and `rightPadding` props to charts for full control of label cutoff
- x label fixes
- All x-labels now show by default on string x-axes
- Truncate when labels overflow, with tooltip to show column name on hover
- Option to wrap using `xLabelWrap`    
```svelte
<LineChart 
data={orders_by_month}
x=month
y=sales_usd0k 
yAxisTitle="Sales per Month"
echartsOptions={{
dataZoom: {
show: true,
bottom: 10
},
grid: {
bottom: 50
}
}}
/>
```

Chart upgrades and spacing improvements

---

packages/ui/core-components/src/lib/unsorted/viz/core/ECharts.svelte

https://github.com/user-attachments/assets/af5f721a-76c5-4cc9-af55-c28c72c6f858
- Move EnterFullScreen component to more sane location
- Calculate height more carefully
- Test edge cases
- title
- title and subtitle
- user has custom height for chart
- graph is in grid

POC full screen charts

---

.changeset/eleven-planets-listen.md
sites/example-project/src/pages/api/pagesManifest.json/+server.js

- Fixed an issue where URLs were being encoded twice
- Corrected handling of the `src/pages/` path in server configuration
In `+server.js`, the URL was being encoded twice due to the following two steps:
- Use of `new URL` to support Windows file paths
- Calculation of `node.href` in the `_buildPageManifest` function.
The following log from `Sidebar.svelte` illustrates the double encoding issue with the fileTree object:
```bash
'white%20space': {
label: 'white%20space',
href: '/white%2520space',
children: {},
frontMatter: [Object],
isTemplated: false,
isPage: true
}
```
The `_buildPageManifest` function expects an unencoded `pagePath` for the computation of variables such as `part` and `label`.
To rectify this, I replaced the use of `new URL` with `path.normalize` and `replace` to …

Fix double URL encoding

---

.changeset/afraid-pumpkins-destroy.md
packages/ui/core-components/src/lib/unsorted/viz/map/USMap.stories.svelte
packages/ui/core-components/src/lib/unsorted/viz/map/_USMap.svelte

Added toBoolean to abbreviation prop in US maps to handle strings, added stories

added toBoolean to handle abbreviations prop string value

---

.github/workflows/e2e.yml
e2e/dev-server-startup/tests/tests.spec.js

[CI] - Use fewer runners for e2e testing

---

.github/workflows/e2e.yml

- Skips full e2e tests if the changes are isolated to the `sites/docs/**` files in the monorepo
- This could be extended to include other CI tests, but these are the slowest ones right now
- The implementation works around [this github limitation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks) around required checks
See this in action: #3072

ci: skip docs only checks

---

.changeset/tiny-trees-judge.md
packages/ui/core-components/src/lib/atoms/hover-card/HoverCard.svelte
packages/ui/core-components/src/lib/unsorted/ui/Info.svelte

Fixes issue with Info component where on mobile, hover to show tooltip did not work. Now clicks will work in addition to hover.

Fix mobile usage issue for Info component

---

.changeset/fluffy-apples-talk.md
packages/evidence/scripts/build-template.js

This mutes an error that popped up with a version upgrade:
```
(node:52040) ExperimentalWarning: CommonJS module /home/brian/code/evidence/template/.evidence/template/t
ailwind.config.cjs is loading ES Module /home/brian/code/evidence/template/node_modules/@evidence-dev/tai
lwind/src/config/config.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

[hotfix] chore: override process warnings from node

---

.changeset/four-mugs-taste.md
e2e/dev-server-startup/package.json
packages/datasources/javascript/package.json
packages/lib/component-utilities/package.json
packages/lib/preprocess/package.json
packages/lib/sdk/package.json
packages/lib/universal-sql/package.json
packages/ui/core-components/package.json
packages/ui/tailwind/package.json
pnpm-lock.yaml
sites/docs/package.json
sites/example-project/package.json

Upgrade vitest 

---

.changeset/breezy-pots-vanish.md
packages/evidence/package.json
pnpm-lock.yaml

Running `npm run dev` in the template with the latest package versions (https://github.com/evidence-dev/template/pull/203) results in the following error:
```failed to load config from /home/zach/code/evidence/template/.evidence/template/vite.config.js
error when starting dev server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@tailwindcss/vite' imported from /home/zach/code/evidence/template/.evidence/template/vite.config.js.timestamp-1739482588321-007c66b6d6a2e.mjs
at packageResolve (node:internal/modules/esm/resolve:857:9)
at moduleResolve (node:internal/modules/esm/resolve:926:18)
at defaultResolve (node:internal/modules/esm/resolve:1056:11)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:654:12)
at #cachedDefaultResolve …
```

Hotfix 2025-02-13

---

sites/docs/pages/core-concepts/data-sources/index.md

Links to CSV, which is already linked to on the line above.

Remove duplicated link

---

.changeset/plenty-rings-nail.md
packages/ui/core-components/src/lib/unsorted/viz/table/TableRow.svelte

Fixes issue where clicking a table row link with openInNewTab=true did not actually open the link in a new tab
There was an issue where setting openInNewTab for a DataTable row would still open the link in the same tab. This can be tested with the example project on the page `/tables/new-table/` by clicking a row in the first table. It opens the link (a Google search) in the same tab even though openInNewTab=true is set. This happens because there is an on:click handler on the TableRow that doesn't take the target=_blank property into account.

Fixes issue with openInNewTab for DataTable rows

---

.changeset/rotten-wasps-poke.md
packages/ui/core-components/src/lib/atoms/inputs/date-input/_DateInput.svelte
sites/docs/pages/components/inputs/date-range/index.md
sites/docs/queries/orders_by_day.sql

New options to the Date Range UI components presets:
- `Month to Today`
- `Year to Today`
The `... to Date` presets sets the end date to the end of the Month and Year, respectively
These new presets will end the date range on the supplied end date
Raised in Bug - https://github.com/evidence-dev/evidence/issues/2450

Date range preset amendment
