evidence-dev/evidence

- packages/components/package.json
- packages/components/viz/Bar.svelte
- packages/components/viz/Bar.svelte.d.ts
- packages/components/viz/BarChart.svelte
- packages/components/viz/BarChart.svelte.d.ts
- packages/components/viz/Column.svelte
- sites/components-workspace/package.json
- sites/components-workspace/src/components/viz/Bar.svelte
- sites/components-workspace/src/components/viz/BarChart.svelte
- sites/components-workspace/src/components/viz/Column.svelte
> Fix column bar

- packages/components/viz/Column.svelte
- packages/components/viz/Hist.svelte
- packages/components/viz/Hist.svelte.d.ts
- sites/components-workspace/src/components/viz/Column.svelte
- sites/components-workspace/src/components/viz/Hist.svelte
Fixes #17  
Fixes #25
Fixes #27
> Fix histogram

- packages/components/viz/BarChart.svelte
- packages/components/viz/Chart.svelte
- packages/components/viz/ColumnChart.svelte
- sites/components-workspace/src/components/viz/BarChart.svelte
- sites/components-workspace/src/components/viz/Chart.svelte
- sites/components-workspace/src/components/viz/ColumnChart.svelte
> Implement default sorting for reverse axis charts

- packages/components/modules/formatValue.js
- packages/components/modules/getColumnFormat.js
- packages/components/modules/getFormatTag.js
- packages/components/viz/Value.svelte
- packages/components/viz/Value.svelte.d.ts
- sites/components-workspace/src/components/modules/formatValue.js
- sites/components-workspace/src/components/modules/getColumnFormat.js
- sites/components-workspace/src/components/modules/getFormatTag.js
- sites/components-workspace/src/components/viz/Value.svelte
- sites/components-workspace/src/pages/index.svelte
> Add formatting to value component

- packages/components/viz/Area.svelte
- packages/components/viz/Bar.svelte
- packages/components/viz/Column.svelte
- packages/components/viz/XAxis.svelte
- packages/components/viz/YAxis.svelte
- sites/components-workspace/src/components/viz/Area.svelte
- sites/components-workspace/src/components/viz/Bar.svelte
- sites/components-workspace/src/components/viz/Column.svelte
- sites/components-workspace/src/components/viz/XAxis.svelte
- sites/components-workspace/src/components/viz/YAxis.svelte
> Bar axis adjustment

- packages/components/modules/formatAxisLabel.js
- packages/components/modules/incrementDate.js
- packages/components/viz/BarChart.svelte
- packages/components/viz/Chart.svelte
- packages/components/viz/ColumnChart.svelte
- packages/components/viz/ColumnChart.svelte.d.ts
- sites/components-workspace/src/components/modules/formatAxisLabel.js
- sites/components-workspace/src/components/modules/incrementDate.js
- sites/components-workspace/src/components/viz/BarChart.svelte
- sites/components-workspace/src/components/viz/Chart.svelte
- sites/components-workspace/src/components/viz/ColumnChart.svelte
- sites/components-workspace/src/pages/index.svelte
> Add date support to column charts

- packages/components/viz/ColumnChart.svelte
- packages/components/viz/ColumnChart.svelte.d.ts
- sites/components-workspace/src/components/viz/ColumnChart.svelte
- sites/components-workspace/src/pages/index.svelte
- sites/example-project/src/pages/charts/index.md
> Column axis title

- packages/preprocess/index.cjs
- packages/preprocess/package.json
- pnpm-lock.yaml
- sites/example-project/src/pages/index.md
- sites/postgres-example/src/pages/index.md
> Fix bug preventing single quotes in markdown preprocessor

- sites/docs/docs/getting-started/connect-data-warehouse.md
> add curly braces to database config instructions

- sites/docs/docusaurus.config.js
> add algolia docsearch to docs

- .changeset/mean-baboons-give.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/workflows/tests.yml
- package.json
- packages/db-orchestrator/package.json
- packages/sqlite/index.cjs
- packages/sqlite/package-lock.json
- packages/sqlite/package.json
- packages/sqlite/test/test.js
- pnpm-lock.yaml
- sites/docs/docs/getting-started/connect-data-warehouse.md
- sites/docs/docs/queries/sql-queries.md
*TODO*:
- Update docs
Closes #108
> feat: Support SQLite as a source

- packages/snowflake/package.json
- packages/sqlite/package.json
Bumps snowflake and sqlite deps.
> Install warnings

- sites/example-project/src/components/viz/Value.svelte
- New styling for Value component errors (pill style)
- Makes it easier to tell that error is interactive
- Fixes spacing issue with placeholder
- Changes message displayed for placeholders
Spacing within the Value error is not ideal, but works fairly well across browsers. This will likely need to be revisited in the future.
> Change style of Value component errors

- sites/example-project/src/components/ui/BreadCrumbs.svelte
Change import location in BreadCrumbs for `pageHasQueries` store
> change import location of pagehasqueries store

- CONTRIBUTING.md
- sites/docs/README.md
Added some minor notes I took down myself that maybe useful to a public contributor.
> Added documentation to run Evidence docs during development and added few more details to the contribution guidelines.

- .changeset/twenty-insects-yell.md
- package.json
- packages/evidence/package.json
- packages/evidence/scripts/build-template.js
- pnpm-lock.yaml
- sites/example-project/package-lock.json
- sites/example-project/package.json
- sites/example-project/src/components/ui/Databases/DatabaseSettingsPanel.svelte
- sites/example-project/src/components/ui/Deployment/DeploySettingsPanel.svelte
- sites/example-project/src/components/ui/Deployment/NetlifyDeploy.svelte
- sites/example-project/src/components/ui/Deployment/OtherDeploy.svelte
- sites/example-project/src/pages/api/settings.json.js
- sites/example-project/src/pages/settings/index.svelte
Pre-releasing this to test in a client repo.
> Deploy panel

- packages/snowflake/package.json
- pnpm-lock.yaml
> bump snowflake-sdk to remove vulnerabilities

- .changeset/quick-radios-cry.md
- sites/docs/docs/deployment/netlify.md
- sites/docs/docs/deployment/vercel.md
- sites/example-project/src/components/ui/Deployment/DeploySettingsPanel.svelte
- sites/example-project/src/components/ui/Deployment/NetlifyDeploy.svelte
- sites/example-project/src/components/ui/Deployment/VercelDeploy.svelte
Adds vercel-specific instructions to the deployments section in settings
> Vercel deploy panel

- .changeset/clever-tigers-walk.md
- packages/evidence/cli.js
Related Issue evidence-dev/evidence#258
> Issue 258 - Copy any arguments passed to evidence cli script over to svelte-kit cli script

- .changeset/strange-days-cheer.md
- sites/docs/docs/tutorial/add-a-chart.md
- sites/docs/docs/tutorial/use-query-results-in-text.md
Updating links in the docs site that were broken in the last docs re-org
> Docs update

- sites/docs/docs/tutorial/add-queries.md
Somehow broke this and didn't notice.
> Fix query in Tutorial

- README.md
To me it looks better and more in line with the rest of headers. What do you think?
> Make the tag line a top-level markdown header

- .changeset/late-berries-bow.md
- sites/example-project/src/components/modules/checkInputs.js
- sites/example-project/src/pages/charts/index.md
> change error message to reference new syntax

- .changeset/odd-years-exercise.md
- sites/example-project/src/components/viz/DataTable.svelte
> Fix boolean false appearance in data table

- .changeset/quiet-moose-collect.md
- packages/evidence/package.json
- packages/evidence/scripts/build-template.js
- packages/telemetry/index.cjs
- packages/telemetry/package.json
- pnpm-lock.yaml
- sites/example-project/package.json
- sites/example-project/src/components/ui/TelemetryOptOut/TelemetrySettingsPanel.svelte
- sites/example-project/src/pages/api/settings.json.js
- sites/example-project/svelte.config.js
> Telemetry updates

- .changeset/cuddly-phones-push.md
- .changeset/eighty-seas-appear.md
- packages/snowflake/package.json
- pnpm-lock.yaml
- sites/example-project/src/components/ui/Databases/SnowflakeForm.svelte
- sites/example-project/src/pages/charts/bar-chart.md
- sites/example-project/src/pages/charts/histogram.md
- sites/example-project/src/pages/charts/line-chart.md
- Updates version of Snowflake SDK used in the Snowflake connector - this was causing authentication issues with some versions of Node
- Fixes the `database` form item for the Snowflake connector in the Settings UI
- Changes query examples in `example-project` to use single quotes rather than double quotes
> Update snowflake sdk

- .changeset/cool-chicken-cheat.md
- sites/example-project/src/app.css
- sites/example-project/src/pages/text-and-metrics/markdown.md
> Blockquote styling

- .changeset/quiet-books-rescue.md
- sites/example-project/src/components/ui/QueryViewerSupport/Prismjs.svelte
Fixes a minor code presentation issue
https://user-images.githubusercontent.com/14029371/200108483-8c2a4d8a-9979-4f43-94c1-230ee77566ce.mov
> Fix code alignment issue in sql viewer

- .changeset/pink-ties-teach.md
- sites/example-project/src/pages/index.md
To confirm that the release process is back on track. re: #456 and #457
> demo change to test release

- .changeset/odd-cows-crash.md
> changeset that should have been included with #366

- .changeset/unlucky-glasses-buy.md
- package.json
- packages/evidence/package.json
- pnpm-lock.yaml
Will allow us to use some new svelte features like {@const}
> bump svelte version

- .changeset/witty-zoos-sing.md
- .github/ISSUE_TEMPLATE/bug_report.md
- packages/db-orchestrator/package.json
- packages/duckdb/.gitignore
- packages/duckdb/CHANGELOG.md
- packages/duckdb/index.cjs
- packages/duckdb/package.json
- packages/duckdb/test/test.js
- pnpm-lock.yaml
- sites/docs/docs/features/queries/sql-queries.md
- sites/docs/docs/getting-started/connect-database.md
- sites/example-project/src/components/ui/Databases/DatabaseSettingsPanel.svelte
- sites/example-project/src/components/ui/Databases/DuckdbForm.svelte
> Add DuckDB as a database connection

- .changeset/dirty-crews-draw.md
- packages/preprocess/index.cjs
> 504 ensure bare query objects are available at load

- .changeset/curly-rabbits-appear.md
- packages/preprocess/index.cjs
- pnpm-lock.yaml
- sites/example-project/package.json
- sites/example-project/src/components/QueryStatus.svelte
- sites/example-project/src/components/ui/stores.js
- sites/example-project/src/pages/paramaterized-pages/[district].md
- sites/example-project/src/pages/paramaterized-pages/index.md
> 507 auto reload during development on parameterized pages

- .changeset/seven-starfishes-behave.md
- sites/example-project/src/components/ui/QueryViewerSupport/Prismjs.svelte
Fixes https://github.com/evidence-dev/evidence/pull/452#issuecomment-1347036478
**Before**
**After**
> Fix indentation in sql viewer

- .changeset/metal-mangos-judge.md
- sites/example-project/src/components/modules/echarts.js
Fixes https://github.com/evidence-dev/evidence/pull/450#issuecomment-1340363141
> Fix chart rendering issue

- .changeset/rude-spoons-travel.md
- sites/example-project/src/components/QueryStatus.svelte
> 519 dev mode status indicator missing page information

- sites/docs/docs/walkthroughs/installation.md
> Docs: Add CLI argument descriptions

- .changeset/pink-wolves-breathe.md
- packages/db-orchestrator/index.cjs
- sites/example-project/src/components/ui/Deployment/NetlifyDeploy.svelte
- sites/example-project/src/components/ui/Deployment/VercelDeploy.svelte
- sites/example-project/src/components/ui/Formatting/CollapsibleTableSection.svelte
- sites/example-project/src/components/ui/Formatting/CustomFormatGrid.svelte
- sites/example-project/src/components/ui/Formatting/CustomFormatsSection.svelte
- sites/example-project/src/components/ui/VersionControl/VersionControlPanel.svelte
- sites/example-project/src/components/viz/BigValue.svelte
Addresses some of the issues in #489:
- Unused CSS
- Security issues with target="_blank" links
- Positive tabindex values
> Addressing CSS and security issues flagged by svelte

- .changeset/serious-mugs-rush.md
- pnpm-lock.yaml
- sites/example-project/package.json
Removes error printed to terminal
> Bump tiny charts 

- .changeset/small-ties-exercise.md
- sites/example-project/src/components/ui/CollapsibleSection.svelte
- sites/example-project/src/components/ui/Deployment/VariableCopy.svelte
- sites/example-project/src/components/ui/Formatting/CustomFormatGrid.svelte
- sites/example-project/src/components/ui/QueryViewerSupport/CompilerToggle.svelte
> Make clickable elements buttons to improve accessibility

- .changeset/long-squids-travel.md
- sites/example-project/src/components/modules/builtInFormats.js
> Fix column title formatting for id columns

- sites/example-project/src/components/ui/DownloadData.svelte
- sites/example-project/src/components/ui/QueryViewerSupport/QueryDataTable.svelte
- sites/example-project/src/components/viz/DataTable.svelte
- sites/example-project/src/components/viz/ECharts.svelte
> Pagination edits

- .changeset/rare-donuts-hope.md
- package.json
- packages/db-orchestrator/index.cjs
- packages/evidence/cli.js
- packages/preprocess/index.cjs
- sites/example-project/src/components/viz/BigValue.svelte
- sites/example-project/src/components/viz/Chart.svelte
- sites/example-project/src/components/viz/Column.svelte
- sites/example-project/src/components/viz/DataTable.svelte
- sites/example-project/src/components/viz/Value.svelte
- sites/example-project/src/components/viz/context.js
This is an attempt to add: "Fail on build error" without disrupting existing projects.
- New CLI command
- New `package.json` command
- New flag `VITE` to propagate the settings
- Rework on `pre-processor` to fail on error in `strict` mode
- Shared `strictBuild` flag
Make a PR in the `template` to bump the version and include the new CLI command
> Add "Fail on build error" to the project

- .changeset/gorgeous-badgers-trade.md
- sites/example-project/src/components/viz/USMap.svelte
> Add strict error option to USMap

- .changeset/four-news-repeat.md
- packages/mysql/index.cjs
Issue-646 Fix broken MYSQL connector due to constant being re-assigned
> Issue-646 Fix constant being re-assigned

- .github/workflows/ui-tests.yml
- tests/README.md
> Fix UI test suite

- .changeset/chatty-socks-search.md
- package.json
- packages/evidence/package.json
- pnpm-lock.yaml
Should resolve incompatible peers issue in current pre-release.
> align sk version with adapter static peer reqs

- .changeset/gorgeous-bikes-clean.md
- .github/workflows/tests.yml
- packages/evidence/scripts/build-template.js
- packages/preprocess/index.cjs
- sites/example-project/src/components/QueryStatus.svelte
- sites/example-project/src/components/ui/BreadCrumbs.svelte
- sites/example-project/src/components/ui/Databases/DatabaseSettingsPanel.svelte
- sites/example-project/src/components/ui/QueryViewer.svelte
- sites/example-project/src/pages/+layout.server.js
- sites/example-project/src/pages/+layout.svelte
- sites/example-project/src/pages/settings/+page.svelte
- Move to relative import instead of lib import for some components
- Add variable `fs` settings on `vite` config
> Misc. Fix for SvelteKit Upgrade

- .changeset/calm-actors-refuse.md
- package.json
- packages/evidence/package.json
- packages/preprocess/package.json
- packages/snowflake/package.json
- pnpm-lock.yaml
- sites/docs/package.json
- sites/example-project/package.json
- sites/example-project/src/components/ui/QueryViewer.svelte
- sites/example-project/src/components/viz/BigValue.svelte
In the template project the `LinkedChart` of `svelte-tiny-linked-charts` was `undefined`. 
- Add the `pnpm` dependencies
- Move the `LinkedChart` to a `svelte:component`
e.g.
```bash
TypeError: Cannot read properties of undefined (reading 'LinkedChart')
at eval (/src/components/viz/BigValue.svelte:122:114)
at Object.$$render (/@fs/Users/charles/DEV/github.com/evidence-dev/template/node_modules/svelte/internal/index.mjs:1876:22)
at eval (/src/pages/+page.md:163:87)
at Object.$$render (/@fs/Users/charles/DEV/github.com/evidence-dev/template/node_modules/svelte/internal/index.mjs:1876:22)
at Object.default (root.svelte:48:41)
at eval (/src/pages/+layout.svelte:155:56)
at Object.$$render (/@fs/Users/charles/DEV/github.com/evidence-dev/template/node_modules/svelte/internal/index.mjs:1876:22) …
```
> LinkedChart Fix + Fix dependencies

- sites/docs/docs/getting-started/what-is-evidence.md
- sites/docs/docs/markdown/index.md
> Fix broken docs links

- .github/workflows/tests.yml
- packages/bigquery/index.cjs
- packages/bigquery/package.json
- packages/bigquery/test/test.js
- pnpm-lock.yaml
This PR should fix the failing bigquery test.
Resolves #719
> Fix MacOS / Node16 Bigquery Test

- .eslintignore
- .prettierignore
Linting the changeset directory doesn't really add value; and just creates friction - so we should not do that. 
- ~~[ ] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)~~
> lint: ignore changeset directory

- .changeset/cuddly-news-reflect.md
- .changeset/gorgeous-jars-jump.md
- sites/example-project/src/components/ui/Databases/BigqueryForm.svelte
- sites/example-project/src/components/ui/Databases/DatabaseSettingsPanel.svelte
- sites/example-project/src/components/ui/Databases/DuckdbForm.svelte
- sites/example-project/src/components/ui/Databases/GenericForm.svelte
- sites/example-project/src/components/ui/Databases/SqliteForm.svelte
- sites/example-project/src/components/ui/Deployment/DeploySettingsPanel.svelte
- sites/example-project/src/components/ui/Deployment/EvidenceDeploy.svelte
- sites/example-project/src/components/ui/Formatting/FormattingSettingsPanel.svelte
- sites/example-project/src/components/ui/Sidebar.svelte
- sites/example-project/src/components/ui/TelemetryOptOut/TelemetrySettingsPanel.svelte
- sites/example-project/src/components/ui/VersionControl/VersionControlPanel.svelte
- sites/example-project/src/pages/+layout.svelte
- sites/example-project/src/pages/queries/sql-file-queries/+page.md
Addressing #736 
- SQLite and DuckDB extension text alignment
| Before | After|
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/63001560/231876907-bb5e6833-c430-4673-bf28-603cfcfbeeff.png) | <img width="630" alt="Screenshot 2023-04-13 at 15 27 57" src="https://user-images.githubusercontent.com/63001560/231876972-cb7fa8c6-5efb-45b3-9f70-0f9497467f5b.png">  |
- Bullet Points
| Before | After|
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/63001560/231877483-a12c8758-7c54-4162-8512-6633886644cc.png) | <img width="1900" alt="Screenshot 2023-04-13 at 16 42 06" src="https://user-images.githubusercontent.com/63001560/231878232-03cfb265-86ba-48c5-a265-7feeb11bdab3.png"> |
- No Bars Below Settings Panels on narrow …
> Clearing visual regressions

- .changeset/wet-eyes-buy.md
- packages/evidence/package.json
- pnpm-lock.yaml
- sites/example-project/package.json
- sites/example-project/src/app.css
- sites/example-project/src/pages/+page.md
- sites/example-project/src/pages/text-and-metrics/lists/+page.md
- sites/example-project/tailwind.config.cjs
> fix list styling

- sites/docs/docs/deployment/vercel.md
This temporarily resolves #727 
- ~~[ ] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)~~
> docs: note that vercel + duckdb doesn't work

- .changeset/curly-apes-greet.md
- sites/example-project/src/components/modules/echartsCopy.js
- sites/example-project/src/components/ui/PageMenu.svelte
- sites/example-project/src/components/viz/ECharts.svelte
- sites/example-project/src/components/viz/EChartsMap.svelte
- sites/example-project/src/components/viz/EchartsCopyTarget.svelte
> fixed chart width when printing to pdf

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/database-connector-request.md
- .github/ISSUE_TEMPLATE/documentation-request.md
- .github/ISSUE_TEMPLATE/feature_request.md
Addresses https://github.com/evidence-dev/evidence/issues/855
> Change bold text to h2 in Github templates

- sites/docs/docs/components/custom-components.md
- sites/docs/docs/components/custom-echarts.md
- sites/docs/docs/core-concepts/components/index.md
- sites/docs/docs/core-concepts/filters/index.md
- sites/docs/docs/core-concepts/queries/index.md
- sites/docs/docs/core-concepts/syntax/index.md
- sites/docs/docs/core-concepts/templated-pages/index.md
- sites/docs/docs/markdown/index.md
- sites/example-project/src/pages/charts/funnel-chart/+page.md
- sites/example-project/src/pages/charts/histogram/+page.md
- sites/example-project/src/pages/charts/line-chart/+page.md
- sites/example-project/src/pages/charts/sankey-chart/+page.md
- sites/example-project/src/pages/charts/stacked-charts/+page.md
- sites/example-project/src/pages/database-specific/bigquery-dates/+page.md
- sites/example-project/src/pages/database-specific/postgres-dates/+page.md
- sites/example-project/src/pages/database-specific/snowflake-dates/+page.md
- sites/example-project/src/pages/database-specific/sqlite-dates/+page.md
- sites/example-project/src/pages/dates-and-times/+page.md
- sites/example-project/src/pages/diagrams/sankey.md
- sites/example-project/src/pages/maps/+page.md
- sites/example-project/src/pages/queries/query-chaining/+page.md
- sites/example-project/src/pages/queries/sql-file-queries/+page.md
- sites/example-project/src/pages/queries/writing-queries/+page.md
- sites/example-project/src/pages/states/[state].md
- sites/example-project/src/pages/states/index.md
- sites/example-project/src/pages/tables/initially-filtered-table/+page.md
- sites/example-project/src/pages/tables/new-table/+page.md
- sites/example-project/src/pages/text-and-metrics/code-blocks/+page.md
- sites/example-project/src/pages/text-and-metrics/value-component/+page.md
This PR should fulfill the requirements for issue #799 
No UI changes. No changeset needed for docs only changes I believe.
> Update info string sql queries

- .github/pull_request_template.md
- .github/workflows/tests.yml
- .github/workflows/ui-tests.yml
Addresses #860 
**UI tests** (ui-tests.yml) will ignore changes to
- docs
- markdown files in root of monorepo (README, LICENSE, CONTRIBUTING etc)
- github templates
**Integration tests** (ie tests.yml) will ignore changes to
- all the above
- example-project/src/pages (the development workspace)
> Only run tests on code changes

- sites/docs/docs/core-concepts/loops/index.md
> Correct {#each} Value component example

- .changeset/serious-needles-kiss.md
- packages/db-orchestrator/index.cjs
> take out automatic duckdb connection

- .changeset/strange-laws-wash.md
- sites/example-project/src/components/ui/Deployment/DeploySettingsPanel.svelte
- sites/example-project/src/components/ui/Deployment/EvidenceDeploy.svelte
- sites/example-project/src/components/ui/Deployment/VariableCopy.svelte
- sites/example-project/src/components/ui/Formatting/CurrencyFormatGrid.svelte
- sites/example-project/src/components/ui/Formatting/CustomFormatsSection.svelte
- sites/example-project/src/components/ui/Formatting/FormattingSettingsPanel.svelte
- sites/example-project/src/components/viz/ErrorChart.svelte
- sites/example-project/src/components/viz/SearchBar.svelte
Fixes #791, #798, #736
---
---
---
---
> Various visual regressions

- .changeset/odd-pillows-fry.md
- packages/mssql/index.cjs
Change SQL Server's environment variable handling to the design from #812
> rewrite mssql environment variables to avoid collisions

- .changeset/odd-boats-cheer.md
- packages/core-components/src/lib/unsorted/viz/Column.svelte
- packages/core-components/src/lib/unsorted/viz/DataTable.svelte
- sites/docs/docs/components/data-table.md
- sites/example-project/src/pages/tables/text-wrapping/+page.md
> 921 control wrap in datatable

- .changeset/pink-doors-smile.md
- packages/bigquery/index.cjs
- packages/core-components/src/lib/unsorted/ui/Deployment/EnvironmentVarListing.svelte
- sites/docs/docs/cli/index.md
changed bigquery default adapter back to service account
> fix bigquery default connection & other places

- .changeset/angry-icons-worry.md
- packages/core-components/src/lib/unsorted/ui/Databases/BigqueryForm.svelte
- packages/core-components/src/lib/unsorted/ui/Deployment/EnvironmentVarListing.svelte
> added authenticator env var to listing, and warnings for browser-only auth

- sites/docs/docs/core-concepts/data-sources/index.md
> Docs: Explain relative filepaths

- sites/docs/docs/getting-started/install-evidence.md
> add vscode install

- .github/workflows/lint-format.yml
> ci: use frozen lockfile for linting

- packages/bigquery/index.cjs
- packages/bigquery/package.json
- packages/mssql/index.cjs
- packages/mssql/package.json
- packages/mysql/index.cjs
- packages/mysql/package.json
- packages/postgres/package.json
- packages/redshift/index.cjs
- packages/redshift/package.json
- packages/snowflake/index.cjs
- packages/snowflake/package.json
- packages/sqlite/index.cjs
- packages/sqlite/package.json
Adds basic types and a wrapping function to allow existing connectors to function as plugins
> [next] Wrap connectors into database plugins

- packages/faker-datasource/index.mjs
- packages/faker-datasource/package.json
- pnpm-lock.yaml
This includes a datasource entirely driven by fakerjs, this will let us create as much fake data in whatever structure we would like.
> [next] Faker datasource

- packages/faker-datasource/filter.mjs
- packages/faker-datasource/index.mjs
- packages/faker-datasource/package.json
- sites/test-env/pages/social-media/index.md
- sites/test-env/pages/social-media/user-analytics.md
- sites/test-env/sources/social_media/comments.yaml
- sites/test-env/sources/social_media/connection.yaml
- sites/test-env/sources/social_media/follows.yaml
- sites/test-env/sources/social_media/hashtags.yaml
- sites/test-env/sources/social_media/likes.yaml
- sites/test-env/sources/social_media/post_tags.yaml
- sites/test-env/sources/social_media/posts.yaml
- sites/test-env/sources/social_media/users.yaml
Contains improvements to the faker datasource (foreign keys!) and an example database for a social media site (thanks ChatGPT)
> [next] Social Media Datasource

- packages/core-components/src/lib/unsorted/TableOfContents.svelte
- packages/core-components/src/lib/unsorted/ui/BreadCrumbs.svelte
- packages/core-components/src/lib/unsorted/ui/Header.svelte
- packages/evidence/cli.js
- packages/evidence/scripts/build-template.js
- sites/example-project/src/pages/+layout.js
- sites/example-project/src/pages/+layout.server.js
- sites/example-project/src/pages/+layout.svelte
- sites/example-project/src/pages/explore/schema/+page.svelte
> [next] Very basic schema explorer for DuckDB

- .changeset/thirty-mirrors-yawn.md
- sites/example-project/src/pages/explore/console/+page.svelte
- sites/example-project/src/pages/explore/schema/+page.svelte
`/explore/schema`
`/explore/console`
> [next] Better Schema Explorer; Add Query Console

- packages/duckdb/index.cjs
- packages/plugin-connector/src/data-sources/get-sources.js
- packages/universal-sql/package.json
- packages/universal-sql/src/client-duckdb/browser.js
- packages/universal-sql/src/client-duckdb/node.js
- sites/example-project/src/pages/+layout.js
This enables the duckdb connector to find files in the sources directory properly
> Update DuckDB Filepath

- .changeset/famous-bags-change.md
Updated changeset for https://github.com/evidence-dev/evidence/pull/817
> UI components changeset

- .changeset/smooth-chairs-end.md
- packages/duckdb/package.json
- pnpm-lock.yaml
> Bump DuckDB to 0.8.1

- packages/component-utilities/src/tests/columnUnitSummary.spec.js
- packages/faker-datasource/index.mjs
- packages/faker-datasource/package.json
- packages/plugin-connector/src/data-sources/build-connector.js
- packages/plugin-connector/src/data-sources/exec-source.js
- packages/plugin-connector/src/data-sources/get-sources.js
- packages/plugin-connector/src/plugin-discovery/resolve-evidence-config.spec.js
- packages/preprocess/src/utils/higlighter.spec.cjs
- packages/redshift/index.cjs
- sites/test-env/package.json
Clean up the buggy tests minus buggy linting
> Fix most tests

- sites/docs/docs/deployment/netlify.md
- sites/example-project/src/pages/states/[state].md
- sites/example-project/src/pages/templated-pages/[category]/+page.md
- sites/example-project/src/pages/templated-pages/[category]/[item]/+page.md
Fixes Netlify normalizing URLs to lowercase
> Make page param comparison lowercase

- .changeset/fresh-carpets-help.md
- packages/component-utilities/src/profile.js
- packages/csv/index.cjs
- packages/preprocess/src/process-queries.cjs
- packages/universal-sql/src/index.d.ts
- sites/example-project/src/pages/+layout.js
> Add `profile` function to measure load / query times

- .changeset/cold-islands-cross.md
- packages/plugin-connector/src/data-sources/schemas/query-runner.schema.js
- packages/plugin-connector/src/data-sources/schemas/query-runner.schema.spec.js
- pnpm-lock.yaml
- Should validate only the first row of a returned dataset (reduce memory usage, improve performance)
- More stringent row checking (columnTypes must match the returned object keys now)
> [next] improve zod schemas

- .changeset/nice-lizards-jog.md
- packages/bigquery/index.cjs
- packages/bigquery/test/test.js
> revamp value standardization in bigquery adapter

- .changeset/tender-maps-worry.md
- packages/evidence/cli.js
- packages/plugin-connector/src/data-sources/exec-source.js
- packages/plugin-connector/src/data-sources/get-sources.js
- packages/plugin-connector/src/data-sources/index.js
- packages/plugin-connector/src/data-sources/schemas/datasource-spec.schema.js
> add source, query, and change filtration to build:sources cli

- .changeset/four-camels-design.md
- packages/component-utilities/src/dateParsing.js
Not sure why this slipped through in my other PR
> fix falsy date handling in `convertColumnToDate`

- .changeset/gorgeous-ladybugs-repeat.md
> Changeset for favicon

- sites/docs/docs/core-concepts/syntax/index.md
- sites/docs/docs/markdown/index.md
Makes partials docs more consistent with other markdown feature styling
> Update partials docs for consistency

- sites/docs/docs/core-concepts/templated-pages/index.md
- Adds example
- fixes syntax
- links to demo project
> Improve templated page docs

- sites/docs/docs/cli/index.md
> Add SQL Server env vars

- sites/docs/docs/cli/index.md
user struggling to find correct information about what build:strict does.
this adds detail and links back to longer description
> make build:strict clearer

- .changeset/two-houses-call.md
- packages/component-utilities/src/profile.js
- packages/core-components/.storybook/preview.js
- packages/core-components/package.json
- packages/core-components/src/lib/atoms/index.js
- packages/core-components/src/lib/atoms/skeletons/Skeleton.svelte
- packages/core-components/src/lib/atoms/skeletons/Skeletons.stories.svelte
- packages/core-components/src/lib/atoms/skeletons/index.js
- packages/core-components/src/lib/unsorted/viz/Chart.svelte
- packages/core-components/src/lib/unsorted/viz/DataTable.svelte
- packages/preprocess/src/process-queries.cjs
- pnpm-lock.yaml
- sites/example-project/src/pages/query-store/+page.md
- sites/test-env/pages/index.md
When `QueryStore` is fetching data; `Chart` and `DataTable` now show skeletons until the data is available
Fixes #1177
> Universal SQL: Loading States

- .changeset/green-pens-repair.md
- packages/core-components/src/lib/unsorted/ui/Databases/DatabaseSettingsPanel.svelte
- packages/core-components/src/lib/unsorted/ui/Databases/DatabricksForm.svelte
- packages/core-components/src/lib/unsorted/ui/Databases/GenericForm.svelte
- packages/databricks/index.cjs
- packages/databricks/package.json
- packages/databricks/test/test.js
- packages/db-orchestrator/package.json
- pnpm-lock.yaml
- sites/docs/docs/cli/index.md
- sites/docs/docs/core-concepts/data-sources/index.md
Adds an adapter for connecting to a databricks database
> Databricks db adapter

- .changeset/nervous-apples-exercise.md
- packages/component-utilities/src/echarts.js
- packages/core-components/src/lib/unsorted/viz/BarChart.stories.svelte
- packages/core-components/src/lib/unsorted/viz/BarChart.svelte
- packages/core-components/src/lib/unsorted/viz/Chart.svelte
- pnpm-lock.yaml
> Fix Y Axis labels being truncated on horizontal bar charts

- .changeset/honest-apes-design.md
- packages/bigquery/index.cjs
> Fix BQ builds

- .changeset/nine-bats-tease.md
- packages/core-components/src/lib/unsorted/viz/Chart.svelte
- packages/core-components/src/lib/unsorted/viz/Hist.svelte
- packages/core-components/src/lib/unsorted/viz/ReferenceArea.svelte
Missed these in the y2 axis changes, minor fixes
> Fix refarea and histogram for y2 axis

- .changeset/stale-nails-hope.md
- packages/duckdb/index.cjs
- packages/duckdb/package.json
- pnpm-lock.yaml
> bump duckdb-async to 0.9.1

- .changeset/fifty-ducks-draw.md
- packages/core-components/package.json
- pnpm-lock.yaml
Fixes issues with dependencies
> move new layout libs to deps from devdeps

- .changeset/moody-kings-refuse.md
- packages/core-components/src/lib/unsorted/ui/Databases/SnowflakeForm.svelte
> Fix snowflake authenticator not persisting in settings

- .changeset/tough-yaks-end.md
- packages/snowflake/package.json
- pnpm-lock.yaml
Bump snowflake-sdk version from 1.6.23 -> 1.9.0, remove dead deps
> bump snowflake version

- sites/docs/docs/core-concepts/syntax/index.md
- sites/docs/docs/markdown/index.md
Image paths are relative by default, and so you need to prepend a `/` to image paths in order to get them to be absolute, which is relative to the `/static` directory.
updates `[My Image](image.png)` -> `[My Image](/image.png)`
> correct the image syntax

- .changeset/smart-boats-cough.md
- packages/core-components/src/lib/unsorted/viz/DataTable.svelte
- pnpm-lock.yaml
- sites/example-project/src/pages/tables/new-table/+page.md
> Fix link/image column type regressions in DataTable

- .changeset/early-bags-collect.md
- packages/telemetry/index.cjs
Add fields needed to de-duplicate projects. This anonymous data will help us better understand how the product is being used.
> Add fields to telemetry

- .changeset/smooth-pumpkins-exercise.md
- packages/preprocess/src/process-queries.cjs
- packages/universal-sql/src/index.d.ts
- pnpm-lock.yaml
- sites/test-env/pages/source-hmr.md
> feat: debounce query stores

- sites/docs/docs/components/custom-components.md
Updates the customization docs to account for new layout
> update docs for logo edit

- sites/docs/docs/guides/system-requirements.md
Updating the maximum node version to match with the current LTS version `v20.10.0`
> Update max node version to 20.10

- .changeset/sour-olives-join.md
- packages/core-components/src/lib/unsorted/ui/QueryViewerSupport/Prismjs.svelte
Fit more lines of SQL in the queryviewer
> reduce queryviewer font size

- .changeset/cyan-wombats-do.md
- packages/plugin-connector/src/data-sources/build-sources.js
- packages/universal-sql/src/index.d.ts
- pnpm-lock.yaml
- sites/test-env/sources/social_media/comments.yaml
- sites/test-env/sources/social_media/follows.yaml
- sites/test-env/sources/social_media/posts/likes.yaml
- sites/test-env/sources/social_media/posts/post_tags.yaml
- sites/test-env/sources/social_media/posts/posts.yaml
- sites/test-env/sources/social_media/users.yaml
See also: https://github.com/sindresorhus/ora/issues/209
> Universal SQL: Fix dev server hanging after spinners run

- .changeset/wise-rocks-exist.md
- packages/core-components/src/lib/organisms/source-config/SourceConfigForm.svelte
- packages/plugin-connector/src/data-sources/update-datasource-options.js
- packages/plugin-connector/src/index.js
- pnpm-lock.yaml
- sites/example-project/src/pages/settings/+page.server.js
This improves the settings ui and prevents locking in a number of situations
> Universal SQL: Update settings ui

- .changeset/soft-pens-shout.md
- packages/duckdb/index.cjs
- packages/duckdb/package.json
- pnpm-lock.yaml
> Universal SQL: DuckDB Connector improvements

- .changeset/cool-ads-check.md
- packages/component-utilities/package.json
- packages/preprocess/src/process-queries.cjs
- packages/universal-sql/src/client-duckdb/node.d.ts
- packages/universal-sql/src/index.d.ts
- pnpm-lock.yaml
While writing the SQL Console component, I encountered a few issues that were easily resolved
> Universal SQL: Misc Fixes

- .changeset/curly-needles-peel.md
- packages/core-components/src/lib/unsorted/viz/Chart.svelte
- packages/core-components/src/lib/unsorted/viz/DataTable.svelte
- packages/universal-sql/src/index.d.ts
This makes sure that the DataTable and Chart report errors - even if the query is reporting a loading state
> Universal SQL: DataTable + Chart Error States

- .changeset/cuddly-snails-prove.md
- packages/core-components/src/lib/organisms/source-config/SourceConfig.svelte
- packages/core-components/src/lib/unsorted/ui/Deployment/EnvironmentVarListing.svelte
- packages/plugin-connector/src/data-sources/index.js
- packages/plugin-connector/src/data-sources/update-datasource-options.js
- packages/universal-sql/src/index.d.ts
- Environment variables now handle newlines better (This may need some testing for different platforms)
- Environment variables now update properly when you save a connection; so you do not need to refresh the page
> Universal SQL: Environment Variable Copy Behaviors

- .changeset/tender-beds-peel.md
- packages/component-utilities/src/profile.js
- packages/core-components/src/lib/organisms/source-config/SourceConfigFormField.svelte
- packages/plugin-connector/src/data-sources/schemas/query-runner.schema.js
- packages/snowflake/index.cjs
- pnpm-lock.yaml
- sites/test-env/evidence.plugins.yaml
- sites/test-env/package.json
> Universal SQL: Underscores in Snowflake Passwords + Misc snowflake fixes

- .changeset/cold-waves-swim.md
- packages/component-utilities/src/checkInputs.js
- packages/component-utilities/src/getColumnEvidenceType.js
- packages/core-components/src/lib/unsorted/ui/QueryViewer.svelte
- packages/core-components/src/lib/unsorted/viz/Chart.svelte
- packages/plugin-connector/src/build-plugins/source-query-hmr.js
- packages/plugin-connector/src/data-sources/index.js
- packages/query-store/src/QueryStore.ts
- packages/query-store/src/types.ts
- packages/universal-sql/src/calculateScore.d.ts
- packages/universal-sql/src/calculateScore.js
> Allow initialdata to saturate columns

- .changeset/funny-peas-rest.md
- packages/universal-sql/package.json
- packages/universal-sql/src/client-duckdb/browser.js
- pnpm-lock.yaml
> Fix windows n hydration

- .changeset/tall-carpets-film.md
- .prettierignore
- packages/core-components/src/lib/atoms/dropdown/Dropdown.svelte
- packages/duckdb/index.cjs
- packages/plugin-connector/src/data-sources/build-sources.js
- sites/docs/docs/getting-started/install-evidence.md
- sites/example-project/src/app.css
- sites/test-env/pages/needful_things.md
Adds basic, consistent styling for the Dropdown component
> dropdown styling

- .changeset/fifty-scissors-yawn.md
- packages/db-commons/index.cjs
- packages/duckdb/index.cjs
- packages/duckdb/test/test.js
- packages/plugin-connector/src/data-sources/index.js
Adds all duckdb types and maps them to Evidence types
> Duckdb Types

- packages/core-components/src/lib/unsorted/ContentsList.svelte
- pnpm-lock.yaml
- sites/test-env/pages/value-in-toc.md
Adds mutation observer to table of contents, and a test case for <Value /> tag in a header to avoid rendering loading... in TOC.
> observe changes in headers for TOC

- .changeset/tiny-pumpkins-lay.md
- packages/core-components/src/lib/atoms/dropdown/Dropdown.svelte
- pnpm-lock.yaml
- sites/example-project/src/pages/ui-components/dropdown/+page.md
> Dropdown inline block

- .github/workflows/tests.yml
> chore: drop v19 and v16 from tests

- .changeset/sixty-zebras-beam.md
- .changeset/stupid-seahorses-explain.md
- packages/component-utilities/src/getCompletedData.js
- packages/component-utilities/src/tests/getCompletedData.spec.js
- packages/universal-sql/src/build-parquet.js
- pnpm-lock.yaml
- sites/test-env/package.json
- sites/test-env/pages/wack-dates.md
> Universal SQL: Pre-release fixes

- sites/docs/docs/components/custom-echarts.md
Flagged in #1431 - just fixing the quote issue as the issue with passing the query is a regression
> Echarts single quotes for strings

- .changeset/pink-dolls-grow.md
- packages/plugin-connector/src/build-plugins/query-directory-hmr.js
- packages/plugin-connector/src/build-plugins/source-query-hmr.js
- packages/plugin-connector/src/build-plugins/vite.js
- packages/preprocess/src/process-queries.cjs
- sites/test-env/queries/external.sql
This adds file watching and query updating to external query files
> feat: query file hmr

- .changeset/angry-coats-talk.md
- .changeset/polite-balloons-breathe.md
- packages/bigquery/index.cjs
- packages/mssql/index.cjs
- Fixes BigQuery
- Fixes MSSQL
- Waiting for MySQL
> Hotfix: Connector issues

- .changeset/stupid-months-dress.md
- packages/core-components/src/lib/unsorted/viz/core/_Chart.svelte
- packages/core-components/src/lib/unsorted/viz/sankey/SankeyDiagram.svelte
> Fix chartAreaHeight issue

- sites/docs/docs/cli/index.md
> Docs: Env vars are case sensitive

- .changeset/proud-drinks-remember.md
- packages/component-utilities/src/buildQuery.js
> fix: buildReactiveInputQuery

- packages/core-components/src/lib/atoms/inputs/dropdown/Dropdown.svelte
- pnpm-lock.yaml
- sites/example-project/src/pages/input-components/dropdown/+page.md
> add title to single select dropdown

- packages/core-components/src/lib/atoms/shadcn/select/select-trigger.svelte
Fix the color of the caret sort icon in date range
> Fix-color-of-date-range-caret-icon

- sites/docs/docs/core-concepts/data-sources/index.md
- Better description of the CSV options
- Adds casing requirements for csv files
> Improve CSV Options docs

- .changeset/six-shrimps-decide.md
- packages/evidence/cli.js
- packages/telemetry/index.cjs
Adds telemetry to dev/build/build:strict/build:sources/preview
> CLI telemetry

- packages/component-utilities/src/echarts.js
- packages/preprocess/src/process-queries.cjs
- sites/test-env/pages/echarts-blink.md
Removes the debounce workaround in `echarts.js` in favour of removing debounced calls during component initialization
> Fix echarts staggering

- packages/plugin-connector/src/data-sources/get-sources.js
> account for nan in timestamp based parquet cleaning

- sites/docs/docs/core-concepts/data-sources/index.md
- sites/docs/docs/core-concepts/queries/index.md
Feedback in slack suggested these docs were not clear currently.
> Clarify file queries docs

- .changeset/strange-dingos-doubt.md
- packages/postgres/index.cjs
> Postgres better errors

- .changeset/tall-cycles-confess.md
- packages/duckdb/index.cjs
- packages/duckdb/package.json
- pnpm-lock.yaml
Upgrade DuckDB to 0.10.0, add custom user agent
> Bump duckdb connector to 0.10.0

- .changeset/three-cameras-trade.md
- packages/core-components/src/lib/unsorted/viz/core/_BigValue.svelte
> Fix sparkline error msg in bigvalue

- .changeset/old-shrimps-develop.md
- packages/core-components/package.json
- pnpm-lock.yaml
- sites/example-project/package.json
> add dependency for chroma

- sites/docs/docs/core-concepts/data-sources/index.md
> Update Motherduck connection details

- .changeset/little-carpets-tell.md
- packages/evidence/cli.js
- pnpm-lock.yaml
- sites/example-project/src/pages/settings/+page.server.js
> Add dev mode flag to telemetry

- .github/workflows/tests.yml
> Add node 18 tests

- .changeset/tall-crews-decide.md
- packages/evidence/scripts/build-template.js
- packages/evidence/scripts/svelte.config.js
> Update Svelte Vite plugin error handling and HMR configuration

- pnpm-lock.yaml
- sites/test-env/.env
- sites/test-env/package.json
> chore: increase build memory when running test

- .changeset/smart-pianos-hang.md
- packages/evidence/package.json
> Fix file imports for evidence package

- .changeset/warm-pigs-develop.md
- packages/ui/core-components/src/lib/organisms/layout/header/Header.svelte
- pnpm-lock.yaml
removes the margin on the right side of the kebab
> remove right margin from default layout header

- .changeset/tall-coins-complain.md
- packages/ui/core-components/src/lib/unsorted/ui/QueryViewer.svelte
> Make query errors copyable

- .changeset/tall-goats-turn.md
- packages/lib/component-utilities/src/autoFormatting.js
- packages/lib/component-utilities/src/getColumnSummary.js
- packages/lib/component-utilities/src/inferColumnTypes.js
- sites/test-env/pages/categories/[category]/index.md
- sites/test-env/pages/categories/index.md
Fixes #1764 
Fixes fully null columns erroring out when formatting
> Fix null number formatting

- .changeset/flat-falcons-burn.md
- packages/lib/sdk/package.json
- packages/ui/core-components/package.json
- pnpm-lock.yaml
Upgrade all svelte deps to 4.2.12
> Fix-svelte-deps

- .changeset/gold-eagles-vanish.md
- packages/ui/core-components/src/lib/unsorted/viz/scatter/Scatter.svelte
> Adjust scatter hover to focus on individual point

- .changeset/neat-wombats-judge.md
- packages/ui/core-components/src/lib/unsorted/viz/core/_Delta.svelte
Same issue as #1796 , just missed this one
> Fix null handling in delta

- .github/workflows/ui-tests.yml
> use .app in netlify deploy GH action

- .changeset/funny-falcons-act.md
- packages/lib/db-commons/index.cjs
See https://github.com/evidence-dev/evidence/issues/1735
> source sql ending in a line comment need final newline

- .changeset/silver-tools-serve.md
- packages/lib/component-utilities/src/echarts.js
Closes https://github.com/evidence-dev/evidence/issues/1795
> fix echarts options update

- .changeset/eleven-turtles-pull.md
- sites/example-project/src/app.css
- sites/example-project/src/pages/text-and-metrics/markdown/+page.md
> Fix header link sizes

- packages/evidence/scripts/build-template.js
ref #1876
this should suppress that annoying message
> Fix: ignore a specific warning during dev server run

- .changeset/stale-falcons-compete.md
- packages/ui/core-components/src/lib/unsorted/ui/Deployment/EvidenceDeploy.svelte
> Update Evidence Cloud link in settings

- .changeset/giant-trainers-invent.md
- .github/workflows/ui-tests.yml
- packages/ui/core-components/src/lib/atoms/inputs/date-range/_DateRange.svelte
Adds several new presets to the defaults included in the date range and a separator between groups.
> Additional date range presets

- .changeset/silver-clocks-tie.md
- packages/ui/core-components/src/lib/atoms/inputs/date-range/DateRange.svelte
- packages/ui/core-components/src/lib/atoms/inputs/date-range/_DateRange.svelte
https://github.com/evidence-dev/evidence/assets/61282104/2bec3557-4288-4076-8209-ff78066b2bf6
https://github.com/evidence-dev/evidence/assets/61282104/ab019b40-503d-4456-baf6-8e80bd430ffa
> DateRange loading state

- packages/ui/core-components/src/lib/unsorted/ui/CodeBlock.svelte
- sites/example-project/src/app.css
Inlines and simplifies the styling on code fences
> Code-highlight-css

- packages/ui/core-components/src/lib/atoms/inputs/date-range/_DateRange.svelte
> fix last month preset

- .changeset/sour-fans-remain.md
- packages/ui/core-components/src/lib/unsorted/viz/table/_DataTable.svelte
> fix null column errors

- .changeset/calm-dragons-dress.md
- packages/ui/core-components/src/lib/unsorted/viz/core/_Sparkline.svelte
- sites/example-project/src/pages/text-and-metrics/sparkline/+page.md
> Fix reactivity for sparklines

- .changeset/shiny-avocados-fly.md
- packages/ui/core-components/src/lib/atoms/inputs/button-group/ButtonGroup.svelte
- sites/test-env/pages/button-range.md
> fix: add loading state to ButtonGroup

- .changeset/silver-trainers-draw.md
- packages/ui/core-components/src/lib/unsorted/viz/core/_BigValue.svelte
- sites/example-project/src/pages/text-and-metrics/big-value/+page.md
> Fix BigValue downIsGood

- .changeset/pretty-ghosts-melt.md
- packages/datasources/duckdb/package.json
- pnpm-lock.yaml
> bump duckdb connector

- .github/workflows/tests.yml
> chore: add kyle to test runs

- .changeset/shaggy-bulldogs-approve.md
- .changeset/tricky-garlics-admire.md
- packages/ui/core-components/src/lib/unsorted/viz/map/BaseMap.svelte
- packages/ui/core-components/src/lib/unsorted/viz/map/EvidenceMap.js
- packages/ui/core-components/src/lib/unsorted/viz/map/Map.stories.svelte
- pnpm-lock.yaml
> chore: map improvements

- .changeset/hot-goats-happen.md
- packages/ui/core-components/src/lib/atoms/inputs/dropdown/Dropdown.svelte
- packages/ui/core-components/src/lib/atoms/inputs/dropdown/stories/DependentDropdowns.story.svelte
- packages/ui/core-components/src/lib/atoms/inputs/dropdown/stories/Dropdown.stories.svelte
- packages/ui/core-components/src/lib/storybook-helpers/WithScopedInputStore.svelte
> Dropdown `selectAllByDefault` is not being respected when the query changes

- .changeset/chatty-crabs-know.md
- packages/ui/core-components/src/lib/atoms/accordion/AccordionItem.svelte
- sites/example-project/src/pages/ui-components/accordion/+page.md
Adds an optional `title` slot to accordion items.
> Optional accordion title slot

- .changeset/dry-peaches-smoke.md
- packages/lib/component-utilities/src/buildQuery.js
- packages/lib/sdk/src/usql/query/Query.js
- packages/lib/universal-sql/src/index.d.ts
- packages/ui/core-components/src/lib/atoms/inputs/dropdown/Dropdown.svelte
- packages/ui/core-components/src/lib/atoms/inputs/dropdown/stories/Dropdown.stories.svelte
> Dropdown Ordering Fixes

- sites/docs/pages/components/checkbox.md
- [x ] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x ] I have added to the docs where applicable
> Added props table to checkbox docs

- .changeset/soft-walls-love.md
- .changeset/twenty-gifts-learn.md
- packages/lib/sdk/src/types/mosaic-sql.d.ts
- packages/lib/sdk/src/usql/query/Query.js
- packages/ui/core-components/src/lib/unsorted/viz/core/Value.stories.svelte
- packages/ui/core-components/src/lib/unsorted/viz/core/Value.svelte
- sites/docs/pages/components/value.md
- [x ] I have added to the docs where applicable
> updated agg prop to Value component

- .changeset/fresh-bugs-rescue.md
- packages/ui/core-components/src/lib/atoms/inputs/dropdown/Dropdown.svelte
- packages/ui/core-components/src/lib/atoms/inputs/dropdown/stories/Dropdown.stories.svelte
- [x ] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)
> updated dropdown select all function for non-query options

- .changeset/proud-peaches-search.md
- .changeset/tasty-beers-chew.md
- packages/lib/sdk/src/usql/query/Query.js
- packages/ui/core-components/src/lib/atoms/index.js
- packages/ui/core-components/src/lib/atoms/query-debugger/QueryDebugger.svelte
- packages/ui/core-components/src/lib/atoms/query-debugger/Section.svelte
- packages/ui/core-components/src/lib/atoms/query-debugger/index.js
This adds a new component that can be used to investigate the queries that have run on the page. It isn't designed for general usage and so it has not been documented.
> QueryDebugger

- .changeset/shaggy-dryers-explain.md
- packages/datasources/duckdb/package.json
- pnpm-lock.yaml
> Bump DuckDB Connector to 1.0

- sites/docs/pages/core-concepts/data-sources/index.md
- sites/docs/pages/reference/cli.md
Fixes https://github.com/evidence-dev/evidence/issues/1747
> Docs: build variables and .env files

- .changeset/spotty-coats-tickle.md
- sites/example-project/src/pages/+layout.js
- sites/example-project/src/pages/charts/annotations/+page.md
Custom Format used for Start date similar to the user's issue, end date for comparison
resolves #2088
> Fix Custom Formatting 

- .changeset/strong-gifts-swim.md
- sites/docs/pages/components/dropdown.md
> updated docs with selectAllByDefault

- .changeset/afraid-parrots-hammer.md
- .github/workflows/tests.yml
- packages/lib/sdk/src/plugins/datasources/evalSources.js
- packages/lib/sdk/src/plugins/datasources/loadSourcePlugins.js
- packages/lib/sdk/src/plugins/datasources/schemas/datasource.schema.js
- packages/lib/sdk/src/plugins/datasources/wrapSimpleConnector.js
- packages/lib/universal-sql/src/build-parquet.js
- packages/lib/universal-sql/src/build-parquet.spec.js
- packages/lib/universal-sql/src/client-duckdb/browser.js
- packages/lib/universal-sql/src/client-duckdb/node.js
This lets you batch results in smaller batches in case you have extremely wide tables
> Feat: Configurable Batch Sizes

- .changeset/rotten-cars-perform.md
- packages/ui/core-components/package.json
- packages/ui/core-components/src/lib/unsorted/ui/Tabs/Tab.svelte
- packages/ui/core-components/src/lib/unsorted/ui/Tabs/Tabs.stories.svelte
- packages/ui/core-components/src/lib/unsorted/ui/Tabs/Tabs.svelte
- packages/ui/core-components/src/lib/unsorted/ui/Tabs/index.d.ts
- pnpm-lock.yaml
Fixes #1972 
Before:
https://github.com/evidence-dev/evidence/assets/31896377/1aeab317-1860-4989-95e4-d21c02c0ba2c
After:
https://github.com/evidence-dev/evidence/assets/31896377/b9816fc6-f101-4ece-ae68-4bd8737e11a8
> Use an `internalId` in tabs to enable dynamic `label`/`id` from a query

- .changeset/beige-squids-sort.md
- packages/ui/core-components/src/lib/unsorted/viz/references/ReferenceLine.stories.svelte
- packages/ui/core-components/src/lib/unsorted/viz/references/_ReferenceLine.svelte
> Fix ReferenceLine dynamic xy

- .changeset/rotten-readers-end.md
- .changeset/two-carrots-count.md
- packages/lib/sdk/src/plugins/datasources/evalSources.js
- packages/lib/sdk/src/plugins/datasources/schemas/datasourcePlugin.schema.js
- packages/lib/sdk/src/plugins/datasources/updateManifest.js
- packages/lib/sdk/src/plugins/datasources/updateManifest.spec.js
This resolves an issue where adding new sources required deleting and recreating the manifest file
This also adds .schema.json file generation again to resolve an issue in the extensions
> fix: several datasource regressions

- .changeset/real-spiders-roll.md
- packages/lib/sdk/src/plugins/datasources/evalSources.js
- packages/lib/sdk/src/plugins/datasources/schemas/manifest.schema.js
- packages/lib/sdk/src/plugins/datasources/updateManifest.js
- packages/lib/sdk/src/plugins/datasources/updateManifest.spec.js
> Allow sources to be removed from the manifest

- .changeset/smart-glasses-taste.md
- packages/evidence/scripts/build-template.js
> chore: remove sdk from optimizeDeps

- .changeset/smart-rice-tickle.md
- packages/lib/component-utilities/src/formatTitle.js
- packages/ui/core-components/src/lib/molecules/dimension-grid/DimensionCut.svelte
- packages/ui/core-components/src/lib/molecules/dimension-grid/DimensionGrid.stories.svelte
- packages/ui/core-components/src/lib/molecules/dimension-grid/_DimensionGrid.svelte
> Updated Dimension grid take in queries with spaces

- .changeset/tricky-avocados-shout.md
- packages/ui/core-components/src/lib/atoms/inputs/dropdown/Dropdown.svelte
- packages/ui/core-components/src/lib/atoms/inputs/dropdown/dropdownOptionStore.js
- pnpm-lock.yaml
- sites/test-env/pages/lots-of-dropdowns.md
Paired with @ItsMeBrianD to find these couple of fixes.
> Fix Dropdown query-based default value performance and race conditions

- .changeset/fuzzy-deers-yawn.md
- packages/ui/core-components/src/lib/atoms/inputs/dropdown/dropdownOptionStore.js
Fixes a bug added here: https://github.com/evidence-dev/evidence/pull/2203
> Fix dropdown select

- sites/docs/pages/core-concepts/syntax/index.md
> remove extra / in partial docs

- .changeset/six-gorillas-fail.md
- packages/ui/core-components/src/lib/unsorted/viz/heatmap/CalendarHeatmap.stories.svelte
> Calendar heatmap stories

- .changeset/hip-crabs-give.md
- .changeset/pretty-rings-tie.md
- packages/lib/sdk/package.json
- packages/lib/sdk/src/build-dev/vite/datasource-plugins/source-query-hmr.js
- packages/lib/sdk/src/build-dev/vite/index.js
- packages/lib/sdk/src/build-dev/vite/sidecar-app.js
- packages/lib/sdk/src/index.js
- packages/lib/sdk/src/lib/projectPaths.js
- packages/lib/sdk/src/lib/projectRoot.js
- packages/lib/sdk/src/meta.js
- packages/lib/sdk/src/plugins/datasources/cli/edit/editSourceConfig.js
- packages/lib/sdk/src/plugins/datasources/cli/sources.js
- packages/lib/sdk/src/plugins/datasources/evalSources.js
- packages/lib/sdk/src/utils/index.js
- pnpm-lock.yaml
- sites/example-project/package.json
- sites/example-project/src/pages/api/[...route]/evidencemeta.json/+server.js
> Fix SPA Mode

- .changeset/small-doors-deny.md
- packages/lib/sdk/package.json
- packages/lib/sdk/src/build-dev/vite/virtuals-dynamic.js
> Update SDK package scripts

- .changeset/wild-carrots-judge.md
- packages/ui/core-components/src/lib/unsorted/viz/references/ReferenceArea/reference-area.store.js
- packages/ui/core-components/src/lib/unsorted/viz/references/ReferenceLine/reference-line.store.js
- packages/ui/core-components/src/lib/unsorted/viz/references/ReferencePoint/reference-point.store.js
- sites/docs/pages/components/annotations.md
> References wait for data to set ECharts config

- sites/docs/pages/core-concepts/data-sources/index.md
Added explanation to use postgres ssl certificates with example template for the yaml files.
> Update docs for postgres using SSL certificates

- .changeset/shaggy-socks-sort.md
- packages/ui/core-components/src/lib/unsorted/viz/core/Value.stories.svelte
- packages/ui/core-components/src/lib/unsorted/viz/core/_Value.svelte
- sites/docs/pages/components/data-table.md
- sites/docs/pages/components/value.md
> Conditonal rendering value

- .changeset/pink-cats-cheer.md
- packages/ui/core-components/src/lib/unsorted/ui/Tabs/Tabs.svelte
~~I have added to the docs where applicable~~
~~I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable~~
Before:
After:
> changed tabs inactive border styling

- .changeset/fair-toys-argue.md
- packages/lib/preprocess/src/process-queries.cjs
- packages/lib/sdk/src/usql/query/Query.js
- sites/example-project/src/pages/+layout.js
- tests/UI/dataTable.spec.ts
Resolves https://github.com/evidence-dev/evidence/issues/2248
Resolves https://github.com/evidence-dev/evidence/issues/2216
> Include column metadata during prerendering

- .changeset/popular-poets-refuse.md
- packages/evidence/cli.js
> fix: increase node memory limit

- packages/datasources/mssql/package.json
- pnpm-lock.yaml
- sites/test-env/evidence.plugins.yaml
- sites/test-env/package.json
~~For UI or styling changes, I have added a screenshot or gif showing before & after~~
~~I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)~~
~~I have added to the docs where applicable~~
~~I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable~~
fix #2285
> removed mssql icon

- .changeset/brave-toys-press.md
- .prettierignore
- packages/ui/core-components/src/lib/atoms/query-load/QueryLoad.svelte
- packages/ui/core-components/src/lib/unsorted/viz/map/AreaMap.svelte
- packages/ui/core-components/src/lib/unsorted/viz/map/BaseMap.svelte
- packages/ui/core-components/src/lib/unsorted/viz/map/BubbleMap.svelte
- packages/ui/core-components/src/lib/unsorted/viz/map/EvidenceMap.js
- packages/ui/core-components/src/lib/unsorted/viz/map/Map.stories.svelte
- packages/ui/core-components/src/lib/unsorted/viz/map/PointMap.svelte
- packages/ui/core-components/src/lib/unsorted/viz/map/USMap.stories.svelte
- packages/ui/core-components/src/lib/unsorted/viz/map/components/Areas.svelte
- pnpm-lock.yaml
- sites/docs/pages/components/area-map.md
- sites/docs/pages/components/base-map.md
https://github.com/user-attachments/assets/f31e8b48-8d33-4ddf-9807-e57b02126960
> Add skeleton loading state to Area Map, Bubble Map, and Point Map

- sites/docs/pages/motivation.md
> Remove dead NYT link from docs

- .changeset/weak-beers-unite.md
- packages/ui/core-components/src/lib/unsorted/ui/CodeBlock.svelte
> Remove max height from codeblock

- .changeset/little-plums-repeat.md
- packages/ui/core-components/src/lib/atoms/fullscreen/Fullscreen.svelte
- packages/ui/core-components/src/lib/organisms/layout/sidebar/Sidebar.svelte
- packages/ui/core-components/src/lib/unsorted/viz/table/DataTable.stories.svelte
- packages/ui/core-components/src/lib/unsorted/viz/table/_DataTable.svelte
- ~~I have added to the docs where applicable~~
- ~~I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable~~
1. Removed Scroll to top
2. Removed Scroll when modal is open
3. Fixed esc key behaviour that locked user out from fullscreen mode
https://www.loom.com/share/127253117d0840f3af0650cae7ff0699
> removed scroll to top and fixed esc close for fullscreen mode

- .github/DISCUSSION_TEMPLATE/data-source-request.yaml
- .github/DISCUSSION_TEMPLATE/ideas.yaml
- .github/ISSUE_TEMPLATE/config.yml
- CONTRIBUTING.md
- README.md
- packages/extension/README.md
- Updates links to GH discussions
- Moves templates to discussion templates
When we merge this PR, we should archive the #feature-ideas channel on Slack
> GH Discussions

- .github/DISCUSSION_TEMPLATE/data-source-request.yaml
- .github/DISCUSSION_TEMPLATE/ideas.yaml
removes invalid fields from GH Discussion templates
> Remove invalid fields from Discussions

- .changeset/cyan-peas-arrive.md
- .changeset/forty-apricots-brake.md
- packages/ui/core-components/src/lib/atoms/inputs/dropdown/Dropdown.svelte
- packages/ui/core-components/src/lib/atoms/inputs/dropdown/stories/Dropdown.stories.svelte
- packages/ui/core-components/src/lib/unsorted/viz/map/AreaMap.stories.svelte
- packages/ui/core-components/src/lib/unsorted/viz/map/AreaMap.svelte
- packages/ui/core-components/src/lib/unsorted/viz/map/BaseMap.svelte
- packages/ui/core-components/src/lib/unsorted/viz/map/EvidenceMap.js
- packages/ui/core-components/src/lib/unsorted/viz/map/components/Areas.svelte
https://github.com/user-attachments/assets/b4ded673-c843-47fb-ad6a-3b054a732c8e
> Make AreaMap `geoJsonUrl` reactive

- .changeset/fair-beers-roll.md
- packages/datasources/snowflake/package.json
- packages/lib/component-utilities/src/echarts.js
- packages/lib/component-utilities/src/stores.js
- packages/lib/sdk/src/plugins/datasources/wrapSimpleConnector.js
- packages/lib/telemetry/index.cjs
- packages/ui/core-components/src/lib/molecules/dimension-grid/dimensionGridQuery.js
- packages/ui/core-components/src/lib/unsorted/viz/core/_Delta.svelte
- packages/ui/core-components/src/lib/unsorted/viz/map/BaseMap.svelte
- packages/ui/core-components/src/lib/unsorted/viz/references/ReferenceArea/reference-area.store.js
- packages/ui/core-components/src/lib/unsorted/viz/references/ReferenceLine/reference-line.store.js
- pnpm-lock.yaml
- Fixes CVE.
- Formatter test made me change some other files for tests but only formatting.
> bump axios for CVE

- sites/docs/pages/core-concepts/syntax/index.md
- sites/docs/pages/reference/markdown.md
Here is the page to review: https://docs-dj371ghn3-evidence.vercel.app/reference/markdown/#frontmatter
> More detail in breadcrumbs docs

- packages/extension/package.json
- pnpm-lock.yaml
Resolves https://github.com/evidence-dev/evidence/security/dependabot/147
> bump webpack to 5.94.0

- .changeset/khaki-countries-scream.md
- packages/ui/core-components/src/lib/atoms/inputs/dropdown/Dropdown.svelte
- packages/ui/core-components/src/lib/atoms/inputs/dropdown/stories/Dropdown.stories.svelte
- ~~I have added to the docs where applicable~~
- ~~I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable~~
> added string check for selectAllByDefualt

- .changeset/strong-cheetahs-breathe.md
- e2e/hmr/pages/error-handling/reserved-word-query-name.md
- e2e/hmr/tests/tests.spec.js
- packages/lib/component-utilities/src/hmrErrorHandling.js
- pnpm-lock.yaml
Resolves: https://github.com/evidence-dev/evidence/issues/2343
> Add hmr error handling for reserved words query names

- sites/docs/pages/components/dropdown.md
Fixes https://github.com/evidence-dev/evidence/issues/2456
> Fix dropdown order docs

- e2e/create-e2e-project.js
- e2e/package.json
- pnpm-lock.yaml
https://github.com/user-attachments/assets/2d253b31-c884-4459-9db1-074152bb946a
> feat: `create-e2e-project` script to automate e2e project creation

- sites/docs/pages/deployment/environments.md
- sites/docs/pages/deployment/overview.md
- sites/docs/pages/deployment/rendering-modes.md
> SPA mode docs

- .changeset/eleven-items-hear.md
- packages/lib/preprocess/package.json
- packages/lib/preprocess/src/add-classes.cjs
- packages/lib/preprocess/src/add-script-tags.cjs
- packages/lib/preprocess/src/extract-queries/extract-queries.cjs
- packages/lib/preprocess/src/partials/inject-partials.cjs
- packages/lib/preprocess/src/partials/inject-partials.spec.js
- packages/lib/preprocess/src/process-queries.cjs
- packages/lib/preprocess/src/utils/get-prism-langs.cjs
- packages/lib/preprocess/src/utils/highlighter.cjs
- packages/lib/preprocess/src/utils/supportedLanguages.cjs
- packages/lib/preprocess/tsconfig.json
- pnpm-lock.yaml
Fixes preprocess tsconfig to include `*.cjs` and `*.js`, and fixes all type errors that popped up as a result
> Fix preprocess tsconfig

- sites/docs/pages/deployment/rendering-modes.md
> fix: spa docs

- .changeset/fuzzy-maps-beg.md
- packages/ui/core-components/src/lib/devtools/_DevTools.svelte
- packages/ui/core-components/src/lib/devtools/query-debugger/QueryDebugger.svelte
- pnpm-lock.yaml
- sites/test-env/pages/empty-codeblock.md
Fixes an issue with memory caused by the `QueryDebugger`'s `module` code
> fix: add dev fences to modules code

- packages/lib/sdk/src/lib/history/index.js
> fix: sdk build

- .changeset/healthy-humans-occur.md
- .changeset/kind-lamps-play.md
> chore: add changesets

- .changeset/twenty-squids-mate.md
- packages/ui/core-components/src/lib/atoms/inputs/dropdown/dropdownOptionStore.js
> fix: defer selectAll

- MONOREPO_ROADMAP.md
This file contains an outline of where we would like the monorepo to end up within the next 6-12 months. It also includes a glossary of common terms that are used within the document.
> Introduce a roadmap document

- .changeset/tiny-kiwis-refuse.md
- packages/datasources/snowflake/index.cjs
Adds `resultPrefetch` option to snowflake for use with very large datasets
> Add resultPrefetch option to snowflake connector

- .changeset/nervous-geese-serve.md
- .github/workflows/chromatic.yml
> chore: add changeset

- packages/ui/core-components/src/lib/unsorted/viz/map/AreaMap.svelte
- packages/ui/core-components/src/lib/unsorted/viz/map/BubbleMap.svelte
- sites/docs/pages/components/area-map.md
- sites/docs/pages/components/bubble-map.md
- sites/docs/pages/components/point-map.md
> updated area, bubble, point legend sections docs

- .changeset/chatty-feet-raise.md
- packages/ui/core-components/src/lib/organisms/layout/EvidenceDefaultLayout.svelte
- pnpm-lock.yaml
- sites/example-project/src/service-worker.js
Resolves https://github.com/evidence-dev/evidence/issues/2474
Demo:
https://github.com/user-attachments/assets/8babc02c-86af-459c-8cd1-f3103308fc16
> Add env flag to disable windows cache service worker

- .changeset/rotten-dingos-fail.md
- sites/example-project/src/service-worker.js
See discussion here: https://github.com/evidence-dev/evidence/issues/2474#issuecomment-2408988287
> Windows cache service worker isnt asynchronous

- .changeset/five-students-wait.md
- packages/lib/sdk/src/usql/setTrackProxy/setTrackProxy.js
> fix: remove log

- .changeset/shy-bottles-agree.md
- packages/lib/sdk/package.json
- packages/lib/sdk/src/lib/debug.js
- packages/lib/sdk/src/logger/EvidenceLogger.js
- packages/lib/sdk/src/logger/index.js
Adds a basic `EvidenceLogger` class, this will be used to enforce consistent logging standards and formatting across Evidence's tooling
> feat: add basic EvidenceLogger

- sites/docs/pages/deployment/rendering-modes.md
See [slack](https://evidencedev.slack.com/archives/C023LRB9Z40/p1729789000447219) for details
> Docs: SPA mode must be on private site

- .changeset/tasty-parents-punch.md
- packages/lib/component-utilities/src/getSeriesConfig.js
- packages/ui/core-components/src/lib/unsorted/viz/area/Area.svelte
- packages/ui/core-components/src/lib/unsorted/viz/area/AreaChart.stories.svelte
- packages/ui/core-components/src/lib/unsorted/viz/area/AreaChart.svelte
- packages/ui/core-components/src/lib/unsorted/viz/bar/Bar.svelte
- packages/ui/core-components/src/lib/unsorted/viz/bar/BarChart.stories.svelte
- packages/ui/core-components/src/lib/unsorted/viz/bar/BarChart.svelte
- packages/ui/core-components/src/lib/unsorted/viz/bubble/Bubble.svelte
- packages/ui/core-components/src/lib/unsorted/viz/bubble/BubbleChart.stories.svelte
- packages/ui/core-components/src/lib/unsorted/viz/bubble/BubbleChart.svelte
- packages/ui/core-components/src/lib/unsorted/viz/line/Line.svelte
- packages/ui/core-components/src/lib/unsorted/viz/line/LineChart.stories.svelte
- packages/ui/core-components/src/lib/unsorted/viz/line/LineChart.svelte
- packages/ui/core-components/src/lib/unsorted/viz/scatter/Scatter.svelte
- packages/ui/core-components/src/lib/unsorted/viz/scatter/ScatterPlot.stories.svelte
- packages/ui/core-components/src/lib/unsorted/viz/scatter/ScatterPlot.svelte
- sites/docs/pages/components/area-chart/index.md
- sites/docs/pages/components/bar-chart/index.md
- sites/docs/pages/components/bubble-chart/index.md
- sites/docs/pages/components/line-chart/index.md
- sites/docs/pages/components/scatter-plot/index.md
Attempt to fix #2663 - let me know what you think
> Add seriesOrder parameter (fixes #2663)

- sites/docs/pages/core-concepts/data-sources/index.md
Remove warning message about USQL changing data sources
> Remove update warning on docs sources page

- sites/docs/pages/deployment/rendering-modes/index.md
This PR updates the docs to provide an example nginx config for self hosting evidence in SPA mode
> add explanation how to selfhost SPA

- pnpm-lock.yaml
To fix failing checks here: https://github.com/evidence-dev/evidence/pull/2788
> chore: pnpm i

- sites/docs/pages/deployment/rendering-modes/index.md
> docs: mark as code fence

- sites/docs/pages/components/dropdown/index.md
> docs: multi dropdown 

- packages/ui/core-components/src/lib/unsorted/viz/map/components/Legend Components/CategoricalLegend.svelte
- packages/ui/core-components/src/lib/unsorted/viz/map/components/Legend Components/LegendToggle.svelte
- packages/ui/core-components/src/lib/unsorted/viz/map/components/Legend Components/ScalarLegend.svelte
- packages/ui/core-components/src/lib/unsorted/viz/map/components/Legend.svelte
Before (light)
After (light)
Before (dark)
After (dark)
- ~~[ ] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)~~
> [Theming] Map legend

- sites/docs/pages/core-concepts/dot-functions/index.md
- sites/docs/pages/core-concepts/exports/index.md
- sites/docs/pages/core-concepts/query-functions/index.md
This documents how to use `.where()` and similar functions
- What should these be called?
- Dot functions
- Query functions
- Mutator functions
- something else?
> Docs for "Query functions"

- .changeset/unlucky-ants-enjoy.md
- packages/evidence/cli.js
- packages/evidence/scripts/build-template.js
Cherry picking commits from https://github.com/evidence-dev/evidence/pull/2853 into `main` for a hotfix release
> [Hotfix] dev server logging

- .changeset/giant-parrots-push.md
- packages/lib/sdk/src/utils/svelte/addBasePath.js
- packages/lib/sdk/src/utils/svelte/addBasePath.spec.js
- sites/test-env/pages/null-datatable.md
> Ignore non-strings in `addBasePath`

- sites/docs/pages/deployment/base-paths/index.md
> Clarify base path docs

- sites/docs/pages/deployment/overview/index.md
> uncomment HF spaces

- sites/docs/pages/core-concepts/themes/index.md
> Move Themes lower in docs

- .changeset/odd-fans-accept.md
- packages/lib/sdk/src/plugins/datasources/index.js
- packages/lib/sdk/src/plugins/datasources/loadSourceConfig.js
- sites/example-project/src/pages/settings/+page.server.js
- sites/example-project/src/pages/settings/+page.svelte
> fix: environemnt variables appear in the deploy section again

- sites/docs/pages/core-concepts/themes/index.md
> fix link typo in themes

- .github/workflows/changesets.yml
Fixes CI issues with https://github.com/evidence-dev/evidence/pull/2907
> Don't run changesets on extension

- .changeset/khaki-coats-talk.md
- packages/ui/core-components/src/lib/atoms/inputs/button-group/ButtonGroup.svelte
- packages/ui/core-components/src/lib/unsorted/viz/core/Chart.svelte
- packages/ui/core-components/src/lib/unsorted/viz/core/EmptyChart.svelte
- packages/ui/core-components/src/lib/unsorted/viz/core/ErrorChart.stories.svelte
- packages/ui/core-components/src/lib/unsorted/viz/core/ErrorChart.svelte
- packages/ui/core-components/src/lib/unsorted/viz/core/Sparkline.svelte
- packages/ui/core-components/src/lib/unsorted/viz/core/_Chart.svelte
- packages/ui/core-components/src/lib/unsorted/viz/funnel/FunnelChart.svelte
- packages/ui/core-components/src/lib/unsorted/viz/funnel/_FunnelChart.svelte
- packages/ui/core-components/src/lib/unsorted/viz/heatmap/CalendarHeatmap.svelte
- packages/ui/core-components/src/lib/unsorted/viz/heatmap/Heatmap.svelte
- packages/ui/core-components/src/lib/unsorted/viz/heatmap/_CalendarHeatmap.svelte
- packages/ui/core-components/src/lib/unsorted/viz/heatmap/_Heatmap.svelte
- packages/ui/core-components/src/lib/unsorted/viz/map/BaseMap.svelte
- packages/ui/core-components/src/lib/unsorted/viz/map/EChartsMap.svelte
- packages/ui/core-components/src/lib/unsorted/viz/map/USMap.svelte
- packages/ui/core-components/src/lib/unsorted/viz/map/_BaseMap.svelte
- packages/ui/core-components/src/lib/unsorted/viz/map/_USMap.svelte
- packages/ui/core-components/src/lib/unsorted/viz/references/ReferenceArea/ReferenceArea.svelte
- packages/ui/core-components/src/lib/unsorted/viz/references/ReferenceLine/ReferenceLine.svelte
- packages/ui/core-components/src/lib/unsorted/viz/references/ReferencePoint/ReferencePoint.svelte
- packages/ui/core-components/src/lib/unsorted/viz/sankey/SankeyDiagram.svelte
- packages/ui/core-components/src/lib/unsorted/viz/table/DataTable.svelte
- packages/ui/core-components/src/lib/unsorted/viz/table/_DataTable.svelte
- pnpm-lock.yaml
This has some small QoL changes to `ErrorChart`:
- `chartType` is now `title`
- Error text is rendered in a `pre` tag, so that DuckDB's error messages appear properly formatted
- (Dead) Legacy error messages have been removed
> Error Chart Improvment

- sites/docs/pages/components/custom-components/index.md
> relative -> absolute link

- .changeset/witty-apples-taste.md
- package.json
- packages/lib/sdk/package.json
- packages/ui/core-components/package.json
- pnpm-lock.yaml
Fixes https://github.com/evidence-dev/evidence/security/dependabot/214
> vuln: upgrade nanoid to 5.0.9

- sites/docs/pages/deployment/github-pages/index.md
addresses https://github.com/evidence-dev/evidence/issues/2919
> docs: more explicit build path instructions

- .changeset/funny-mayflies-refuse.md
- packages/ui/core-components/src/lib/unsorted/viz/table/TableCell.svelte
- packages/ui/core-components/src/lib/unsorted/viz/table/TableHeader.svelte
- pnpm-lock.yaml
Fixes https://github.com/evidence-dev/evidence/issues/2928
Issues when using wrapTitle 
Added wraptitle check to handle alignment for specific use cases
> fixed wrapTitle Alignment issues

- sites/docs/pages/deployment/self-host/github-pages/index.md
> Docs: More explicit base path instructions for GH pages

- .changeset/light-candles-explode.md
- packages/ui/core-components/src/lib/organisms/layout/EvidenceDefaultLayout.svelte
> update default layout

- .changeset/selfish-zoos-doubt.md
- packages/ui/core-components/src/lib/unsorted/viz/bubble/Bubble.svelte
Noticed this while doing another PR
> Bubble chart remove log

- sites/docs/pages/reference/cli/index.md
Always forget to include the extra `--` when running a modified CLI command. Adding an alert so that info pops on the page more
> Add alert to CLI docs

- sites/docs/pages/components/charts/line-chart/index.md
> Docs: typo

- .changeset/four-mugs-taste.md
- e2e/dev-server-startup/package.json
- packages/datasources/javascript/package.json
- packages/lib/component-utilities/package.json
- packages/lib/preprocess/package.json
- packages/lib/sdk/package.json
- packages/lib/universal-sql/package.json
- packages/ui/core-components/package.json
- packages/ui/tailwind/package.json
- pnpm-lock.yaml
- sites/docs/package.json
- sites/example-project/package.json
> Attemp to upgrade vitest

- .changeset/cool-vans-lick.md
- packages/lib/sdk/src/plugins/datasources/writeSourceConfig.js
> chore: handle malformed source directories

- sites/docs/pages/deployment/self-host/windows-iis/index.md
> Fixes spelling mistake
